# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ranposu_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'function_path': 'animated_java:ranposu_aj/animations/down_end/stop'}
tag @s remove aj.ranposu_aj.animation.down_end.playing
scoreboard players set @s aj.frame 0
execute at @s run function animated_java:ranposu_aj/animations/down_end/zzz/set_frame {frame: 0}