# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_0) positioned ^0 ^1.0605 ^-0.6908 rotated ~0 ~10 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_hitbox_body_0
$execute as $(hitbox_body_1) positioned ^0 ^0.6557 ^1.576 rotated ~0 ~0 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_hitbox_body_1
execute positioned ^0 ^1.8702 ^3.415 rotated ~0 ~2.5 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_pos_head
$execute as $(hitbox_head_0) positioned ^0 ^1.2565 ^3.3882 rotated ~0 ~2.5 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_hitbox_head_0
$execute as $(hitbox_tail_0) positioned ^0 ^1.2302 ^-1.9934 rotated ~0 ~-12.5 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_hitbox_tail_0
$execute as $(hitbox_tail_1) positioned ^0 ^0.903 ^-2.9696 rotated ~0 ~-22.5 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_hitbox_tail_1
$execute as $(shadow) positioned ^0 ^0.3656 ^-0.225 rotated ~0 ~0 run function animated_java_ranposu:ranposu/animations/state_paralysis_end/zzz/frames/36_locator_shadow