# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7999f,-0.0196f,1.3635f,0f,-0.0196f,-1.7999f,3.3259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7993f,-0.0491f,1.3677f,0f,-0.0491f,-1.7993f,2.9509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.674f,0.6615f,1.4496f,0f,0.6615f,-1.674f,2.6232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6981f,0.5971f,1.2479f,0f,0.5971f,-1.6981f,2.2577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7805f,0.2641f,1.342f,0f,0.2641f,-1.7805f,1.9589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2553f,-1.29f,0.8163f,0f,-1.29f,-1.2553f,1.528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7823f,-0.252f,1.0094f,0f,-0.252f,-1.7823f,1.0242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.428f,1.0958f,1.2744f,0f,1.0958f,-1.428f,1.481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.2866f,-1.2588f,0.7627f,0f,-1.2588f,-1.2866f,1.5771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.776f,-0.2932f,0.9441f,0f,-0.2932f,-1.776f,1.0689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.5757f,0.8701f,1.2744f,0f,0.8701f,-1.5757f,1.481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7882f,0.2057f,1.3983f,0f,0.2057f,-1.7882f,0.9462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7998f,0.0295f,0.8636f,0f,0.0295f,-1.7998f,-0.4233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4574f,1.0564f,0.9275f,0f,1.0564f,-1.4574f,0.1918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.61f,-0.8049f,1.585f,0f,-0.8049f,-1.61f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.8496f,0f,0f,-1.8f,-0.7335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4745f,1.0324f,0.9236f,0f,1.0324f,-1.4745f,-0.1195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.8f,0f,1.585f,0f,0f,-1.8f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7955f,0.1275f,1.9812f,0f,0.1275f,-1.7955f,-2.6227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7978f,0.0883f,1.9316f,0f,0.0883f,-1.7978f,-1.6114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7968f,0.1079f,1.8377f,0f,0.1079f,-1.7968f,-0.5182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7107f,0.56f,1.5786f,0f,0.56f,-1.7107f,0.147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0563778025,"pz":-0.8555543539,"ry":0,"rx":18.125},"hitbox_body_1":{"px":0,"py":0.3461237062,"pz":1.3601882109,"ry":0,"rx":6.5625},"pos_head":{"px":0,"py":1.3812916686,"pz":3.3475594352,"ry":0,"rx":-1.5625},"hitbox_head_0":{"px":0,"py":0.7672700617,"pz":3.3643084292,"ry":0,"rx":-1.5625},"hitbox_tail_0":{"px":0,"py":1.4354882026,"pz":-2.1921275669,"ry":0,"rx":2.8125},"hitbox_tail_1":{"px":0,"py":1.5059255529,"pz":-3.3263088512,"ry":0,"rx":4.0625},"shadow":{"px":0,"py":0.225,"pz":-0.305859375,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args