# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7749f,0.2997f,1.8032f,0f,0.2997f,-1.7749f,3.395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7988f,0.0654f,1.8313f,0f,0.0654f,-1.7988f,3.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,1.8311f,0f,0.2349f,-1.7846f,2.6832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7601f,0.3768f,1.5847f,0f,0.3768f,-1.7601f,2.3463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.6869f,0f,0.3126f,-1.7727f,2.0502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2161f,-1.3271f,0.9727f,0f,-1.3271f,-1.2161f,1.7696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7749f,-0.2997f,1.1523f,0f,-0.2997f,-1.7749f,1.2608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7387f,0.4659f,1.5719f,0f,0.4659f,-1.7387f,1.5814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3003f,-1.2447f,0.9773f,0f,-1.2447f,-1.3003f,1.7519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7791f,-0.2738f,1.1642f,0f,-0.2738f,-1.7791f,1.2457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7206f,0.5288f,1.5719f,0f,0.5288f,-1.7206f,1.5814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7998f,0.0262f,1.6419f,0f,0.0262f,-1.7998f,1.0369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.882f,0f,0.0785f,-1.7983f,-0.3982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6026f,0.8195f,1.0399f,0f,0.8195f,-1.6026f,0.1998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6823f,-0.6402f,1.7104f,0f,-0.6402f,-1.6823f,0.1024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7988f,0.0654f,0.8724f,0f,0.0654f,-1.7988f,-0.446f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6085f,0.8078f,1.0346f,0f,0.8078f,-1.6085f,0.1509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7244f,-0.5162f,1.7104f,0f,-0.5162f,-1.7244f,0.1024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,-0.4405f,1.7347f,0f,-0.4405f,-1.7453f,-2.5682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.777f,-0.2868f,1.896f,0f,-0.2868f,-1.777f,-1.5686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7996f,-0.0393f,1.8918f,0f,-0.0393f,-1.7996f,-0.4714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7679f,0.3383f,1.7192f,0f,0.3383f,-1.7679f,0.2213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0739800455,"pz":-0.7068734651,"ry":0,"rx":10.8333333333},"hitbox_body_1":{"px":0,"py":0.6362232198,"pz":1.5538671291,"ry":0,"rx":0.8333333333},"pos_head":{"px":0,"py":1.8196571705,"pz":3.4177532349,"ry":0,"rx":2.0833333333},"hitbox_head_0":{"px":0,"py":1.2058131832,"pz":3.3954233958,"ry":0,"rx":2.0833333333},"hitbox_tail_0":{"px":0,"py":1.2902084362,"pz":-2.03374631,"ry":0,"rx":-9.1666666667},"hitbox_tail_1":{"px":0,"py":1.0631450727,"pz":-3.0878255879,"ry":0,"rx":-14.1666666667},"shadow":{"px":0,"py":0.365625,"pz":-0.2315625,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args