# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.head_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.head_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.neck_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.neck_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.neck_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.tail_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.tail_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.tail_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.tail_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.tail_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dino_aj.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out