# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:reus_aj/animations/land_down_l/zzz/apply_frame {frame: 35}
scoreboard players add @s aj.land_down_l.frame 1