# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.6709f,-0.6688f,-0.0266f,0.0149f,-0.6689f,1.6711f,0.003f,1.3869f,0.0236f,0.0126f,-1.7998f,4.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.6709f,-0.667f,-0.0557f,-0.0019f,-0.6689f,1.6694f,0.0759f,1.4161f,0.0236f,0.0911f,-1.7975f,4.189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.7872f,-0.2115f,-0.032f,-0.0028f,-0.2121f,1.7171f,0.4967f,1.4663f,-0.0279f,0.497f,-1.7298f,3.855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.7997f,-0.0316f,-0.0115f,0.0009f,-0.0325f,1.4744f,1.0321f,1.3705f,-0.0087f,1.0321f,-1.4747f,3.4487f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.7997f,-0.0337f,0f,0f,-0.0325f,1.7384f,0.4656f,1.498f,-0.0087f,0.4655f,-1.7388f,3.1626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9671f,-1.5181f,0.9612f,0f,-1.5181f,-0.9671f,2.4553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.5588f,0.9f,1.4239f,0f,0.9f,-1.5588f,2.1776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,0.4659f,1.7387f,1.356f,0f,1.7387f,-0.4659f,2.7013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.2579f,-1.2875f,0.9568f,0f,-1.2875f,-1.2579f,2.8406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6507f,-0.7177f,1.0087f,0f,-0.7177f,-1.6507f,2.3034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.6109f,0.8032f,1.356f,0f,0.8032f,-1.6109f,2.7013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,-0.0785f,1.3941f,0f,-0.0785f,-1.7983f,2.1537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.7983f,0.0785f,0f,0.4168f,0.0784f,1.7966f,-0.0785f,0.8189f,-0.0034f,-0.0784f,-1.7983f,0.9274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.663f,0.6888f,1.024f,0f,0.6888f,-1.663f,1.5109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.4745f,-1.0324f,1.6503f,0f,-1.0324f,-1.4745f,1.2523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7387f,0.4659f,0.9531f,0f,0.4659f,-1.7387f,0.663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.3789f,1.157f,0.9733f,0f,1.157f,-1.3789f,1.2811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7387f,-0.4659f,1.6503f,0f,-0.4659f,-1.7387f,1.2523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7235f,-0.1344f,0.5014f,-0.0055f,0.0405f,1.6986f,0.5943f,2.7628f,-0.5175f,0.5804f,-1.6234f,-1.2078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7929f,-0.0078f,0.159f,-0.095f,0.0507f,1.676f,0.6545f,2.3947f,-0.1509f,0.6564f,-1.6692f,-0.2688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7932f,0.0146f,-0.1562f,0f,-0.0472f,1.6588f,0.6971f,1.944f,0.1496f,0.6986f,-1.6522f,0.727f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.663f,0.6888f,1.6348f,0f,0.6888f,-1.663f,1.3705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.1906,"pz":0.3311,"ry":0,"rx":22.5},"hitbox_body_1":{"px":0,"py":0.4203,"pz":2.7282,"ry":0,"rx":-2.5},"pos_head":{"px":0.0092,"py":1.4019,"pz":4.5855,"ry":358.2243,"rx":2.4155},"hitbox_head_0":{"px":0.2368,"py":0.8323,"pz":4.5544,"ry":358.2243,"rx":2.4155},"hitbox_tail_0":{"px":-0.0436,"py":2.1088,"pz":-0.9752,"ry":5.442,"rx":21.3208},"hitbox_tail_1":{"px":0.2197,"py":2.489,"pz":-1.9793,"ry":17.1635,"rx":19.2799},"shadow":{"px":0,"py":0.2813,"pz":0.9177,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args