# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0.1308 ^-0.1743 ^0.3281 ~0 ~0
data modify storage animated_java:temp entry.data.locators.hitbox_arm_left_0 merge value { px: 0.1308, py: -0.1743, pz: 0.3281, ry: 0, rx: 0 }