# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7987f,-0.0672f,2.3057f,0f,-0.0672f,-1.7987f,-2.4401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7859f,0.2248f,2.1792f,0f,0.2248f,-1.7859f,-1.4355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7342f,0.4822f,1.8582f,0f,0.4822f,-1.7342f,-0.3862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_tail_0":{"px":2.5132715754286375e-16,"py":1.7287324182435158,"pz":-2.052241982895374,"ry":0,"rx":7.174285714285724},"hitbox_tail_1":{"px":3.7819665060851623e-16,"py":1.7571130379234736,"pz":-3.08821001183224,"ry":0,"rx":-2.1385714285714132}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args