# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7695f,-0.33f,2.0169f,0f,-0.33f,-1.7695f,-2.4801f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7994f,-0.0452f,2.0423f,0f,-0.0452f,-1.7994f,-1.4679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7817f,0.2563f,1.8582f,0f,0.2563f,-1.7817f,-0.3862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_tail_0":{"px":2.4618865684510287e-16,"py":1.5045437287342187,"pz":-2.0102829404895277,"ry":0,"rx":-1.4375000000000062},"hitbox_tail_1":{"px":3.7240457992660114e-16,"py":1.3793151395969687,"pz":-3.0409141655037493,"ry":0,"rx":-10.562500000000002}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args