# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7852f,-0.2301f,1.9744f,0f,-0.2301f,-1.7852f,-2.4853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7995f,-0.0442f,1.9992f,0f,-0.0442f,-1.7995f,-1.4731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7888f,0.2008f,1.8489f,0f,0.2008f,-1.7888f,-0.3862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_tail_0":{"px":2.468611593681653e-16,"py":1.4617528034083866,"pz":-2.015774340324407,"ry":0,"rx":-1.4062499999999987},"hitbox_tail_1":{"px":3.7731856715792777e-16,"py":1.3692744769255443,"pz":-3.0810399163304205,"ry":0,"rx":-7.343750000000003}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args