# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,0.3896f,1.7573f,5.0077f,0f,1.7573f,-0.3896f,3.2563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.5966f,0.8311f,5.1935f,0f,0.8311f,-1.5966f,2.9305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,0.3896f,5.2228f,0f,0.3896f,-1.7573f,2.594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,4.9502f,0f,0.2349f,-1.7846f,2.2779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,-0.3126f,4.945f,0f,-0.3126f,-1.7727f,1.9646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7167f,-0.5086f,0.1851f,0.6623f,0f,-0.6156f,-1.6914f,4.108f,0.5413f,-1.6132f,0.5871f,2.281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7167f,-0.1851f,-0.5086f,0.5047f,0f,1.6914f,-0.6156f,4.1926f,0.5413f,-0.5871f,-1.6132f,1.7719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7167f,-0.3991f,-0.3657f,0.4078f,0f,1.2161f,-1.3271f,4.6708f,0.5413f,-1.2657f,-1.1598f,1.5674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7387f,0.3816f,-0.2672f,-0.5814f,0f,-1.0324f,-1.4745f,4.7107f,-0.4659f,-1.4242f,0.9973f,2.1064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7387f,0.4659f,0f,-0.5163f,0f,0f,-1.8f,4.2388f,-0.4659f,-1.7387f,0f,1.8529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.3929f,0.2503f,-0.4078f,0f,0.9671f,-1.5181f,4.6708f,-0.4659f,-1.4664f,-0.9342f,1.5674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,-0.6156f,4.5425f,0f,-0.6156f,-1.6914f,1.0336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.5588f,0.9f,3.4137f,0f,0.9f,-1.5588f,-0.6556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7573f,0.3896f,3.717f,0f,0.3896f,-1.7573f,-0.1166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.7846f,0.2349f,4.3535f,0f,0.2349f,-1.7846f,0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7846f,-0.2349f,3.75f,0f,-0.2349f,-1.7846f,0.2575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7932f,0.1569f,4.121f,0f,0.1569f,-1.7932f,0.7523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.2349f,-1.7846f,4.3535f,0f,-1.7846f,-0.2349f,0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7387f,-0.4659f,3.035f,0f,-0.4659f,-1.7387f,-2.1106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.4745f,-1.0324f,3.6157f,0f,-1.0324f,-1.4745f,-1.2812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2728f,-1.2728f,4.3715f,0f,-1.2728f,-1.2728f,-0.4857f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,-0.1569f,4.3944f,0f,-0.1569f,-1.7932f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":3.5204047065,"pz":-0.4890561766,"ry":0,"rx":-5},"hitbox_body_1":{"px":0,"py":3.7864800226,"pz":1.8744403879,"ry":0,"rx":-20},"pos_head":{"px":0,"py":5.0127204671,"pz":3.283869906,"ry":0,"rx":27.5},"hitbox_head_0":{"px":0,"py":4.4678740628,"pz":3.0002408203,"ry":0,"rx":27.5},"hitbox_tail_0":{"px":0,"py":2.8678044234,"pz":-1.4358085837,"ry":0,"rx":-35},"hitbox_tail_1":{"px":0,"py":2.3559393134,"pz":-2.6203483523,"ry":0,"rx":-15},"shadow":{"px":0,"py":3.0408145696,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args