# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.3743f,1.1625f,1.1426f,0f,1.1625f,-1.3743f,3.2754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.3223f,1.2213f,1.4075f,0f,1.2213f,-1.3223f,3.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.5143f,0.9732f,1.5513f,0f,0.9732f,-1.5143f,2.7042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6602f,0.6954f,1.3713f,0f,0.6954f,-1.6602f,2.3276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7291f,0.5003f,1.5046f,0f,0.5003f,-1.7291f,2.0441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7448f,0.228f,0.3791f,0.3789f,-0.1077f,1.2771f,-1.2639f,0.7308f,-0.429f,-1.2478f,-1.2243f,1.9777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7448f,-0.0306f,0.4413f,0.4929f,-0.1077f,1.7711f,-0.3029f,0.9091f,-0.429f,-0.32f,-1.7186f,1.4813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7448f,-0.021f,0.4419f,0.4078f,-0.1077f,1.764f,-0.3414f,1.424f,-0.429f,-0.3574f,-1.7112f,1.5682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7943f,0.0101f,-0.143f,-0.4279f,0.0912f,1.4654f,-1.0413f,0.7474f,0.1105f,-1.0453f,-1.4612f,1.8984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7943f,0.0716f,-0.1242f,-0.4529f,0.0912f,1.7731f,-0.2964f,0.9278f,0.1105f,-0.3017f,-1.7711f,1.3904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.2241f,0.4084f,-0.4078f,0.1969f,1.7837f,-0.1405f,1.424f,-0.4222f,-0.091f,-1.7474f,1.5682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,0.1569f,1.5333f,0f,0.1569f,-1.7932f,1.0302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7941f,0.1462f,0.8354f,0f,0.1462f,-1.7941f,0.0524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5006f,0.9941f,0.9252f,0f,0.9941f,-1.5006f,0.6644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.7184f,-1.6504f,1.3243f,0f,-1.6504f,-0.7184f,0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7387f,0.4659f,0.941f,0f,0.4659f,-1.7387f,-0.4885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,0.6156f,1.6914f,0.6494f,0f,1.6914f,-0.6156f,0.057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7846f,-0.2349f,1.3243f,0f,-0.2349f,-1.7846f,0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.4745f,1.0324f,1.7036f,0f,1.0324f,-1.4745f,-2.5333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,0.6156f,1.3573f,0f,0.6156f,-1.6914f,-1.5819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.3291f,0f,0f,-1.8f,-0.485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7893f,-0.196f,1.3676f,0f,-0.196f,-1.7893f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.4782209844,"pz":-0.4698199039,"ry":0,"rx":-6.25},"hitbox_body_1":{"px":0,"py":0.4927710247,"pz":1.4727275049,"ry":0,"rx":5},"pos_head":{"px":0,"py":1.1402271337,"pz":3.3033139921,"ry":0,"rx":42.7272727273},"hitbox_head_0":{"px":0,"py":0.6890041767,"pz":2.8865395861,"ry":0,"rx":42.7272727273},"hitbox_tail_0":{"px":0,"py":1.0549528091,"pz":-2.2832440759,"ry":0,"rx":20},"hitbox_tail_1":{"px":0,"py":1.6576052653,"pz":-3.3811842456,"ry":0,"rx":35},"shadow":{"px":0,"py":0.0140625,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args