# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^1.5217 ^1.3813 ^-1.7078 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^-0.3968 ^1.4924 ^-1.4031 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^-2.0159 ^0.7095 ^-1.0037 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_neck_1
$execute as $(hitbox_neck_0) positioned ^-3.2633 ^0.3967 ^-0.4792 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_neck_0
execute positioned ^-3.5603 ^0.8047 ^1.043 rotated ~358.2269 ~19.1025 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_head
$execute as $(head_0) positioned ^-3.55 ^-0.3395 ^0.528 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_head_0
$execute as $(hitbox_arm_right_0) positioned ^-2.3094 ^-0.6496 ^-3.5371 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_arm_right_0
$execute as $(hitbox_arm_left_0) positioned ^0.1318 ^-0.77 ^1.2911 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_arm_left_0
execute positioned ^-2.1591 ^4.7148 ^-6.398 rotated ~50.3976 ~43.7304 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_muzzle_r_0
execute positioned ^-2.3309 ^6.9516 ^-5.4698 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_muzzle_r_1
execute positioned ^-5.8748 ^-0.5752 ^-3.3207 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_r_0
execute positioned ^-4.6857 ^2.009 ^-4.0533 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_r_1
execute positioned ^-3.4966 ^4.5932 ^-4.7859 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_r_2
execute positioned ^-2.3074 ^7.1775 ^-5.5186 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_r_3
execute positioned ^-1.1183 ^9.7617 ^-6.2512 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_r_4
execute positioned ^0.0708 ^12.3459 ^-6.9838 rotated ~58.3634 ~61.6101 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_r_5
$execute as $(hitbox_finger_right_0) positioned ^-4.0916 ^1.5545 ^-4.1501 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_right_0
$execute as $(hitbox_finger_right_1) positioned ^-2.6125 ^3.6006 ^-4.4173 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_right_1
$execute as $(hitbox_finger_right_2) positioned ^-1.4189 ^6.222 ^-5.2942 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_right_2
$execute as $(hitbox_finger_right_3) positioned ^-0.138 ^9.0353 ^-6.2353 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_right_3
execute positioned ^-1.659 ^3.0401 ^-5.6661 rotated ~62.344 ~25.6711 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_muzzle_r_2
execute positioned ^0.203 ^6.9472 ^2.9086 rotated ~96.127 ~40.3294 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_muzzle_l_0
execute positioned ^0.5109 ^8.4081 ^0.9941 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_muzzle_l_1
execute positioned ^-5.0278 ^2.0631 ^2.6958 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_l_0
execute positioned ^-3.1533 ^4.2465 ^2.106 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_l_1
execute positioned ^-1.2788 ^6.4299 ^1.5161 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_l_2
execute positioned ^0.5957 ^8.6134 ^0.9262 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_l_3
execute positioned ^2.4702 ^10.7968 ^0.3363 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_l_4
execute positioned ^4.3447 ^12.9802 ^-0.2535 rotated ~72.532 ~48.0123 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_wing_l_5
$execute as $(hitbox_finger_left_0) positioned ^-2.5584 ^3.6284 ^2.0344 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_left_0
$execute as $(hitbox_finger_left_1) positioned ^-1.6206 ^5.4102 ^2.0749 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_left_1
$execute as $(hitbox_finger_left_2) positioned ^0.2824 ^7.6931 ^1.5923 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_left_2
$execute as $(hitbox_finger_left_3) positioned ^2.3246 ^10.1431 ^1.0745 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_finger_left_3
execute positioned ^0.1842 ^5.0638 ^3.115 rotated ~101.105 ~20.2685 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_muzzle_l_2
$execute as $(hitbox_leg_right_0) positioned ^0.5573 ^0.6355 ^-3.4576 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_leg_right_0
$execute as $(hitbox_leg_left_0) positioned ^0.8038 ^0.9056 ^-0.4209 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_leg_left_0
$execute as $(hitbox_tail_0) positioned ^2.4772 ^1.0293 ^-1.2624 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_0
$execute as $(hitbox_tail_1) positioned ^4.3859 ^0.4969 ^-1.5649 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_1
$execute as $(hitbox_tail_2) positioned ^6.4028 ^0.0533 ^-1.2975 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_2
$execute as $(hitbox_tail_3) positioned ^7.8904 ^-0.1045 ^-2.5682 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_3
$execute as $(hitbox_tail_4) positioned ^9.245 ^-0.0766 ^-4.115 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_4
$execute as $(shadow) positioned ^1.1875 ^0.9012 ^-1.5334 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_shadow
execute positioned ^1.1875 ^-0.2738 ^-1.3131 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_pos_comet_star
execute positioned ^1.1875 ^3.2513 ^-3.3694 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_beam_start
execute positioned ^1.1875 ^3.2513 ^-3.3693 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_counter_mirror/zzz/frames/61_locator_beam_end