# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.ranposu_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ranposu_aj', 'function_path': 'animated_java:ranposu_aj/animations/anger/next_frame'}
execute if score @s aj.anger.frame matches 56.. run scoreboard players set @s aj.anger.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.anger.frame
execute at @s run function animated_java:ranposu_aj/animations/anger/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.anger.frame 1