# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7268f,0.5081f,0.8236f,0f,0.5081f,-1.7268f,3.2972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.6982f,0.5966f,0.9614f,0f,0.5966f,-1.6982f,2.9484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.408f,1.1214f,1.1354f,0f,1.1214f,-1.408f,2.6589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.3833f,1.1517f,1.0738f,0f,1.1517f,-1.3833f,2.2461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.4743f,1.0326f,1.2916f,0f,1.0326f,-1.4743f,2.0209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7276f,0.4851f,0.1419f,0.3789f,-0.0167f,0.4504f,-1.7427f,0.4502f,-0.5051f,-1.6739f,-0.4278f,1.7654f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7276f,-0.1208f,0.4908f,0.4927f,-0.0167f,1.7605f,0.3746f,0.8044f,-0.5051f,0.355f,-1.6908f,1.3745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7276f,0.0046f,0.5054f,0.4078f,-0.0167f,1.7984f,-0.0734f,1.3003f,-0.5051f,-0.0752f,-1.726f,1.5383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7964f,-0.1003f,-0.0521f,-0.4014f,-0.0167f,1.0565f,-1.4572f,0.4953f,0.1118f,-1.4539f,-1.0554f,1.5719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7964f,0.0187f,-0.1114f,-0.4307f,-0.0167f,1.7119f,0.5561f,0.89f,0.1118f,0.5561f,-1.7083f,1.2051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7293f,0.1684f,0.4701f,-0.4078f,0.2906f,1.7175f,0.4536f,1.3003f,-0.4061f,0.5117f,-1.6773f,1.5383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7333f,0.4855f,1.5071f,0f,0.4855f,-1.7333f,1.0298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7993f,-0.0514f,0.9057f,0f,-0.0514f,-1.7993f,0.073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.3969f,1.1351f,0.9356f,0f,1.1351f,-1.3969f,0.6907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.6026f,-1.6961f,1.2959f,0f,-1.6961f,-0.6026f,0.1169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7732f,-0.3097f,0.7411f,0f,-0.3097f,-1.7732f,-0.2661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.1681f,1.3695f,0.6586f,0f,1.3695f,-1.1681f,0.3469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.5197f,-0.9647f,1.2959f,0f,-0.9647f,-1.5197f,0.1169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.4209f,1.105f,1.6494f,0f,1.105f,-1.4209f,-2.5347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6934f,0.6102f,1.3061f,0f,0.6102f,-1.6934f,-1.5821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7997f,-0.0349f,1.2993f,0f,-0.0349f,-1.7997f,-0.4849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7888f,-0.2003f,1.3395f,0f,-0.2003f,-1.7888f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.4484073541,"pz":-0.4676618737,"ry":0,"rx":-6.3888888889},"hitbox_body_1":{"px":0,"py":0.4027436063,"pz":1.2724367812,"ry":0,"rx":15.6481481481},"pos_head":{"px":0,"py":0.8324611685,"pz":3.32382476,"ry":0,"rx":19.3577649776},"hitbox_head_0":{"px":0,"py":0.2529364096,"pz":3.1202219204,"ry":0,"rx":19.3577649776},"hitbox_tail_0":{"px":0,"py":1.0015594175,"pz":-2.2825070548,"ry":0,"rx":19.8148148148},"hitbox_tail_1":{"px":0,"py":1.645916424,"pz":-3.3837800612,"ry":0,"rx":37.8703703704},"shadow":{"px":0,"py":-0.0140625,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args