# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7325f,0.4883f,0.8414f,0f,0.4883f,-1.7325f,3.3112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7167f,0.5413f,0.9678f,0f,0.5413f,-1.7167f,2.9581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.4473f,1.0702f,1.1314f,0f,1.0702f,-1.4473f,2.6625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.4333f,1.0888f,1.0514f,0f,1.0888f,-1.4333f,2.2528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.4456f,1.0726f,1.2753f,0f,1.0726f,-1.4456f,2.0337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7726f,0.2952f,0.1044f,0.4128f,-0.0193f,0.4964f,-1.7301f,0.5213f,-0.3125f,-1.7048f,-0.4856f,1.7321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7726f,-0.0501f,0.3091f,0.4893f,-0.0193f,1.7909f,0.1797f,0.8289f,-0.3125f,0.1737f,-1.7641f,1.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7726f,-0.0615f,0.307f,0.4078f,-0.0193f,1.783f,0.2461f,1.2848f,-0.3125f,0.2391f,-1.7565f,1.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7991f,-0.0522f,0.026f,-0.4009f,-0.0505f,0.9904f,-1.5022f,0.5895f,0.0293f,-1.5021f,-0.9914f,1.585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7991f,-0.045f,-0.0372f,-0.42f,-0.0505f,1.7746f,0.2972f,0.9254f,0.0293f,0.2981f,-1.7749f,1.1631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7695f,0.0661f,0.3233f,-0.4078f,0.1937f,1.6357f,0.7259f,1.2848f,-0.2671f,0.7484f,-1.6151f,1.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7325f,0.4883f,1.4924f,0f,0.4883f,-1.7325f,1.043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7997f,0.0349f,0.7887f,0f,0.0349f,-1.7997f,-0.0823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4473f,1.0702f,0.8468f,0f,1.0702f,-1.4473f,0.5335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.1346f,-1.3974f,1.3781f,0f,-1.3974f,-1.1346f,0.1129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7592f,0.3811f,0.8464f,0f,0.3811f,-1.7592f,-0.5153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.0205f,1.4828f,0.7011f,0f,1.4828f,-1.0205f,0.0859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7711f,-0.3212f,1.3781f,0f,-0.3212f,-1.7711f,0.1129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7756f,0.2954f,1.4097f,0f,0.2954f,-1.7756f,-2.5923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7991f,0.0582f,1.377f,0f,0.0582f,-1.7991f,-1.5803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,-0.1569f,1.4446f,0f,-0.1569f,-1.7932f,-0.4852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,-0.0116f,1.4098f,0f,-0.0116f,-1.8f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.5965578326,"pz":-0.5572593966,"ry":0,"rx":-0.3703703704},"hitbox_body_1":{"px":0,"py":0.3876569579,"pz":1.2838065539,"ry":0,"rx":15.7407407407},"pos_head":{"px":0,"py":0.8511651966,"pz":3.3374648405,"ry":0,"rx":17.5},"hitbox_head_0":{"px":0,"py":0.2653445596,"pz":3.1527563032,"ry":0,"rx":17.5},"hitbox_tail_0":{"px":0,"py":0.871240921,"pz":-2.1526587931,"ry":0,"rx":1.8518518519},"hitbox_tail_1":{"px":0,"py":1.0024737369,"pz":-3.337409659,"ry":0,"rx":9.4444444444},"shadow":{"px":0,"py":0.05625,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args