# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7686f,0.3349f,1.2107f,0f,0.3349f,-1.7686f,3.3843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.762f,0.3681f,1.3014f,0f,0.3681f,-1.762f,3.0204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6353f,0.7521f,1.4012f,0f,0.7521f,-1.6353f,2.6977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6039f,0.8171f,1.2497f,0f,0.8171f,-1.6039f,2.3087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.6075f,0.81f,1.4329f,0f,0.81f,-1.6075f,2.0546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7897f,0.1551f,0.1137f,0.428f,-0.0318f,0.8109f,-1.6067f,0.6872f,-0.1897f,-1.5995f,-0.8035f,1.7685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7897f,-0.0307f,0.1899f,0.4761f,-0.0318f,1.7997f,-0.0093f,0.9466f,-0.1897f,-0.0127f,-1.7899f,1.2977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7897f,-0.0636f,0.1815f,0.4078f,-0.0318f,1.7733f,0.3072f,1.3928f,-0.1897f,0.3023f,-1.7643f,1.5736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7996f,-0.0347f,0.0173f,-0.4132f,-0.0349f,1.103f,-1.422f,0.7258f,0.0168f,-1.422f,-1.1034f,1.6748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7996f,-0.0342f,-0.0182f,-0.4257f,-0.0349f,1.7983f,0.0698f,1.0056f,0.0168f,0.0701f,-1.7986f,1.2136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7885f,0.035f,0.1997f,-0.4078f,0.1019f,1.6879f,0.617f,1.3928f,-0.1753f,0.6244f,-1.6791f,1.5736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7735f,0.3079f,1.5472f,0f,0.3079f,-1.7735f,1.0468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7992f,0.0533f,0.7868f,0f,0.0533f,-1.7992f,-0.1987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.524f,0.9578f,0.8912f,0f,0.9578f,-1.524f,0.4109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.4021f,-1.1287f,1.4988f,0f,-1.1287f,-1.4021f,0.111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7777f,0.2823f,0.8461f,0f,0.2823f,-1.7777f,-0.4962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.2911f,1.2542f,0.8213f,0f,1.2542f,-1.2911f,0.1218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7504f,-0.4195f,1.4988f,0f,-0.4195f,-1.7504f,0.111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7973f,-0.0985f,1.4875f,0f,-0.0985f,-1.7973f,-2.5872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7958f,-0.1226f,1.5564f,0f,-0.1226f,-1.7958f,-1.577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7953f,-0.1295f,1.6073f,0f,-0.1295f,-1.7953f,-0.481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7963f,0.1154f,1.5223f,0f,0.1154f,-1.7963f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7664906305,"pz":-0.6126923506,"ry":0,"rx":3.6762688615},"hitbox_body_1":{"px":0,"py":0.4729863868,"pz":1.3997339973,"ry":0,"rx":9.8491083676},"pos_head":{"px":0,"py":1.2230090461,"pz":3.4095023007,"ry":0,"rx":11.8004115226},"hitbox_head_0":{"px":0,"py":0.6217406547,"pz":3.2838862823,"ry":0,"rx":11.8004115226},"hitbox_tail_0":{"px":0,"py":0.9958296304,"pz":-2.0957073481,"ry":0,"rx":-3.9060356653},"hitbox_tail_1":{"px":0,"py":0.9277040227,"pz":-3.225656041,"ry":0,"rx":-3.1378600823},"shadow":{"px":0,"py":0.16875,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args