# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7387f,-0.4659f,3.8631f,0f,-0.4659f,-1.7387f,2.8702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7387f,-0.4659f,3.78f,0f,-0.4659f,-1.7387f,2.5045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,-0.3896f,3.6644f,0f,-0.3896f,-1.7573f,2.1872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7167f,-0.5413f,3.2837f,0f,-0.5413f,-1.7167f,2.0158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5966f,-0.8311f,3.1845f,0f,-0.8311f,-1.5966f,1.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7167f,-0.5086f,0.1851f,0.6623f,0.1628f,-1.0722f,-1.4366f,2.4814f,0.5162f,-1.3534f,1.0686f,2.2721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7167f,-0.1851f,-0.5086f,0.5047f,0.1628f,1.4366f,-1.0722f,2.409f,0.5162f,-1.0686f,-1.3534f,1.7611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7167f,-0.3991f,-0.3657f,0.4078f,0.1628f,0.7792f,-1.6144f,2.8036f,0.5162f,-1.5728f,-0.707f,1.4223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7387f,0.3816f,-0.2672f,-0.5814f,-0.1401f,-1.4129f,-1.1063f,3.0037f,-0.4443f,-1.0479f,1.3945f,1.9244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7387f,0.4659f,0f,-0.5163f,-0.1401f,-0.5228f,-1.7167f,2.4774f,-0.4443f,-1.6582f,0.5413f,1.8244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.3929f,0.2503f,-0.4078f,-0.1401f,0.4814f,-1.7288f,2.8036f,-0.4443f,-1.6893f,-0.4344f,1.4223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.428f,-1.0958f,2.5208f,0f,-1.0958f,-1.428f,0.9518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.663f,0.6888f,1.032f,0f,0.6888f,-1.663f,-0.5089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7932f,0.1569f,1.4031f,0f,0.1569f,-1.7932f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.8f,0f,2.0645f,0f,0f,-1.8f,0.1333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7387f,0.4659f,1.4527f,0f,0.4659f,-1.7387f,0.0333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5966f,0.8311f,1.6062f,0f,0.8311f,-1.5966f,0.6324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.9f,-1.5588f,2.0645f,0f,-1.5588f,-0.9f,0.1333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,-0.2349f,0.7878f,0f,-0.2349f,-1.7846f,-2.2312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5966f,-0.8311f,1.2553f,0f,-0.8311f,-1.5966f,-1.3331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.428f,-1.0958f,1.9007f,0f,-1.0958f,-1.428f,-0.4457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.663f,-0.6888f,2.1372f,0f,-0.6888f,-1.663f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0880617547,"pz":-0.1930653573,"ry":0,"rx":-22.5},"hitbox_body_1":{"px":0,"py":2.0525394179,"pz":1.9810309885,"ry":0,"rx":-37.5},"pos_head":{"px":0,"py":3.8854746968,"pz":2.8871824625,"ry":0,"rx":-15},"hitbox_head_0":{"px":0,"py":3.292154758,"pz":3.0461620609,"ry":0,"rx":-15},"hitbox_tail_0":{"px":0,"py":0.5339737742,"pz":-1.5840286175,"ry":0,"rx":-27.5},"hitbox_tail_1":{"px":0,"py":0.1811012067,"pz":-2.8252462879,"ry":0,"rx":-7.5},"shadow":{"px":0,"py":0.7836048736,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args