# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:dino_aj/animations/state_paralysis/zzz/apply_frame {frame: 2}
scoreboard players add @s aj.state_paralysis.frame 1