# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args merge from entity @s data.locators.body_0
function animated_java:ranposu_aj/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.body_1
function animated_java:ranposu_aj/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.head_0
function animated_java:ranposu_aj/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.tail_0
function animated_java:ranposu_aj/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.tail_1
function animated_java:ranposu_aj/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.shadow
function animated_java:ranposu_aj/zzz/at_all_locators/execute_at_transform with storage aj:temp args