# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.7399f,0.3938f,0.24f,0.033f,0.4254f,1.009f,1.4286f,2.1175f,0.178f,1.4377f,-1.0684f,2.8588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.7399f,0.4397f,-0.139f,0.0077f,0.4254f,1.7398f,0.1788f,2.1686f,0.178f,0.14f,-1.7857f,2.4882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.7932f,0.1555f,-0.0205f,0f,0.1293f,1.5987f,0.817f,2.2813f,0.0888f,0.8124f,-1.6038f,2.1698f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.3896f,1.1441f,2.2175f,0f,1.1441f,-1.3896f,1.7573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7959f,-0.1214f,2.2457f,0f,-0.1214f,-1.7959f,1.4453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9081f,-1.5541f,1.4852f,0f,-1.5541f,-0.9081f,1.0585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4388f,0f,1.7987f,-0.0691f,1.7287f,0f,-0.0691f,-1.7987f,0.577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.4223f,1.1032f,1.9913f,0f,1.1032f,-1.4223f,1.0352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.4338f,-1.0883f,1.5004f,0f,-1.0883f,-1.4338f,1.2269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6946f,-0.6068f,1.5878f,0f,-0.6068f,-1.6946f,0.6944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7138f,0.5503f,1.9913f,0f,0.5503f,-1.7138f,1.0352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7195f,-0.5323f,1.8892f,0f,-0.5323f,-1.7195f,0.4958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.7996f,0.0362f,0.0009f,0.4168f,0.036f,1.7791f,0.2711f,0.9035f,0.0046f,0.271f,-1.7795f,-0.846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5213f,0.9621f,1.0062f,0f,0.9621f,-1.5213f,-0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5939f,-0.8364f,1.6603f,0f,-0.8364f,-1.5939f,-0.4129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7932f,-0.1569f,0.7991f,0f,-0.1569f,-1.7932f,-0.4934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.781f,0.2609f,1.1408f,0f,0.2609f,-1.781f,0.0221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.0958f,-1.428f,1.6603f,0f,-1.428f,-1.0958f,-0.4129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.6056f,0.1907f,-0.7909f,-0.3573f,-0.0308f,1.7344f,0.4806f,1.317f,0.813f,0.4423f,-1.5438f,-3.0574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7388f,0.0137f,-0.4653f,-0.0956f,0.074f,1.7845f,-0.224f,1.443f,0.4596f,-0.2355f,-1.7243f,-2.0875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7932f,0f,-0.1569f,0f,0.034f,1.7573f,-0.3881f,1.652f,0.1532f,-0.3896f,-1.7506f,-1.0146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,-0.2349f,1.7061f,0f,-0.2349f,-1.7846f,-0.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.8016501413,"pz":-0.9808765693,"ry":0,"rx":-7.5},"hitbox_body_1":{"px":0,"py":1.0930021524,"pz":1.2986510317,"ry":0,"rx":-17.2},"pos_head":{"px":0.0389632144,"py":2.1319212847,"pz":2.882139533,"ry":355.5502259909,"rx":5.7018526865},"hitbox_head_0":{"px":-0.1110868906,"py":1.5382001275,"pz":2.8343565238,"ry":355.5502259909,"rx":5.7018526865},"hitbox_tail_0":{"px":-0.2432171849,"py":0.8543875718,"pz":-2.5512547276,"ry":344.8991901226,"rx":-7.1495448352},"hitbox_tail_1":{"px":-0.7064237987,"py":0.9905358376,"pz":-3.7592659597,"ry":332.8739320416,"rx":15.4873127706},"shadow":{"px":0,"py":0.3525,"pz":-0.755625,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args