# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dino_aj.root] run return 0
execute on passengers if entity @s[tag=aj.dino_aj.data] unless data entity @s {data:{rigHash: '8bb65354611d9009d14caf398ff4cff209afc0e901c4e8b6b944f01fa8bc94c9'}} on vehicle run function animated_java:dino_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1