# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java_karakuri:karakuri/zzz/reset_floating_entities
function animated_java_karakuri:karakuri/zzz/apply_default_pose_to_nodes with storage animated_java:temp entry.data.uuids_by_name