# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.5 ^0.87721875 ~0 ~0
data modify entity @s data.locators.hitbox_neck_0 merge value { px: 0, py: 0.5, pz: 0.87721875, ry: 0, rx: 0 }