# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.28125 ^0.109375 ^-0.0387125 ~0 ~0
data modify entity @s data.locators.hitbox_leg_right_1 merge value { px: -0.28125, py: 0.109375, pz: -0.0387125, ry: 0, rx: 0 }