# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.421875 ^0.4925375 ~0 ~0
data modify entity @s data.locators.hitbox_body_0 merge value { px: 0, py: 0.421875, pz: 0.4925375, ry: 0, rx: 0 }