# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.484375 ^1.3206625 ~0 ~0
data modify entity @s data.locators.hitbox_head_0 merge value { px: 0, py: 0.484375, pz: 1.3206625, ry: 0, rx: 0 }