# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:nikuyaki/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'c389073e91975edaf9b6d1a5397e5449d4780a5bd2c18f83ffa065e11893f90a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack