# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/0 with entity @s data.locators.hitbox_body_1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/1 with entity @s data.locators.hitbox_body_0
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/2 with entity @s data.locators.hitbox_neck_0
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/3 with entity @s data.locators.hitbox_head_0
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/4 with entity @s data.locators.hitbox_leg_right_0
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/5 with entity @s data.locators.hitbox_leg_right_1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/6 with entity @s data.locators.hitbox_leg_left_0
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/7 with entity @s data.locators.hitbox_leg_left_1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/8 with entity @s data.locators.hitbox_tail_0
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/9 with entity @s data.locators.hitbox_tail_1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/10 with entity @s data.locators.hitbox_tail_2
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:karakuri_aj/zzz/summon/locators_on_summon/zzz/11 with entity @s data.locators.shadow
data modify entity @s data.uuids append from storage animated_java:temp uuids