# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_4) {transformation: [-2.6633f,12.3223f,-4.0943f,0.9935f,12.4254f,3.632f,2.8483f,0.9483f,3.7697f,-3.2658f,-12.2808f,-9.0336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_3) {transformation: [-1.9306f,9.1917f,-3.4185f,1.4832f,9.6673f,2.3692f,0.9107f,0.7707f,1.6478f,-3.1305f,-9.348f,-7.4179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-3.8076f,8.5395f,-0.7509f,1.622f,8.2118f,3.3976f,-3.001f,1.3355f,-2.4601f,-1.8756f,-8.8552f,-5.774f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_tail_2":{"px":1.4094,"py":0.8769,"pz":-6.9493,"ry":355.1528,"rx":-18.6593},"pos_tail_3":{"px":0.9524,"py":0.899,"pz":-8.7924,"ry":339.9131,"rx":5.2279},"hitbox_tail_3":{"px":0.8487,"py":-0.182,"pz":-9.1333,"ry":180,"rx":0},"pos_tail_4":{"px":0.5123,"py":1.463,"pz":-11.0699,"ry":341.5621,"rx":12.4087},"hitbox_tail_4":{"px":0.1298,"py":0.384,"pz":-11.341,"ry":180,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args