# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_4) {transformation: [-2.8725f,12.3331f,-3.9164f,1.0316f,12.7851f,3.324f,1.0902f,0.7027f,1.9965f,-3.5413f,-12.6162f,-9.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_3) {transformation: [-1.9808f,9.212f,-3.3341f,1.5068f,9.7793f,2.0623f,-0.1118f,0.7014f,0.5849f,-3.2844f,-9.4218f,-7.3942f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_tail_3":{"px":0.9884,"py":0.6793,"pz":-8.7793,"ry":340.5124,"rx":-0.6411},"hitbox_tail_3":{"px":0.8893,"py":-0.4659,"pz":-9.1431,"ry":180,"rx":0},"pos_tail_4":{"px":0.5793,"py":0.9282,"pz":-11.1186,"ry":342.7541,"rx":4.7179},"hitbox_tail_4":{"px":0.2028,"py":-0.227,"pz":-11.4228,"ry":180,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args