# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_4) {transformation: [-2.8905f,12.3311f,-3.9096f,1.0296f,12.8257f,3.2538f,0.7804f,0.6769f,1.6857f,-3.6128f,-12.6412f,-9.0232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_3) {transformation: [-1.9693f,9.2103f,-3.3455f,1.5068f,9.7897f,1.9987f,-0.2601f,0.7014f,0.4293f,-3.328f,-9.4149f,-7.3942f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_tail_3":{"px":0.9867716731,"py":0.6575233066,"pz":-8.7781185233,"ry":340.4379851939,"rx":-1.4914333399},"hitbox_tail_3":{"px":0.8870665663,"py":-0.4975567874,"pz":-9.1448751225,"ry":180,"rx":0},"pos_tail_4":{"px":0.578457774,"py":0.8511900522,"pz":-11.1229949322,"ry":342.814413378,"rx":3.3751707977},"hitbox_tail_4":{"px":0.2021110454,"py":-0.3176442941,"pz":-11.4313790969,"ry":180,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args