# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(tail_4) {transformation: [-2.9429f,12.328f,-3.8801f,1.0275f,12.8581f,3.1948f,0.398f,0.6571f,1.3054f,-3.6755f,-12.6681f,-9.0222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_tail_4":{"px":0.581,"py":0.7686,"pz":-11.1272,"ry":342.971,"rx":1.7208},"hitbox_tail_4":{"px":0.2055,"py":-0.4173,"pz":-11.4406,"ry":180,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args