# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java_karakuri:karakuri rig_hash set value '85f218abbffc60ee125291456ae5eb1da16baa532ce53561d210cf4e422b2d8b'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.damage_counter.frame dummy
scoreboard objectives add aj.bite.frame dummy