# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,0.328f,1.7699f,7.2177f,0f,1.7699f,-0.328f,3.2161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.6379f,0.7464f,7.3862f,0f,0.7464f,-1.6379f,2.8811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7639f,0.3589f,7.4096f,0f,0.3589f,-1.7639f,2.5441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7945f,0.1412f,7.1209f,0f,0.1412f,-1.7945f,2.2427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7539f,-0.4049f,7.0992f,0f,-0.4049f,-1.7539f,1.9301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7167f,-0.5086f,0.1851f,0.6602f,0.0189f,-0.6716f,-1.6699f,6.4792f,0.5409f,-1.5907f,0.6458f,2.2616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7167f,-0.3622f,-0.4022f,0.5047f,0.0189f,1.2968f,-1.2482f,6.3406f,0.5409f,-1.1947f,-1.2329f,1.7638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7167f,-0.3991f,-0.3657f,0.4078f,0.0189f,1.1711f,-1.3668f,6.8114f,0.5409f,-1.3073f,-1.1128f,1.5427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7387f,0.3862f,-0.2605f,-0.5854f,-0.0163f,-1.0562f,-1.4574f,6.8713f,-0.4656f,-1.4054f,1.0237f,2.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7387f,0.4658f,0.0081f,-0.5183f,-0.0163f,-0.0293f,-1.7997f,6.3952f,-0.4656f,-1.7384f,0.0325f,1.8501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.3972f,0.2434f,-0.4078f,-0.0163f,0.8882f,-1.5655f,6.8114f,-0.4656f,-1.5144f,-0.8543f,1.5427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6689f,-0.6743f,6.6645f,0f,-0.6743f,-1.6689f,1.0137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7989f,0.0628f,5.3606f,0f,0.0628f,-1.7989f,-0.1621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7945f,0.1412f,5.7359f,0f,0.1412f,-1.7945f,0.3294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5509f,-0.9136f,6.3806f,0f,-0.9136f,-1.5509f,0.1207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.707f,-0.5711f,5.4949f,0f,-0.5711f,-1.707f,0.232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7901f,-0.1882f,5.9536f,0f,-0.1882f,-1.7901f,0.6469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.8032f,-1.6109f,6.3806f,0f,-1.6109f,-0.8032f,0.1207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5893f,-0.845f,5.1465f,0f,-0.845f,-1.5893f,-2.2214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5096f,-0.9804f,5.6979f,0f,-0.9804f,-1.5096f,-1.3723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.4375f,-1.0833f,6.3356f,0f,-1.0833f,-1.4375f,-0.4794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7669f,-0.3435f,6.433f,0f,-0.3435f,-1.7669f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":5.4888485647,"pz":-0.3937735243,"ry":0,"rx":-11},"hitbox_body_1":{"px":0,"py":5.9382943773,"pz":1.8804149887,"ry":0,"rx":-22},"pos_head":{"px":0,"py":7.2241520671,"pz":3.2433936482,"ry":0,"rx":24.5},"hitbox_head_0":{"px":0,"py":6.6652083564,"pz":2.9886683239,"ry":0,"rx":24.5},"hitbox_tail_0":{"px":0,"py":4.9558592857,"pz":-1.5529462364,"ry":0,"rx":-33},"hitbox_tail_1":{"px":0,"py":4.3701656761,"pz":-2.5654208661,"ry":0,"rx":-28},"shadow":{"px":0,"py":5.0794097623,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args