# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.2758f,1.2698f,1.9845f,0f,1.2698f,-1.2758f,3.2934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.4858f,1.016f,2.2079f,0f,1.016f,-1.4858f,2.9922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6397f,0.7425f,2.3057f,0f,0.7425f,-1.6397f,2.6689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7437f,0.4465f,2.0729f,0f,0.4465f,-1.7437f,2.3225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7985f,0.0728f,2.1346f,0f,0.0728f,-1.7985f,2.0153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7779f,0.0549f,0.2757f,0.4349f,-0.1836f,1.1101f,-1.405f,1.3202f,-0.2129f,-1.4158f,-1.0909f,2.1268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7779f,-0.1131f,0.2573f,0.4887f,-0.1836f,1.7152f,-0.5141f,1.4352f,-0.2129f,-0.5341f,-1.7057f,1.6023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7779f,-0.0739f,0.2712f,0.4078f,-0.1836f,1.6204f,-0.762f,1.9568f,-0.2129f,-0.7803f,-1.608f,1.5666f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7908f,0.1452f,-0.1094f,-0.4925f,0.1799f,1.2604f,-1.2724f,1.3001f,-0.026f,-1.2769f,-1.2684f,2.1011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7908f,0.1806f,-0.0207f,-0.4745f,0.1799f,1.7314f,-0.4581f,1.4321f,-0.026f,-0.4578f,-1.7406f,1.5782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.2868f,0.3671f,-0.4078f,0.1048f,1.6229f,-0.7716f,1.9568f,-0.4539f,-0.7239f,-1.5843f,1.5666f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7866f,-0.2194f,1.9519f,0f,-0.2194f,-1.7866f,1.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7883f,-0.2052f,1.1698f,0f,-0.2052f,-1.7883f,0.1251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6426f,0.736f,1.3582f,0f,0.736f,-1.6426f,0.7142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.5003f,-1.7291f,1.6836f,0f,-1.7291f,-0.5003f,0.1198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7778f,0.2816f,1.174f,0f,0.2816f,-1.7778f,-0.5179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,0.9671f,1.5181f,1.0073f,0f,1.5181f,-0.9671f,0.0777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7778f,-0.2816f,1.6836f,0f,-0.2816f,-1.7778f,0.1198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.6109f,0.8032f,1.9709f,0f,0.8032f,-1.6109f,-2.5411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7119f,0.5562f,1.658f,0f,0.5562f,-1.7119f,-1.5782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7997f,-0.0314f,1.6491f,0f,-0.0314f,-1.7997f,-0.481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,-0.3126f,1.7341f,0f,-0.3126f,-1.7727f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.8009426754,"pz":-0.4101561215,"ry":0,"rx":-10},"hitbox_body_1":{"px":0,"py":1.0260809689,"pz":1.6668432086,"ry":0,"rx":-7},"pos_head":{"px":0,"py":1.9861697435,"pz":3.3214360655,"ry":0,"rx":34.3636363636},"hitbox_head_0":{"px":0,"py":1.4791236308,"pz":2.9747268183,"ry":0,"rx":34.3636363636},"hitbox_tail_0":{"px":0,"py":1.3314192219,"pz":-2.268546709,"ry":0,"rx":18},"hitbox_tail_1":{"px":0,"py":1.8001304922,"pz":-3.3728642891,"ry":0,"rx":26.5},"shadow":{"px":0,"py":0.3805109244,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args