# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=animated_java_karakuri.karakuri.animation.idle.playing] run function animated_java_karakuri:karakuri/animations/idle/zzz/on_tick
execute if entity @s[tag=animated_java_karakuri.karakuri.animation.damage_counter.playing] run function animated_java_karakuri:karakuri/animations/damage_counter/zzz/on_tick
execute if entity @s[tag=animated_java_karakuri.karakuri.animation.bite.playing] run function animated_java_karakuri:karakuri/animations/bite/zzz/on_tick
function animated_java_karakuri:karakuri/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~