# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.6296f,0.7645f,2.2631f,0f,0.7645f,-1.6296f,3.5852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.6674f,0.6781f,2.4176f,0f,0.6781f,-1.6674f,3.2435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,-0.0117f,2.3712f,0f,-0.0117f,-1.8f,2.9089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7941f,0.1452f,2.0831f,0f,0.1452f,-1.7941f,2.6069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7997f,-0.0301f,2.1272f,0f,-0.0301f,-1.7997f,2.2967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7999f,-0.0164f,0.0057f,0.4381f,-0.0155f,1.785f,0.2311f,1.0787f,-0.0077f,0.231f,-1.7851f,1.8592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7999f,-0.0173f,0.0013f,0.4387f,-0.0155f,1.6664f,0.6804f,1.4994f,-0.0077f,0.6803f,-1.6665f,1.5213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.6937f,0.6095f,1.8908f,0f,0.6095f,-1.6937f,1.8759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7943f,0.0018f,0.1431f,-0.4377f,-0.0287f,1.7587f,-0.3822f,1.2649f,-0.1402f,-0.3833f,-1.7531f,2.0257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7943f,-0.0169f,0.1421f,-0.4057f,-0.0287f,1.7936f,-0.1494f,1.4865f,-0.1402f,-0.1512f,-1.7882f,1.5347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7943f,-0.0699f,0.1248f,-0.4078f,-0.0287f,1.7142f,0.5483f,1.8908f,-0.1402f,0.5446f,-1.7099f,1.8759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.741f,-0.457f,1.8123f,0f,-0.457f,-1.741f,1.3326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7962f,0.1167f,0.8531f,0f,0.1167f,-1.7962f,-0.1593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5607f,0.8968f,0.9815f,0f,0.8968f,-1.5607f,0.4457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.7326f,-0.4878f,1.6581f,0f,-0.4878f,-1.7326f,0.4083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.7996f,0.0223f,-0.0313f,-0.4289f,0.0236f,1.7983f,-0.0749f,0.8382f,0.0303f,-0.0753f,-1.7982f,-0.2776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.7996f,0.035f,-0.0157f,-0.4219f,0.0236f,1.5883f,0.8465f,0.9859f,0.0303f,0.8461f,-1.5884f,0.323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7922f,-0.1673f,1.6581f,0f,-0.1673f,-1.7922f,0.4083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.3789f,1.157f,2.0193f,0f,1.157f,-1.3789f,-2.2519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7113f,0.5581f,1.7054f,0f,0.5581f,-1.7113f,-1.2893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7997f,-0.0353f,1.6988f,0f,-0.0353f,-1.7997f,-0.1921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7978f,-0.089f,1.6947f,0f,-0.089f,-1.7978f,0.5218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.8484755987,"pz":-0.227679279,"ry":0,"rx":-2.8333333333},"hitbox_body_1":{"px":0,"py":0.9819315509,"pz":2.1000618212,"ry":0,"rx":-14.7083333333},"pos_head":{"px":0,"py":2.2706962108,"pz":3.612251051,"ry":0,"rx":22.1316666667},"hitbox_head_0":{"px":0,"py":1.7017038099,"pz":3.380840787,"ry":0,"rx":22.1316666667},"hitbox_tail_0":{"px":0,"py":1.3795081765,"pz":-1.98007808,"ry":0,"rx":18.0616666667},"hitbox_tail_1":{"px":0,"py":2.0473785567,"pz":-3.100593837,"ry":0,"rx":39.9983333333},"shadow":{"px":0,"py":0.34115625,"pz":0.06890625,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args