# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7498f,0.4221f,2.1954f,0f,0.4221f,-1.7498f,3.5717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7498f,0.4221f,2.2973f,0f,0.4221f,-1.7498f,3.2108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7871f,-0.215f,2.2134f,0f,-0.215f,-1.7871f,2.8836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7973f,0.0986f,1.9176f,0f,0.0986f,-1.7973f,2.5891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7997f,0.0334f,1.9725f,0f,0.0334f,-1.7997f,2.2807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7999f,-0.0114f,0.0089f,0.4367f,-0.0125f,1.784f,-0.239f,1.0801f,-0.0073f,-0.2391f,-1.784f,1.8675f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7999f,-0.0136f,0.0048f,0.4387f,-0.0125f,1.7677f,0.3394f,1.4262f,-0.0073f,0.3394f,-1.7677f,1.4534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.6515f,0.7159f,1.7943f,0f,0.7159f,-1.6515f,1.8322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7962f,0.0529f,0.1045f,-0.4443f,-0.008f,1.5467f,-0.9206f,1.3143f,-0.1168f,-0.9192f,-1.5432f,1.9926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7962f,0.029f,0.1134f,-0.4131f,-0.008f,1.7093f,-0.564f,1.415f,-0.1168f,-0.5634f,-1.7056f,1.4634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7962f,-0.0507f,0.1056f,-0.4078f,-0.008f,1.672f,0.6667f,1.7943f,-0.1168f,0.6648f,-1.6687f,1.8322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7863f,-0.2213f,1.7887f,0f,-0.2213f,-1.7863f,1.2833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7967f,0.1098f,0.8585f,0f,0.1098f,-1.7967f,-0.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5744f,0.8725f,0.9963f,0f,0.8725f,-1.5744f,0.4f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.7259f,-0.5113f,1.6723f,0f,-0.5113f,-1.7259f,0.3535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.7997f,0.0198f,-0.0244f,-0.4265f,0.0204f,1.7993f,-0.0471f,0.8433f,0.0239f,-0.0474f,-1.7992f,-0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.7997f,0.0291f,-0.0118f,-0.4219f,0.0204f,1.5965f,0.831f,0.9969f,0.0239f,0.8308f,-1.5966f,0.2995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7825f,-0.2505f,1.6723f,0f,-0.2505f,-1.7825f,0.3535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5798f,0.8626f,1.9584f,0f,0.8626f,-1.5798f,-2.3305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,0.3897f,1.7392f,0f,0.3897f,-1.7573f,-1.342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7995f,-0.0432f,1.7374f,0f,-0.0432f,-1.7995f,-0.2448f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7999f,-0.0157f,1.7043f,0f,-0.0157f,-1.7999f,0.4683f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.8892523415,"pz":-0.3149486735,"ry":0,"rx":-0.5},"hitbox_body_1":{"px":0,"py":0.8636555166,"pz":1.9334370327,"ry":0,"rx":-7.0625},"pos_head":{"px":0,"py":2.2069850662,"pz":3.5973183387,"ry":0,"rx":13.5625},"hitbox_head_0":{"px":0,"py":1.6098636163,"pz":3.4532730799,"ry":0,"rx":13.5625},"hitbox_tail_0":{"px":0,"py":1.3479907747,"pz":-1.9979765791,"ry":0,"rx":12.505},"hitbox_tail_1":{"px":0,"py":1.8187695133,"pz":-3.1680633912,"ry":0,"rx":28.635},"shadow":{"px":0,"py":0.35071875,"pz":0.01546875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args