# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7941f,0.1455f,2.0915f,0f,0.1455f,-1.7941f,3.5109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7941f,0.1455f,2.1362f,0f,0.1455f,-1.7941f,3.1386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7686f,-0.335f,2.0304f,0f,-0.335f,-1.7686f,2.8178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7978f,0.0894f,1.733f,0f,0.0894f,-1.7978f,2.5248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7955f,0.1278f,1.8041f,0f,0.1278f,-1.7955f,2.2197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,-0.0053f,0.0084f,0.4357f,-0.0084f,1.6201f,-0.7843f,1.0823f,-0.0052f,-0.7844f,-1.6201f,1.843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,-0.0083f,0.0055f,0.4387f,-0.0084f,1.7991f,-0.0576f,1.3288f,-0.0052f,-0.0576f,-1.7991f,1.363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.6314f,0.7607f,1.6864f,0f,0.7607f,-1.6314f,1.7516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7983f,0.0618f,0.0478f,-0.4438f,0.005f,1.1894f,-1.351f,1.3177f,-0.0779f,-1.3496f,-1.1885f,1.9084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7983f,0.0417f,0.066f,-0.4232f,0.005f,1.5798f,-0.8628f,1.3212f,-0.0779f,-0.8618f,-1.5784f,1.3691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7983f,-0.027f,0.0733f,-0.4078f,0.005f,1.6462f,0.7281f,1.6864f,-0.0779f,0.7276f,-1.6445f,1.7516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7999f,0.0157f,1.7532f,0f,0.0157f,-1.7999f,1.2067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7973f,0.0993f,0.8671f,0f,0.0993f,-1.7973f,-0.2677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5942f,0.8357f,1.0188f,0f,0.8357f,-1.5942f,0.3318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.7151f,-0.5463f,1.6937f,0f,-0.5463f,-1.7151f,0.2716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.7999f,0.0146f,-0.015f,-0.4231f,0.0147f,1.7999f,-0.0053f,0.8539f,0.0149f,-0.0054f,-1.7999f,-0.3319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.7999f,0.0198f,-0.0068f,-0.4219f,0.0147f,1.6085f,0.8077f,1.0162f,0.0149f,0.8076f,-1.6086f,0.2649f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7607f,-0.3742f,1.6937f,0f,-0.3742f,-1.7607f,0.2716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7633f,0.3616f,1.8635f,0f,0.3616f,-1.7633f,-2.4286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7952f,0.1309f,1.7898f,0f,0.1309f,-1.7952f,-1.4188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7992f,-0.055f,1.7952f,0f,-0.055f,-1.7992f,-0.3216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7975f,0.0942f,1.7186f,0f,0.0942f,-1.7975f,0.3882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.9529347665,"pz":-0.4434004217,"ry":0,"rx":3},"hitbox_body_1":{"px":0,"py":0.7505698323,"pz":1.7295131278,"ry":0,"rx":0.5},"pos_head":{"px":0,"py":2.1068696443,"pz":3.5344130769,"ry":0,"rx":4.6371428571},"hitbox_head_0":{"px":0,"py":1.4946302818,"pz":3.4847539838,"ry":0,"rx":4.6371428571},"hitbox_tail_0":{"px":0,"py":1.307673153,"pz":-2.0111281629,"ry":0,"rx":4.17},"hitbox_tail_1":{"px":0,"py":1.484429176,"pz":-3.1884629778,"ry":0,"rx":11.59},"shadow":{"px":0,"py":0.3650625,"pz":-0.0646875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args