# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-97.5f,0f,0f,-1.3333f,0f,-97.5f,0f,90.4538f,0f,0f,97.5f,112.6923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-1.3333f,0f,0f,0.0001f,106.5788f,0f,-0.0001f,0f,112.5673f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-1.3333,"py":106.1413,"pz":113.3173,"ry":180,"rx":90},"beam_start":{"px":-1.3333,"py":106.5788,"pz":112.5673,"ry":180,"rx":90},"beam_end":{"px":-1.3333,"py":106.5788,"pz":112.5673,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args