# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-100f,0f,0f,-2.2599f,0f,-100f,0f,90.332f,0f,0f,100f,112.5394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-2.2599f,0f,0f,0.0001f,106.457f,0f,-0.0001f,0f,112.4144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-2.2599,"py":106.0195,"pz":113.1644,"ry":180,"rx":90},"beam_start":{"px":-2.2599,"py":106.457,"pz":112.4144,"ry":180,"rx":90},"beam_end":{"px":-2.2599,"py":106.457,"pz":112.4144,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args