# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-97.5f,0f,0f,-2.5104f,0f,-97.5f,0f,90.2991f,0f,0f,97.5f,112.498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-2.5104f,0f,0f,0.0001f,106.424f,0f,-0.0001f,0f,112.373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-2.5104,"py":105.9866,"pz":113.123,"ry":180,"rx":90},"beam_start":{"px":-2.5104,"py":106.4241,"pz":112.373,"ry":180,"rx":90},"beam_end":{"px":-2.5104,"py":106.424,"pz":112.373,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args