# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-95f,0f,0f,-0.6061f,0f,-95f,0f,90.5494f,0f,0f,95f,112.8123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-0.6061f,0f,0f,0.0001f,106.6744f,0f,-0.0001f,0f,112.6873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-0.6061,"py":106.2369,"pz":113.4373,"ry":180,"rx":90},"beam_start":{"px":-0.6061,"py":106.6744,"pz":112.6873,"ry":180,"rx":90},"beam_end":{"px":-0.6061,"py":106.6744,"pz":112.6873,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args