# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-100f,0f,0f,8.535f,0f,-100f,0f,140.3694f,0f,0f,100f,58.6303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,8.535f,0f,0f,0.0001f,156.4944f,0f,-0.0001f,0f,58.5053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":8.535,"py":156.0569,"pz":59.2553,"ry":180,"rx":90},"beam_start":{"px":8.535,"py":156.4944,"pz":58.5053,"ry":180,"rx":90},"beam_end":{"px":8.535,"py":156.4943,"pz":58.5053,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args