# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-95f,0f,0f,-10.1491f,0f,-95f,0f,130.9439f,0f,0f,95f,53.5922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-10.1491f,0f,0f,0.0001f,147.0689f,0f,-0.0001f,0f,53.4672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-10.1491,"py":146.6314,"pz":54.2172,"ry":180,"rx":90},"beam_start":{"px":-10.1491,"py":147.0689,"pz":53.4672,"ry":180,"rx":90},"beam_end":{"px":-10.1491,"py":147.0689,"pz":53.4672,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args