# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-97.5f,0f,0f,-27.9375f,0f,-97.5f,0f,94.8058f,0f,0f,97.5f,63.8834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-27.9375f,0f,0f,0.0001f,110.9308f,0f,-0.0001f,0f,63.7584f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-27.9375,"py":110.4933,"pz":64.5084,"ry":180,"rx":90},"beam_start":{"px":-27.9375,"py":110.9308,"pz":63.7584,"ry":180,"rx":90},"beam_end":{"px":-27.9375,"py":110.9308,"pz":63.7584,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args