# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-100f,0f,0f,-29.1285f,0f,-100f,0f,91.3052f,0f,0f,100f,66.8696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-29.1285f,0f,0f,0.0001f,107.4302f,0f,-0.0001f,0f,66.7446f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-29.1285,"py":106.9927,"pz":67.4946,"ry":180,"rx":90},"beam_start":{"px":-29.1285,"py":107.4302,"pz":66.7446,"ry":180,"rx":90},"beam_end":{"px":-29.1285,"py":107.4301,"pz":66.7446,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args