# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-100f,0f,0f,-28.2394f,0f,-100f,0f,84.7729f,0f,0f,100f,82.1305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-28.2394f,0f,0f,0.0001f,100.8978f,0f,-0.0001f,0f,82.0055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-28.2394,"py":100.4604,"pz":82.7555,"ry":180,"rx":90},"beam_start":{"px":-28.2394,"py":100.8979,"pz":82.0055,"ry":180,"rx":90},"beam_end":{"px":-28.2394,"py":100.8978,"pz":82.0055,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args