# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-95f,0f,0f,-22.5245f,0f,-95f,0f,85.257f,0f,0f,95f,89.6661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-22.5245f,0f,0f,0.0001f,101.3819f,0f,-0.0001f,0f,89.5411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-22.5245,"py":100.9445,"pz":90.2911,"ry":180,"rx":90},"beam_start":{"px":-22.5245,"py":101.382,"pz":89.5411,"ry":180,"rx":90},"beam_end":{"px":-22.5245,"py":101.3819,"pz":89.5411,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args