# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(comet_star) {transformation: [-97.1875f,0f,0f,-2.3737f,0f,-97.1875f,0f,90.0686f,0f,0f,97.1875f,110.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beam_model) {transformation: [0.0001f,0f,0f,-2.3737f,0f,0f,0.0001f,106.1936f,0f,-0.0001f,0f,110.3269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"pos_comet_star":{"px":-2.3737,"py":105.7561,"pz":111.0769,"ry":180,"rx":90},"beam_start":{"px":-2.3737,"py":106.1936,"pz":110.3269,"ry":180,"rx":90},"beam_end":{"px":-2.3737,"py":106.1936,"pz":110.3269,"ry":180,"rx":90}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args