# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7964f,0.1144f,2.7524f,0f,0.1144f,-1.7964f,2.7721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7924f,0.1652f,2.8012f,0f,0.1652f,-1.7924f,2.4002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2649f,-1.2807f,2.5318f,0f,-1.2807f,-1.2649f,2.1964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9577f,-1.5241f,2.1308f,0f,-1.5241f,-0.9577f,2.3123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5121f,-0.9765f,2.0043f,0f,-0.9765f,-1.5121f,2.0257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.498f,0.998f,1.2966f,0f,0.998f,-1.498f,1.9978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.6915f,-0.6156f,1.3812f,0f,-0.6156f,-1.6915f,1.4648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7563f,-0.3943f,1.9018f,0f,-0.3943f,-1.7563f,1.5541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.498f,0.998f,1.2966f,0f,0.998f,-1.498f,1.9978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6915f,-0.6156f,1.3812f,0f,-0.6156f,-1.6915f,1.4648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7563f,-0.3943f,1.9018f,0f,-0.3943f,-1.7563f,1.5541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7985f,0.0736f,1.986f,0f,0.0736f,-1.7985f,1.0116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7994f,0.0478f,0.8725f,0f,0.0478f,-1.7994f,-0.1006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7017f,0.5867f,1.1126f,0f,0.5867f,-1.7017f,0.4693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3062f,-1.2385f,1.694f,0f,-1.2385f,-1.3062f,0.1212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7994f,0.0478f,0.8725f,0f,0.0478f,-1.7994f,-0.1006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7017f,0.5867f,1.1126f,0f,0.5867f,-1.7017f,0.4693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3062f,-1.2385f,1.694f,0f,-1.2385f,-1.3062f,0.1212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7987f,0.0276f,-0.064f,-0.0675f,0.0293f,1.7991f,-0.0487f,0.8062f,0.0632f,-0.0497f,-1.7982f,-2.4126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7987f,0.004f,-0.0696f,-0.0283f,0.0293f,1.6739f,-0.6611f,1.1781f,0.0632f,-0.6618f,-1.6727f,-1.4717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7994f,0f,-0.0465f,0f,0.0208f,1.6099f,-0.8049f,1.6435f,0.0416f,-0.8052f,-1.6093f,-0.4784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7637f,-0.3596f,1.7473f,0f,-0.3596f,-1.7637f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7975527059,"pz":-0.3851279691,"ry":0,"rx":-11.523104},"hitbox_body_1":{"px":0,"py":0.9671118325,"pz":1.5018319928,"ry":0,"rx":2.344896},"pos_head":{"px":0,"py":2.7675341261,"pz":2.7957128315,"ry":0,"rx":5.264896},"hitbox_head_0":{"px":0,"py":2.1558755824,"pz":2.7393489388,"ry":0,"rx":5.264896},"hitbox_tail_0":{"px":-0.0509811421,"py":0.4867590733,"pz":-1.7954621444,"ry":357.6189666453,"rx":-21.5484992767},"hitbox_tail_1":{"px":-0.0992361884,"py":0.264448988,"pz":-3.0656550552,"ry":357.9623625304,"rx":-1.5512968882}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args