# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0787f,2.818f,0f,0.0787f,-1.7983f,2.7746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7982f,0.08f,2.849f,0f,0.08f,-1.7982f,2.4008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2745f,-1.2711f,2.5812f,0f,-1.2711f,-1.2745f,2.1949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9692f,-1.5168f,2.1794f,0f,-1.5168f,-0.9692f,2.3078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5194f,-0.9651f,2.055f,0f,-0.9651f,-1.5194f,2.0203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5921f,0.8398f,1.4168f,0f,0.8398f,-1.5921f,2.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.5653f,-0.8887f,1.4114f,0f,-0.8887f,-1.5653f,1.483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7403f,-0.4596f,1.9349f,0f,-0.4596f,-1.7403f,1.5528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.5921f,0.8398f,1.4168f,0f,0.8398f,-1.5921f,2.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.5653f,-0.8887f,1.4114f,0f,-0.8887f,-1.5653f,1.483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7403f,-0.4596f,1.9349f,0f,-0.4596f,-1.7403f,1.5528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0.0065f,1.9989f,0f,0.0065f,-1.8f,1.0076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0775f,0.8745f,0f,0.0775f,-1.7983f,-0.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6918f,0.6146f,1.1052f,0f,0.6146f,-1.6918f,0.4606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3264f,-1.2168f,1.6922f,0f,-1.2168f,-1.3264f,0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7983f,0.0775f,0.8745f,0f,0.0775f,-1.7983f,-0.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6918f,0.6146f,1.1052f,0f,0.6146f,-1.6918f,0.4606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3264f,-1.2168f,1.6922f,0f,-1.2168f,-1.3264f,0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7856f,-0.09f,0.2087f,0.2202f,-0.0989f,1.7959f,-0.0715f,0.7693f,-0.2046f,-0.0824f,-1.7864f,-2.3878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7856f,-0.0132f,0.2269f,0.0925f,-0.0989f,1.6631f,-0.6814f,1.1527f,-0.2046f,-0.6884f,-1.6505f,-1.4593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7936f,0f,0.1519f,0f,-0.07f,1.5971f,-0.8274f,1.6319f,-0.1347f,-0.8303f,-1.5914f,-0.4766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7576f,-0.3886f,1.7473f,0f,-0.3886f,-1.7576f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7876,"pz":-0.3694,"ry":0,"rx":-12.4666},"hitbox_body_1":{"px":0,"py":0.999,"pz":1.5355,"ry":0,"rx":0.2058},"pos_head":{"px":0,"py":2.8342,"pz":2.7974,"ry":0,"rx":2.5464},"hitbox_head_0":{"px":0,"py":2.2205,"pz":2.7702,"ry":0,"rx":2.5464},"hitbox_tail_0":{"px":0.1664,"py":0.4582,"pz":-1.7685,"ry":7.8269,"rx":-22.2455},"hitbox_tail_1":{"px":0.3238,"py":0.22,"pz":-3.0269,"ry":6.6625,"rx":-2.2775}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args