# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0793f,2.8233f,0f,0.0793f,-1.7983f,2.7725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7982f,0.0799f,2.8544f,0f,0.0799f,-1.7982f,2.3987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2718f,-1.2738f,2.5861f,0f,-1.2738f,-1.2718f,2.1934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9659f,-1.5189f,2.1845f,0f,-1.5189f,-0.9659f,2.3072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5173f,-0.9683f,2.0596f,0f,-0.9683f,-1.5173f,2.0199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5967f,0.831f,1.4228f,0f,0.831f,-1.5967f,2.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.5591f,-0.8995f,1.4138f,0f,-0.8995f,-1.5591f,1.4853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7384f,-0.4668f,1.9376f,0f,-0.4668f,-1.7384f,1.5529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.5967f,0.831f,1.4228f,0f,0.831f,-1.5967f,2.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.5591f,-0.8995f,1.4138f,0f,-0.8995f,-1.5591f,1.4853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7384f,-0.4668f,1.9376f,0f,-0.4668f,-1.7384f,1.5529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,-0.0009f,1.9993f,0f,-0.0009f,-1.8f,1.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0783f,0.8746f,0f,0.0783f,-1.7983f,-0.1136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6915f,0.6155f,1.105f,0f,0.6155f,-1.6915f,0.4603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.327f,-1.2162f,1.6922f,0f,-1.2162f,-1.327f,0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7983f,0.0783f,0.8746f,0f,0.0783f,-1.7983f,-0.1136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6915f,0.6155f,1.105f,0f,0.6155f,-1.6915f,0.4603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.327f,-1.2162f,1.6922f,0f,-1.2162f,-1.327f,0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7851f,-0.0917f,0.2124f,0.2241f,-0.1008f,1.7957f,-0.0721f,0.7683f,-0.2083f,-0.0834f,-1.786f,-2.3869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7851f,-0.0135f,0.231f,0.0942f,-0.1008f,1.6628f,-0.682f,1.1519f,-0.2083f,-0.6892f,-1.6497f,-1.4589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7933f,0f,0.1546f,0f,-0.0714f,1.5967f,-0.828f,1.6315f,-0.1372f,-0.831f,-1.5908f,-0.4766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7574f,-0.3894f,1.7473f,0f,-0.3894f,-1.7574f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7872969907,"pz":-0.3689384317,"ry":0,"rx":-12.4944930353},"hitbox_body_1":{"px":0,"py":1.0015545897,"pz":1.5394752091,"ry":0,"rx":-0.0301180353},"pos_head":{"px":0,"py":2.8395668709,"pz":2.7953778769,"ry":0,"rx":2.5444132147},"hitbox_head_0":{"px":0,"py":2.2259224541,"pz":2.7681089894,"ry":0,"rx":2.5444132147},"hitbox_tail_0":{"px":0.1694433295,"py":0.4573828894,"pz":-1.7675998082,"ry":7.9700625448,"rx":-22.2632028762},"hitbox_tail_1":{"px":0.3296806847,"py":0.2188307774,"pz":-3.025597119,"ry":6.7833657125,"rx":-2.2964544092}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args