# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_0) positioned ^0 ^0.7872 ^-0.3688 rotated ~0 ~-12.5 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_hitbox_body_0
$execute as $(hitbox_body_1) positioned ^0 ^1.0013 ^1.5389 rotated ~0 ~0 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_hitbox_body_1
execute positioned ^0 ^2.8391 ^2.796 rotated ~0 ~2.5 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_pos_head
$execute as $(hitbox_head_0) positioned ^0 ^2.2255 ^2.7692 rotated ~0 ~2.5 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_hitbox_head_0
$execute as $(hitbox_tail_0) positioned ^0.1719 ^0.4573 ^-1.7673 rotated ~8.0873 ~-22.2603 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_hitbox_tail_0
$execute as $(hitbox_tail_1) positioned ^0.3345 ^0.2188 ^-3.025 rotated ~6.883 ~-2.2946 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_hitbox_tail_1
$execute as $(shadow) positioned ^0 ^0.3938 ^-0.225 rotated ~0 ~0 run function animated_java_ranposu:ranposu/animations/idle_relax/zzz/frames/61_locator_shadow