# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^-0.273792 ^1.7568239791 ^-0.4387769055 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^-0.273792 ^2.1480895729 ^2.8887081974 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^-0.273792 ^1.981132682 ^3.6284778045 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_neck_1
execute positioned ^0 ^2.1521882008 ^5.0527484335 rotated ~0 ~59.9953 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_pos_head
$execute as $(hitbox_head_0) positioned ^-0.273792 ^1.4461671576 ^5.0783497943 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^0.7156575222 ^1.1941786113 ^0.017093339 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^0.9785158364 ^-0.7155620376 ^-0.2534677618 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^-0.7156575222 ^1.1941786113 ^0.017093339 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^-0.9785158364 ^-0.7155620376 ^-0.2534677618 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_leg_right_2
execute positioned ^0 ^3.0133143856 ^-2.6478143039 rotated ~0 ~-12.5047 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_pos_tail_0
execute positioned ^0 ^2.6487518214 ^-4.2114223454 rotated ~0 ~-7.5047 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^-0.273792 ^1.516362925 ^-3.6827752649 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_tail_1
execute positioned ^0 ^2.4449709737 ^-6.1866707136 rotated ~0 ~-7.5047 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_pos_tail_2
execute positioned ^0 ^2.477605564 ^-8.1477434893 rotated ~0 ~-0.0047 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^-0.273792 ^1.4214246225 ^-8.4619888862 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_tail_3
execute positioned ^0 ^3.4340228228 ^-10.3516639129 rotated ~0 ~17.4953 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^-0.273792 ^2.256954761 ^-10.6960228924 rotated ~180 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_hitbox_tail_4
$execute as $(shadow) positioned ^0 ^1.2125 ^0.25 rotated ~0 ~0 run function animated_java_dino:dino/animations/idle_relax/zzz/frames/76_locator_shadow