# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^1.3702 ^0.1775 ^-0.4675 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^1.7861 ^-0.2589 ^2.8366 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^1.4914 ^-0.7362 ^3.5622 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_neck_1
execute positioned ^0.0339 ^0.3733 ^4.5805 rotated ~69.5188 ~0.8344 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_pos_head
$execute as $(hitbox_head_0) positioned ^0.4937 ^-0.7812 ^4.7007 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^1.1269 ^-0.9614 ^-0.1237 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^-1.0487 ^-1.2528 ^-0.9547 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^1.195 ^0.4726 ^0.2865 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^-0.7357 ^-0.2998 ^0.682 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_leg_right_2
execute positioned ^1.1818 ^0.9672 ^-2.4636 rotated ~331.1906 ~-27.1117 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_pos_tail_0
execute positioned ^0.3115 ^0.361 ^-3.6496 rotated ~324.0889 ~-17.8462 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^0.443 ^-0.7378 ^-3.2927 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_tail_1
execute positioned ^-1.0588 ^0.0416 ^-4.922 rotated ~304.4539 ~-5.3244 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_pos_tail_2
execute positioned ^-2.8528 ^0.0361 ^-5.3298 rotated ~272.7108 ~1.8512 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^-3.5315 ^-1.1385 ^-5.3832 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_tail_3
execute positioned ^-4.9641 ^0.0134 ^-4.4517 rotated ~236.7531 ~-1.0362 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^-5.5906 ^-1.1916 ^-3.8385 rotated ~180 ~0 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_hitbox_tail_4
$execute as $(shadow) positioned ^-0.2077 ^1.3388 ^0.2756 rotated ~357.4359 ~-3.5214 run function animated_java_dino:dino/animations/death_bak/zzz/frames/126_locator_shadow