# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^-1.4135 ^1.6762 ^-1.1599 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^1.6177 ^0.9082 ^-0.2606 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^2.7 ^0.4782 ^-0.4024 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_neck_1
execute positioned ^2.9304 ^0.5661 ^0.6228 rotated ~19.2416 ~49.9899 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_pos_head
$execute as $(hitbox_head_0) positioned ^2.7278 ^-0.1432 ^0.523 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^1.2123 ^1.0616 ^-2.4938 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^0.9031 ^-0.696 ^-3.6306 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^0.4021 ^1.2876 ^0.1991 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^0.0558 ^-0.7968 ^0.3248 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_leg_right_2
execute positioned ^-2.6039 ^3.059 ^-2.4394 rotated ~298.5454 ~-16.2681 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_pos_tail_0
execute positioned ^-3.9553 ^2.3935 ^-2.8725 rotated ~276.5465 ~-26.0115 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^-3.9001 ^1.3315 ^-2.4558 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_tail_1
execute positioned ^-5.0426 ^1.4355 ^-3.8551 rotated ~334.9252 ~-34.1046 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_pos_tail_2
execute positioned ^-5.7356 ^0.7936 ^-5.5702 rotated ~340.5934 ~-17.5933 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^-6.2649 ^-0.488 ^-5.825 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_tail_3
execute positioned ^-5.4641 ^0.6783 ^-7.9019 rotated ~13.5691 ~-8.4283 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^-5.5467 ^-0.8506 ^-8.2454 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_hitbox_tail_4
$execute as $(shadow) positioned ^-0.5625 ^0.8375 ^-1.25 rotated ~0 ~0 run function animated_java_dino:dino/animations/damage_counter_tail_right_start/zzz/frames/40_locator_shadow