# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.dino_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dino_aj', 'function_path': 'animated_java:dino_aj/variants/default/apply'}
execute on passengers if entity @s[tag=aj.dino_aj.bone.head_lower] run function animated_java:dino_aj/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.dino_aj.bone.head_upper] run function animated_java:dino_aj/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.dino_aj.bone.neck_0] run function animated_java:dino_aj/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.dino_aj.bone.neck_1] run function animated_java:dino_aj/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.dino_aj.bone.neck_2] run function animated_java:dino_aj/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.dino_aj.bone.body_0] run function animated_java:dino_aj/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_3] run function animated_java:dino_aj/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_2] run function animated_java:dino_aj/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_1] run function animated_java:dino_aj/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_left_0] run function animated_java:dino_aj/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_3] run function animated_java:dino_aj/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_2] run function animated_java:dino_aj/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_1] run function animated_java:dino_aj/variants/default/zzz/12
execute on passengers if entity @s[tag=aj.dino_aj.bone.leg_right_0] run function animated_java:dino_aj/variants/default/zzz/13
execute on passengers if entity @s[tag=aj.dino_aj.bone.tail_4] run function animated_java:dino_aj/variants/default/zzz/14
execute on passengers if entity @s[tag=aj.dino_aj.bone.tail_3] run function animated_java:dino_aj/variants/default/zzz/15
execute on passengers if entity @s[tag=aj.dino_aj.bone.tail_2] run function animated_java:dino_aj/variants/default/zzz/16
execute on passengers if entity @s[tag=aj.dino_aj.bone.tail_1] run function animated_java:dino_aj/variants/default/zzz/17
execute on passengers if entity @s[tag=aj.dino_aj.bone.tail_0] run function animated_java:dino_aj/variants/default/zzz/18
execute on passengers if entity @s[tag=aj.dino_aj.bone.body_1] run function animated_java:dino_aj/variants/default/zzz/19