# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7958f,0.1223f,1.3392f,0f,0.1223f,-1.7958f,3.3015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7987f,-0.0674f,1.3395f,0f,-0.0674f,-1.7987f,2.9265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6702f,0.6713f,1.4234f,0f,0.6713f,-1.6702f,2.5993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7123f,0.555f,1.2127f,0f,0.555f,-1.7123f,2.2389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7842f,0.2382f,1.3025f,0f,0.2382f,-1.7842f,1.9388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2317f,-1.3126f,0.7703f,0f,-1.3126f,-1.2317f,1.5049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.787f,-0.2163f,0.9735f,0f,-0.2163f,-1.787f,1.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.436f,1.0854f,1.2418f,0f,1.0854f,-1.436f,1.4599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3315f,-1.2112f,0.7316f,0f,-1.2112f,-1.3315f,1.534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7854f,-0.2285f,0.9314f,0f,-0.2285f,-1.7854f,1.0327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.5329f,0.9436f,1.2418f,0f,0.9436f,-1.5329f,1.4599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.785f,0.2317f,1.3735f,0f,0.2317f,-1.785f,0.927f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.8f,0.0033f,0.8589f,0f,0.0033f,-1.8f,-0.4262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4726f,1.0351f,0.9318f,0f,1.0351f,-1.4726f,0.188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5981f,-0.8282f,1.5868f,0f,-0.8282f,-1.5981f,0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.8514f,0f,0f,-1.8f,-0.7469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4745f,1.0324f,0.9254f,0f,1.0324f,-1.4745f,-0.1329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.8f,0f,1.5868f,0f,0f,-1.8f,0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7806f,-0.2637f,2.0164f,0f,-0.2637f,-1.7806f,-2.6252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7993f,0.0495f,1.9885f,0f,0.0495f,-1.7993f,-1.6131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7917f,0.1727f,1.8553f,0f,0.1727f,-1.7917f,-0.524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6937f,0.6095f,1.5769f,0f,0.6095f,-1.6937f,0.1334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.0841035861,"pz":-0.8839585158,"ry":0,"rx":19.7916666667},"hitbox_body_1":{"px":0,"py":0.3153912643,"pz":1.3256205226,"ry":0,"rx":7.3958333333},"pos_head":{"px":0,"py":1.3572066207,"pz":3.3230087576,"ry":0,"rx":-2.1458333333},"hitbox_head_0":{"px":0,"py":0.7433873566,"pz":3.3460081831,"ry":0,"rx":-2.1458333333},"hitbox_tail_0":{"px":0,"py":1.480066031,"pz":-2.1830221142,"ry":0,"rx":1.5773809524},"hitbox_tail_1":{"px":0,"py":1.4002236255,"pz":-3.2094715904,"ry":0,"rx":-8.4226190476},"shadow":{"px":0,"py":0.2233455882,"pz":-0.3195,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args