# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.771f,0.3216f,1.3399f,0f,0.3216f,-1.771f,3.3059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7991f,-0.0563f,1.3426f,0f,-0.0563f,-1.7991f,2.9309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6771f,0.6536f,1.423f,0f,0.6536f,-1.6771f,2.6028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7078f,0.5687f,1.2153f,0f,0.5687f,-1.7078f,2.2407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7837f,0.2414f,1.3055f,0f,0.2414f,-1.7837f,1.9408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2185f,-1.3249f,0.7694f,0f,-1.3249f,-1.2185f,1.5091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7869f,-0.2171f,0.9724f,0f,-0.2171f,-1.7869f,1.0091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.4438f,1.0749f,1.244f,0f,1.0749f,-1.4438f,1.462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3359f,-1.2064f,0.7347f,0f,-1.2064f,-1.3359f,1.5334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7863f,-0.222f,0.9363f,0f,-0.222f,-1.7863f,1.0328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.5268f,0.9533f,1.244f,0f,0.9533f,-1.5268f,1.462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7854f,0.2285f,1.3747f,0f,0.2285f,-1.7854f,0.9289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.8f,0.0065f,0.8576f,0f,0.0065f,-1.8f,-0.4264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4707f,1.0378f,0.9294f,0f,1.0378f,-1.4707f,0.1879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5996f,-0.8253f,1.5847f,0f,-0.8253f,-1.5996f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.8493f,0f,0f,-1.8f,-0.7458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4745f,1.0324f,0.9233f,0f,1.0324f,-1.4745f,-0.1318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.8f,0f,1.5847f,0f,0f,-1.8f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7872f,-0.2145f,2.0971f,0f,-0.2145f,-1.7872f,-2.6155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7973f,0.0991f,2.0414f,0f,0.0991f,-1.7973f,-1.6045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7802f,0.2664f,1.8513f,0f,0.2664f,-1.7802f,-0.5239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6959f,0.6033f,1.5753f,0f,0.6033f,-1.6959f,0.1345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0787533339,"pz":-0.8810348973,"ry":0,"rx":19.5833333333},"hitbox_body_1":{"px":0,"py":0.31735038,"pz":1.3294029083,"ry":0,"rx":7.2916666667},"pos_head":{"px":0,"py":1.3578471264,"pz":3.3274718147,"ry":0,"rx":-1.7916666667},"hitbox_head_0":{"px":0,"py":0.743897422,"pz":3.3466765783,"ry":0,"rx":-1.7916666667},"hitbox_tail_0":{"px":0,"py":1.5488290459,"pz":-2.1882002795,"ry":0,"rx":3.1547619048},"hitbox_tail_1":{"px":0,"py":1.4972719847,"pz":-3.2164586159,"ry":0,"rx":-6.8452380952},"shadow":{"px":0,"py":0.2216911765,"pz":-0.318375,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args