# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.4585f,1.0548f,1.343f,0f,1.0548f,-1.4585f,3.3224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.8f,-0.0118f,1.355f,0f,-0.0118f,-1.8f,2.9476f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7032f,0.5824f,1.4215f,0f,0.5824f,-1.7032f,2.6164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6888f,0.623f,1.2254f,0f,0.623f,-1.6888f,2.2479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7819f,0.2544f,1.3178f,0f,0.2544f,-1.7819f,1.9486f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.1645f,-1.3725f,0.7661f,0f,-1.3725f,-1.1645f,1.5258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7865f,-0.2203f,0.9682f,0f,-0.2203f,-1.7865f,1.0254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.4745f,1.0324f,1.2528f,0f,1.0324f,-1.4745f,1.4703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3533f,-1.1868f,0.7473f,0f,-1.1868f,-1.3533f,1.5309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7893f,-0.196f,0.9562f,0f,-0.196f,-1.7893f,1.0334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.5021f,0.9918f,1.2528f,0f,0.9918f,-1.5021f,1.4703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7871f,0.2155f,1.3797f,0f,0.2155f,-1.7871f,0.9362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7999f,0.0196f,0.8525f,0f,0.0196f,-1.7999f,-0.4273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4631f,1.0485f,0.9198f,0f,1.0485f,-1.4631f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6056f,-0.8137f,1.5763f,0f,-0.8137f,-1.6056f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.841f,0f,0f,-1.8f,-0.7414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4745f,1.0324f,0.915f,0f,1.0324f,-1.4745f,-0.1274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.8f,0f,1.5763f,0f,0f,-1.8f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7999f,-0.0168f,2.4126f,0f,-0.0168f,-1.7999f,-2.5394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7755f,0.296f,2.2461f,0f,0.296f,-1.7755f,-1.5407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6856f,0.6314f,1.835f,0f,0.6314f,-1.6856f,-0.5233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7045f,0.5786f,1.5686f,0f,0.5786f,-1.7045f,0.139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.0574184563,"pz":-0.8692063984,"ry":0,"rx":18.75},"hitbox_body_1":{"px":0,"py":0.3252478965,"pz":1.3444140279,"ry":0,"rx":6.875},"pos_head":{"px":0,"py":1.3603900624,"pz":3.3444261398,"ry":0,"rx":-0.375},"hitbox_head_0":{"px":0,"py":0.7461532186,"pz":3.3484463679,"ry":0,"rx":-0.375},"hitbox_tail_0":{"px":0,"py":1.8206781258,"pz":-2.1749216426,"ry":0,"rx":9.4642857143},"hitbox_tail_1":{"px":0,"py":1.8824384664,"pz":-3.2026176079,"ry":0,"rx":-0.5357142857},"shadow":{"px":0,"py":0.2150735294,"pz":-0.313875,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args