# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.2338f,1.3106f,1.3816f,0f,1.3106f,-1.2338f,3.3737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.8f,0.0046f,1.397f,0f,0.0046f,-1.8f,2.999f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6786f,0.6498f,1.4766f,0f,0.6498f,-1.6786f,2.6707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6637f,0.6871f,1.2948f,0f,0.6871f,-1.6637f,2.295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7738f,0.3061f,1.3959f,0f,0.3061f,-1.7738f,1.9985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.931f,-1.5405f,0.7842f,0f,-1.5405f,-0.931f,1.6153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7848f,-0.2333f,0.9826f,0f,-0.2333f,-1.7848f,1.1135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.5844f,0.8543f,1.317f,0f,0.8543f,-1.5844f,1.5223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.42f,-1.1061f,0.8288f,0f,-1.1061f,-1.42f,1.5421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7977f,-0.0916f,1.0662f,0f,-0.0916f,-1.7977f,1.0575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.3935f,1.1394f,1.317f,0f,1.1394f,-1.3935f,1.5223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7926f,0.1634f,1.4283f,0f,0.1634f,-1.7926f,0.9847f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7986f,0.072f,0.8608f,0f,0.072f,-1.7986f,-0.4095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.432f,1.0906f,0.9101f,0f,1.0906f,-1.432f,0.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6286f,-0.7666f,1.5713f,0f,-0.7666f,-1.6286f,0.0586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.836f,0f,0f,-1.8f,-0.7028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4745f,1.0324f,0.9099f,0f,1.0324f,-1.4745f,-0.0887f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.8f,0f,1.5713f,0f,0f,-1.8f,0.0586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5653f,0.8886f,2.498f,0f,0.8886f,-1.5653f,-2.4672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5905f,0.8427f,2.0239f,0f,0.8427f,-1.5905f,-1.5725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7703f,0.3254f,1.798f,0f,0.3254f,-1.7703f,-0.4988f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7352f,0.4785f,1.5705f,0f,0.4785f,-1.7352f,0.1779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0015524912,"pz":-0.7988830153,"ry":0,"rx":15.4166666667},"hitbox_body_1":{"px":0,"py":0.3861304127,"pz":1.4234396125,"ry":0,"rx":5.2083333333},"pos_head":{"px":0,"py":1.3987686769,"pz":3.3958602116,"ry":0,"rx":0.1469047619},"hitbox_head_0":{"px":0,"py":0.7845206959,"pz":3.3942852937,"ry":0,"rx":0.1469047619},"hitbox_tail_0":{"px":0,"py":1.8211081792,"pz":-2.3088601549,"ry":0,"rx":27.9166666667},"hitbox_tail_1":{"px":0,"py":2.3721890558,"pz":-3.3069572115,"ry":0,"rx":29.5833333333},"shadow":{"px":0,"py":0.2169642857,"pz":-0.2749821429,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args