# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.42f,1.1061f,1.4853f,0f,1.1061f,-1.42f,3.3915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.8f,0.0131f,1.5024f,0f,0.0131f,-1.8f,3.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7167f,0.5413f,1.5609f,0f,0.5413f,-1.7167f,2.6841f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6869f,0.6279f,1.3659f,0f,0.6279f,-1.6869f,2.3151f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.4681f,0f,0.3126f,-1.7727f,2.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9671f,-1.5181f,0.8287f,0f,-1.5181f,-0.9671f,1.6591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7828f,-0.2479f,1.023f,0f,-0.2479f,-1.7828f,1.1556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.6314f,0.7607f,1.3806f,0f,0.7607f,-1.6314f,1.5443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.4038f,-1.1267f,0.8688f,0f,-1.1267f,-1.4038f,1.5854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7961f,-0.1177f,1.0992f,0f,-0.1177f,-1.7961f,1.0974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.4669f,1.0431f,1.3806f,0f,1.0431f,-1.4669f,1.5443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7952f,0.1308f,1.4821f,0f,0.1308f,-1.7952f,1.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.8716f,0f,0.0785f,-1.7983f,-0.4025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4669f,1.0431f,0.9411f,0f,1.0431f,-1.4669f,0.2121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6422f,-0.7369f,1.6049f,0f,-0.7369f,-1.6422f,0.0758f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0.0131f,0.8442f,0f,0.0131f,-1.8f,-0.6445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5039f,0.9891f,0.936f,0f,0.9891f,-1.5039f,-0.0329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.797f,-0.1047f,1.6049f,0f,-0.1047f,-1.797f,0.0758f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7002f,0.591f,1.9927f,0f,0.591f,-1.7002f,-2.589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7952f,0.1308f,1.9191f,0f,0.1308f,-1.7952f,-1.5791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7961f,0.1177f,1.8193f,0f,0.1177f,-1.7961f,-0.4865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,0.4405f,1.6067f,0f,0.4405f,-1.7453f,0.1951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.0165404895,"pz":-0.7690687616,"ry":0,"rx":14.1666666667},"hitbox_body_1":{"px":0,"py":0.4480739041,"pz":1.4623937216,"ry":0,"rx":4.1666666667},"pos_head":{"px":0,"py":1.5023259854,"pz":3.4137550238,"ry":0,"rx":0.4166666667},"hitbox_head_0":{"px":0,"py":0.8880922276,"pz":3.4092881111,"ry":0,"rx":0.4166666667},"hitbox_tail_0":{"px":0,"py":1.4368986396,"pz":-2.1714165221,"ry":0,"rx":4.1666666667},"hitbox_tail_1":{"px":0,"py":1.7171241225,"pz":-3.392127904,"ry":0,"rx":19.1666666667},"shadow":{"px":0,"py":0.253125,"pz":-0.2578125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args