# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.676f,0.6565f,1.6712f,0f,0.6565f,-1.676f,3.3965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7995f,0.0436f,1.6947f,0f,0.0436f,-1.7995f,3.0222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7628f,0.364f,1.7191f,0f,0.364f,-1.7628f,2.6853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7341f,0.4827f,1.4935f,0f,0.4827f,-1.7341f,2.3341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.5957f,0f,0.3126f,-1.7727f,2.0379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.1164f,-1.4119f,0.9112f,0f,-1.4119f,-1.1164f,1.7229f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7784f,-0.2781f,1.0969f,0f,-0.2781f,-1.7784f,1.2162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7002f,0.591f,1.4921f,0f,0.591f,-1.7002f,1.5665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3446f,-1.1966f,0.9274f,0f,-1.1966f,-1.3446f,1.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7878f,-0.209f,1.1326f,0f,-0.209f,-1.7878f,1.1796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.635f,0.7528f,1.4921f,0f,0.7528f,-1.635f,1.5665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7986f,0.0698f,1.5752f,0f,0.0698f,-1.7986f,1.0239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.8771f,0f,0.0785f,-1.7983f,-0.4015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.55f,0.9151f,0.9984f,0f,0.9151f,-1.55f,0.205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6663f,-0.6808f,1.6664f,0f,-0.6808f,-1.6663f,0.0913f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7995f,0.0436f,0.856f,0f,0.0436f,-1.7995f,-0.5299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5675f,0.8848f,0.9891f,0f,0.8848f,-1.5675f,0.0741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7663f,-0.3469f,1.6664f,0f,-0.3469f,-1.7663f,0.0913f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,-0.0087f,1.842f,0f,-0.0087f,-1.8f,-2.5848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7964f,-0.1134f,1.9058f,0f,-0.1134f,-1.7964f,-1.5743f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7998f,0.0262f,1.8617f,0f,0.0262f,-1.7998f,-0.478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7592f,0.3811f,1.6723f,0f,0.3811f,-1.7592f,0.2104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.0497921101,"pz":-0.7331770762,"ry":0,"rx":12.2222222222},"hitbox_body_1":{"px":0,"py":0.5573673619,"pz":1.516288847,"ry":0,"rx":2.2222222222},"pos_head":{"px":0,"py":1.6878713006,"pz":3.4190323381,"ry":0,"rx":1.3888888889},"hitbox_head_0":{"px":0,"py":1.0738017617,"pz":3.4041439561,"ry":0,"rx":1.3888888889},"hitbox_tail_0":{"px":0,"py":1.3478308062,"pz":-2.0958818342,"ry":0,"rx":-3.6111111111},"hitbox_tail_1":{"px":0,"py":1.3147846001,"pz":-3.2504283898,"ry":0,"rx":-0.2777777778},"shadow":{"px":0,"py":0.31875,"pz":-0.2425,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args