# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7016f,0.5868f,1.6977f,0f,0.5868f,-1.7016f,3.3965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7994f,0.048f,1.7221f,0f,0.048f,-1.7994f,3.0223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7679f,0.3383f,1.7415f,0f,0.3383f,-1.7679f,2.685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7398f,0.4617f,1.5117f,0f,0.4617f,-1.7398f,2.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.6139f,0f,0.3126f,-1.7727f,2.0405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.1368f,-1.3956f,0.9233f,0f,-1.3956f,-1.1368f,1.7322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7777f,-0.2824f,1.1078f,0f,-0.2824f,-1.7777f,1.225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7086f,0.5662f,1.5081f,0f,0.5662f,-1.7086f,1.5696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3359f,-1.2064f,0.9368f,0f,-1.2064f,-1.3359f,1.6929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7863f,-0.222f,1.1384f,0f,-0.222f,-1.7863f,1.1924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.6545f,0.7089f,1.5081f,0f,0.7089f,-1.6545f,1.5696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.799f,0.0611f,1.5886f,0f,0.0611f,-1.799f,1.0265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.878f,0f,0.0785f,-1.7983f,-0.401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.561f,0.8962f,1.0067f,0f,0.8962f,-1.561f,0.2039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6696f,-0.6727f,1.6752f,0f,-0.6727f,-1.6696f,0.0935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7994f,0.048f,0.8587f,0f,0.048f,-1.7994f,-0.5132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.576f,0.8696f,0.9976f,0f,0.8696f,-1.576f,0.0894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7592f,-0.3811f,1.6752f,0f,-0.3811f,-1.7592f,0.0935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7974f,-0.0959f,1.8205f,0f,-0.0959f,-1.7974f,-2.5824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7939f,-0.1482f,1.9038f,0f,-0.1482f,-1.7939f,-1.5733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0.0131f,1.8677f,0f,0.0131f,-1.8f,-0.4767f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.761f,0.3725f,1.6817f,0f,0.3725f,-1.761f,0.2126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.0546000048,"pz":-0.7279604226,"ry":0,"rx":11.9444444444},"hitbox_body_1":{"px":0,"py":0.5730867195,"pz":1.5238663977,"ry":0,"rx":1.9444444444},"pos_head":{"px":0,"py":1.7142881871,"pz":3.4191114278,"ry":0,"rx":1.5277777778},"hitbox_head_0":{"px":0,"py":1.1002565428,"pz":3.4027345445,"ry":0,"rx":1.5277777778},"hitbox_tail_0":{"px":0,"py":1.3358834541,"pz":-2.0839788305,"ry":0,"rx":-4.7222222222},"hitbox_tail_1":{"px":0,"py":1.2616251026,"pz":-3.2216842247,"ry":0,"rx":-3.0555555556},"shadow":{"px":0,"py":0.328125,"pz":-0.2403125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args