# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0785f,1.5491f,0f,0.0785f,-1.7983f,3.3823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7998f,0.0236f,1.5684f,0f,0.0236f,-1.7998f,3.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7345f,0.481f,1.6153f,0f,0.481f,-1.7345f,2.6732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7045f,0.5786f,1.4096f,0f,0.5786f,-1.7045f,2.31f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.5118f,0f,0.3126f,-1.7727f,2.0139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2728f,-1.2728f,0.9206f,0f,-1.2728f,-1.2728f,1.6321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7727f,-0.3126f,1.0964f,0f,-0.3126f,-1.7727f,1.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.5588f,0.9f,1.4188f,0f,0.9f,-1.5588f,1.5403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.2333f,-1.3111f,0.8764f,0f,-1.3111f,-1.2333f,1.6911f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7623f,-0.3666f,1.0365f,0f,-0.3666f,-1.7623f,1.1758f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.6776f,0.6524f,1.4188f,0f,0.6524f,-1.6776f,1.5403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7966f,0.1099f,1.514f,0f,0.1099f,-1.7966f,0.9996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.8733f,0f,0.0785f,-1.7983f,-0.4144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4966f,1f,0.9607f,0f,1f,-1.4966f,0.1978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6507f,-0.7177f,1.626f,0f,-0.7177f,-1.6507f,0.0693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7998f,0.0236f,0.8468f,0f,0.0236f,-1.7998f,-0.6175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5265f,0.9539f,0.9528f,0f,0.9539f,-1.5265f,-0.0082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7901f,-0.1882f,1.626f,0f,-0.1882f,-1.7901f,0.0693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,0.3896f,1.9411f,0f,0.3896f,-1.7573f,-2.6019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7994f,0.0471f,1.9146f,0f,0.0471f,-1.7994f,-1.5897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7979f,0.0864f,1.8339f,0f,0.0864f,-1.7979f,-0.4954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7503f,0.4202f,1.6292f,0f,0.4202f,-1.7503f,0.1885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0278625872,"pz":-0.7686994502,"ry":0,"rx":13.5},"hitbox_body_1":{"px":0,"py":0.4853981415,"pz":1.4692262407,"ry":0,"rx":3.5},"pos_head":{"px":0,"py":1.5660458532,"pz":3.4046857578,"ry":0,"rx":0.75},"hitbox_head_0":{"px":0,"py":0.9518484775,"pz":3.3966454737,"ry":0,"rx":0.75},"hitbox_tail_0":{"px":0,"py":1.4053357806,"pz":-2.1589057864,"ry":0,"rx":1.5},"hitbox_tail_1":{"px":0,"py":1.5741543472,"pz":-3.367602502,"ry":0,"rx":12.5},"shadow":{"px":0,"py":0.275625,"pz":-0.264375,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args