# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0785f,1.8371f,0f,0.0785f,-1.7983f,3.3415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7983f,0.0785f,1.8678f,0f,0.0785f,-1.7983f,2.9677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,0.1569f,1.8529f,0f,0.1569f,-1.7932f,2.6302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.5944f,0f,0.3126f,-1.7727f,2.3025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.6966f,0f,0.3126f,-1.7727f,2.0064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2728f,-1.2728f,0.9657f,0f,-1.2728f,-1.2728f,1.7475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7727f,-0.3126f,1.1416f,0f,-0.3126f,-1.7727f,1.2373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7573f,0.3896f,1.5748f,0f,0.3896f,-1.7573f,1.5394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.2728f,-1.2728f,0.9657f,0f,-1.2728f,-1.2728f,1.7475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7727f,-0.3126f,1.1416f,0f,-0.3126f,-1.7727f,1.2373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7573f,0.3896f,1.5748f,0f,0.3896f,-1.7573f,1.5394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.6369f,0f,0f,-1.8f,0.9939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.8405f,0f,0.0785f,-1.7983f,-0.4457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6314f,0.7607f,1.0199f,0f,0.7607f,-1.6314f,0.1462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6914f,-0.6156f,1.6918f,0f,-0.6156f,-1.6914f,0.0585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7983f,0.0785f,0.8405f,0f,0.0785f,-1.7983f,-0.4457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6314f,0.7607f,1.0199f,0f,0.7607f,-1.6314f,0.1462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6914f,-0.6156f,1.6918f,0f,-0.6156f,-1.6914f,0.0585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.663f,-0.6888f,1.626f,0f,-0.6888f,-1.663f,-2.6035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,-0.3896f,1.8451f,0f,-0.3896f,-1.7573f,-1.615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,-0.0785f,1.8649f,0f,-0.0785f,-1.7983f,-0.5179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.7023f,0f,0.3126f,-1.7727f,0.1772f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0436739373,"pz":-0.7414539239,"ry":0,"rx":10},"hitbox_body_1":{"px":0,"py":0.6388433922,"pz":1.5254142465,"ry":0,"rx":0},"pos_head":{"px":0,"py":1.8533186397,"pz":3.3643625246,"ry":0,"rx":2.5},"hitbox_head_0":{"px":0,"py":1.2396532696,"pz":3.3375693159,"ry":0,"rx":2.5},"hitbox_tail_0":{"px":0,"py":1.2132847991,"pz":-2.044065493,"ry":0,"rx":-12.5},"hitbox_tail_1":{"px":0,"py":0.8861747401,"pz":-3.020268518,"ry":0,"rx":-22.5},"shadow":{"px":0,"py":0.34875,"pz":-0.275625,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args