# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s item.components.minecraft:custom_model_data set value 2129
data merge entity @s {}