# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.valk_aj.root] run return 0
execute on passengers if entity @s[tag=aj.valk_aj.data] unless data entity @s {data:{rigHash: '22275065d0d27b5dba1031e9a704bef739ea5d3df59817d58ff3457d78c74cc7'}} on vehicle run function animated_java:valk_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1