# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.valk_aj.root] run return 0
execute on passengers if entity @s[tag=aj.valk_aj.data] unless data entity @s {data:{rigHash: '3a658dfa8d19108e82cf355d699f97e85e1a7c8213ca41f774f773366f7d8a69'}} on vehicle run function animated_java:valk_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1