# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.valk_aj.root] run return 0
execute on passengers if entity @s[tag=aj.valk_aj.data] unless data entity @s {data:{rigHash: 'f1e7128261be3680d20e24752a21595ce892f6e8c963264575ce2a4f562fc46d'}} on vehicle run function animated_java:valk_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1