# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-4.5f,0.0124f,-0.0116f,-0.0015f,0.0107f,4.458f,0.6134f,1.9521f,0.0132f,0.6133f,-4.458f,4.7646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-4.5f,0.0117f,-0.0123f,-0.001f,0.0107f,4.4874f,0.3365f,2.7138f,0.0132f,0.3365f,-4.4874f,4.3212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-4.5f,-0.0008f,0.0073f,0f,-0.0007f,4.4998f,0.0413f,2.8001f,-0.0073f,0.0413f,-4.4998f,3.7137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-4.5f,0f,0f,0f,0f,4.4957f,0.1962f,2.8242f,0f,0.1962f,-4.4957f,2.9544f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-4.5f,0f,0f,0f,0f,4.4998f,0.0408f,2.8127f,0f,0.0408f,-4.4998f,2.2261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_right_1) {transformation: [-4.4311f,-0.2658f,-0.7378f,-2.4919f,-0.6311f,-1.3049f,4.2602f,3.3148f,-0.4656f,4.2984f,1.2477f,0.7811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_right_0) {transformation: [-4.2515f,-1.4144f,0.4174f,-0.5522f,0.7985f,-1.137f,4.2801f,2.9286f,-1.2398f,4.1179f,1.3252f,1.442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_left_1) {transformation: [-4.4261f,0.2658f,0.7673f,2.4919f,0.6594f,-1.3049f,4.2559f,3.3148f,0.4739f,4.2984f,1.2445f,0.7811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_left_0) {transformation: [-4.2515f,1.4144f,-0.4174f,0.5522f,-0.7985f,-1.137f,4.2801f,2.9286f,1.2398f,4.1179f,1.3252f,1.442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-4.5f,0f,0f,0f,0f,4.4604f,0.5953f,3.1276f,0f,0.5953f,-4.4604f,0.7193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0563,"pz":1.1625,"ry":0,"rx":7.6025},"hitbox_neck_0":{"px":0,"py":1.2695,"pz":3.0678,"ry":0,"rx":2.4992},"pos_head":{"px":0.0006,"py":2.1162,"pz":5.3325,"ry":359.8424,"rx":4.289},"hitbox_head_0":{"px":-0.0028,"py":1.1108,"pz":5.0119,"ry":359.8424,"rx":4.289}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args