# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.search.frame matches 76.. run scoreboard players set @s aj.search.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.search.frame
execute at @s run function animated_java:ranposu/animations/search/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.search.frame 1