# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^-0.0543 ^-0.0831 ^-0.9894 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^-0.5568 ^0.126 ^1.2644 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^-1.1323 ^0.1211 ^2.4653 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_neck_1
$execute as $(hitbox_neck_0) positioned ^-2.0873 ^-0.1375 ^3.4126 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_neck_0
execute positioned ^-3.3136 ^0.3426 ^4.2029 rotated ~79.1256 ~18.8779 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_head
$execute as $(head_0) positioned ^-2.9879 ^-0.6187 ^3.4772 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_head_0
$execute as $(hitbox_arm_right_0) positioned ^-3.6719 ^-0.3102 ^0.837 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_arm_right_0
$execute as $(hitbox_arm_left_0) positioned ^-2.5047 ^-0.5165 ^-0.2789 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_arm_left_0
execute positioned ^0.5189 ^7.5545 ^0.2875 rotated ~22.5654 ~55.4198 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_muzzle_r_0
execute positioned ^2.3517 ^8.8766 ^1.174 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_muzzle_r_1
execute positioned ^-1.2909 ^1.5 ^3.6533 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_r_0
execute positioned ^-0.0464 ^4.03 ^2.8294 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_r_1
execute positioned ^1.1982 ^6.5601 ^2.0056 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_r_2
execute positioned ^2.4428 ^9.0902 ^1.1817 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_r_3
execute positioned ^3.6873 ^11.6202 ^0.3578 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_r_4
execute positioned ^4.9319 ^14.1503 ^-0.466 rotated ~56.4966 ~59.4624 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_r_5
$execute as $(hitbox_finger_right_0) positioned ^0.1972 ^3.5665 ^2.2123 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_right_0
$execute as $(hitbox_finger_right_1) positioned ^1.6466 ^5.6288 ^1.9541 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_right_1
$execute as $(hitbox_finger_right_2) positioned ^2.8021 ^8.2711 ^1.0889 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_right_2
$execute as $(hitbox_finger_right_3) positioned ^4.0423 ^11.1067 ^0.1604 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_right_3
execute positioned ^0.374 ^5.7529 ^-0.2819 rotated ~14.3809 ~35.693 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_muzzle_r_2
execute positioned ^5.1762 ^1.0944 ^0.2131 rotated ~31.6817 ~2.9157 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_muzzle_l_0
execute positioned ^3.8424 ^1.0726 ^-1.8153 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_muzzle_l_1
execute positioned ^1.8345 ^0.6107 ^6.5266 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_l_0
execute positioned ^2.5028 ^0.7857 ^3.6715 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_l_1
execute positioned ^3.1711 ^0.9606 ^0.8163 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_l_2
execute positioned ^3.8395 ^1.1356 ^-2.0388 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_l_3
execute positioned ^4.5078 ^1.3106 ^-4.8939 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_l_4
execute positioned ^5.1761 ^1.4855 ^-7.749 rotated ~13.1743 ~3.4145 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_wing_l_5
$execute as $(hitbox_finger_left_0) positioned ^2.8688 ^-0.1457 ^3.331 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_left_0
$execute as $(hitbox_finger_left_1) positioned ^2.9224 ^0.0691 ^1.4865 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_left_1
$execute as $(hitbox_finger_left_2) positioned ^3.6924 ^0.3444 ^-1.4112 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_left_2
$execute as $(hitbox_finger_left_3) positioned ^4.5188 ^0.6398 ^-4.521 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_finger_left_3
execute positioned ^5.3388 ^-0.1025 ^1.6731 rotated ~46.0197 ~-11.83 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_muzzle_l_2
$execute as $(hitbox_leg_right_0) positioned ^-2.0055 ^0.3283 ^-1.2108 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_leg_right_0
$execute as $(hitbox_leg_left_0) positioned ^-0.9029 ^-0.5149 ^-1.8177 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_leg_left_0
$execute as $(hitbox_tail_0) positioned ^-0.4811 ^0.2889 ^-1.6145 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_tail_0
$execute as $(hitbox_tail_1) positioned ^-0.5168 ^0.2185 ^-3.0959 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_tail_1
$execute as $(hitbox_tail_2) positioned ^-1.3692 ^0.0556 ^-4.7926 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_tail_2
$execute as $(hitbox_tail_3) positioned ^-2.2658 ^-0.1355 ^-6.0251 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_tail_3
$execute as $(hitbox_tail_4) positioned ^-3.96 ^-0.0306 ^-7.1855 rotated ~180 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_hitbox_tail_4
$execute as $(shadow) positioned ^0 ^-0.6594 ^-0.2203 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_shadow
execute positioned ^0 ^-1.8344 ^0 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_pos_comet_star
execute positioned ^0 ^1.6906 ^-2.0562 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_beam_start
execute positioned ^0 ^1.6906 ^-2.0561 rotated ~0 ~0 run function animated_java_valk:valk/animations/lance_damage_down_r/zzz/frames/31_locator_beam_end