# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.5093f,0.9809f,2.5157f,0f,0.9809f,-1.5093f,3.2088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.8f,0.0092f,2.532f,0f,0.0092f,-1.8f,2.8341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6499f,-0.7197f,2.3575f,0f,-0.7197f,-1.6499f,2.5449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7498f,-0.4223f,1.9896f,0f,-0.4223f,-1.7498f,2.3478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7586f,-0.384f,1.9716f,0f,-0.384f,-1.7586f,2.0351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7996f,0.0343f,0.0181f,0.4185f,0.0016f,0.9019f,-1.5578f,0.976f,-0.0387f,-1.5574f,-0.9017f,1.8928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7996f,-0.001f,0.0388f,0.4313f,0.0016f,1.796f,0.1199f,1.2686f,-0.0387f,0.1199f,-1.7956f,1.4395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7846f,-0.0664f,-0.2256f,0.4078f,-0.0437f,1.7904f,-0.1808f,1.7738f,0.2311f,-0.1738f,-1.7766f,1.5949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7861f,-0.1287f,-0.1822f,-0.4561f,0.108f,0.7883f,-1.6146f,0.8936f,0.1952f,-1.6131f,-0.7745f,1.8996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7861f,0.1501f,-0.1651f,-0.4803f,0.108f,1.747f,0.4201f,1.2579f,0.1952f,0.407f,-1.7425f,1.5023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7861f,0.0663f,-0.213f,-0.4078f,0.108f,1.7608f,-0.3576f,1.7738f,0.1952f,-0.3676f,-1.7512f,1.5949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7748f,-0.2999f,1.744f,0f,-0.2999f,-1.7748f,1.0467f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7859f,-0.225f,1.0352f,0f,-0.225f,-1.7859f,-0.0775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5538f,0.9086f,1.159f,0f,0.9086f,-1.5538f,0.5285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.1427f,-1.3907f,1.6928f,0f,-1.3907f,-1.1427f,0.111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7889f,0.1998f,0.9133f,0f,0.1998f,-1.7889f,-0.3768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5368f,0.9371f,1.0259f,0f,0.9371f,-1.5368f,0.2313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6595f,-0.6973f,1.6928f,0f,-0.6973f,-1.6595f,0.111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7669f,0.3435f,1.2863f,0f,0.3435f,-1.7669f,-2.503f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7924f,-0.1647f,1.379f,0f,-0.1647f,-1.7924f,-1.4947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6444f,-0.7321f,1.7994f,0f,-0.7321f,-1.6444f,-0.4812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7966f,0.1099f,1.7166f,0f,0.1099f,-1.7966f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.9582264306,"pz":-0.6103631035,"ry":0,"rx":3.5},"hitbox_body_1":{"px":0,"py":0.8485256567,"pz":1.7370373574,"ry":0,"rx":-9.59},"pos_head":{"px":0,"py":2.5327717236,"pz":3.2310312447,"ry":0,"rx":0.2927272727},"hitbox_head_0":{"px":0,"py":1.9185297403,"pz":3.2278930215,"ry":0,"rx":0.2927272727},"hitbox_tail_0":{"px":0,"py":0.8063683441,"pz":-2.0001025226,"ry":0,"rx":-5.25},"hitbox_tail_1":{"px":0,"py":0.8994908243,"pz":-3.2588317808,"ry":0,"rx":11},"shadow":{"px":0,"py":0.3630681818,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args