# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.4375 ^0 ~0 ~0
data modify storage animated_java:temp entry.data.interactions.interaction merge value { px: 0, py: 0.4375, pz: 0, ry: 0, rx: 0 }