# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute if score @s aj.shoot_shot_forward.frame matches 88.. run scoreboard players set @s aj.shoot_shot_forward.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.shoot_shot_forward.frame
execute at @s run function animated_java_valk:valk/animations/shoot_shot_forward/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.shoot_shot_forward.frame 1