# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ranposu_aj/animations/down/zzz/apply_frame {frame: 35}
scoreboard players add @s aj.frame 1