# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.shoot_bomb_forward.frame
function animated_java:valk_aj/animations/shoot_bomb_forward/zzz/apply_frame with storage aj:temp
execute if score @s aj.shoot_bomb_forward.frame matches 96.. run return run function animated_java:valk_aj/animations/shoot_bomb_forward/pause
scoreboard players add @s aj.shoot_bomb_forward.frame 1