# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.7301f,-0.4153f,0.2724f,-0.211f,-0.2284f,1.5419f,0.9002f,3.1728f,-0.441f,0.8307f,-1.5347f,2.8634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.7457f,0.1791f,0.4005f,-0.1261f,-0.17f,1.2385f,-1.295f,2.9131f,-0.4044f,-1.2938f,-1.1843f,2.6065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.7457f,0.0844f,0.4305f,-0.0482f,-0.17f,1.4981f,-0.9832f,2.6933f,-0.4044f,-0.9943f,-1.445f,2.3621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.7939f,0f,0.1477f,-0.0254f,-0.0492f,1.6973f,-0.5973f,2.3074f,-0.1392f,-0.5993f,-1.6916f,2.2047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.7939f,0f,0.1477f,0f,-0.0492f,1.6973f,-0.5973f,2.2512f,-0.1392f,-0.5993f,-1.6916f,1.8976f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2093f,-1.3332f,1.278f,0f,-1.3332f,-1.2093f,1.8638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7553f,-0.3985f,1.4288f,0f,-0.3985f,-1.7553f,1.3457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7999f,0.0145f,1.9155f,0f,0.0145f,-1.7999f,1.5508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.4772f,-1.0285f,1.1769f,0f,-1.0285f,-1.4772f,1.7922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.8f,0.0048f,1.44f,0f,0.0048f,-1.8f,1.321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7968f,0.1069f,1.9155f,0f,0.1069f,-1.7968f,1.5508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.5674f,-0.885f,1.7013f,0f,-0.885f,-1.5674f,1.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7984f,-0.0769f,0.8166f,0f,-0.0769f,-1.7984f,-0.3331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5811f,0.8603f,0.959f,0f,0.8603f,-1.5811f,0.2688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6185f,-0.7877f,1.6182f,0f,-0.7877f,-1.6185f,0.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7999f,-0.0141f,0.8367f,0f,-0.0141f,-1.7999f,-0.3676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5421f,0.9284f,0.9528f,0f,0.9284f,-1.5421f,0.2399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6513f,-0.7163f,1.6182f,0f,-0.7163f,-1.6513f,0.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7957f,-0.124f,0.7141f,0f,-0.124f,-1.7957f,-2.3258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6866f,-0.6289f,1.0678f,0f,-0.6289f,-1.6866f,-1.3771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.4385f,-1.082f,1.7047f,0f,-1.082f,-1.4385f,-0.4836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7993f,0.0487f,1.6461f,0f,0.0487f,-1.7993f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.8595746315,"pz":-0.5840711086,"ry":0,"rx":1.55},"hitbox_body_1":{"px":0,"py":1.093590088,"pz":1.9987992745,"ry":0,"rx":-29.45},"pos_head":{"px":-0.214215128,"py":3.200580403,"pz":2.8656020935,"ry":18.6830436224,"rx":-46.0106452856},"hitbox_head_0":{"px":-0.2753268797,"py":2.7779325904,"pz":3.3071190725,"ry":18.6830436224,"rx":-46.0106452856},"hitbox_tail_0":{"px":0,"py":0.3827164553,"pz":-1.7146957166,"ry":0,"rx":-20.45},"hitbox_tail_1":{"px":0,"py":0.1453016225,"pz":-2.9562935621,"ry":0,"rx":-3.95},"shadow":{"px":0,"py":0.2925,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args