# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^-0.8067367513 ^1.2465744883 ^0.3502643254 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^1.4165069422 ^3.1677528366 ^1.3228181926 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^1.9646598234 ^3.7637227364 ^1.4586084535 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_neck_1
execute positioned ^2.824231749 ^4.4179770873 ^2.9153413368 rotated ~339.0507970455 ~53.0312800899 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_pos_head
$execute as $(hitbox_head_0) positioned ^2.3679865406 ^3.6347662474 ^2.8819408507 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^0.4540917156 ^1.3403768207 ^-1.0866846135 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^0.3133111946 ^-0.7531126301 ^-1.8591756942 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^-0.3231992537 ^0.688734692 ^1.324113519 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^-0.6389591388 ^-0.937512311 ^2.8371451322 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_leg_right_2
execute positioned ^-2.1456024935 ^1.8593645329 ^-0.3769216271 rotated ~271.7887414436 ~-36.5734665538 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_pos_tail_0
execute positioned ^-3.4611491605 ^1.0536757254 ^-0.0887192089 rotated ~245.6875064986 ~-18.7050831424 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^-3.3077915977 ^-0.04902029 ^0.2008700759 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_tail_1
execute positioned ^-5.2488079612 ^1.0607687046 ^0.8288734272 rotated ~241.6101033515 ~8.4992359871 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_pos_tail_2
execute positioned ^-6.1625946145 ^2.075497177 ^2.164736194 rotated ~204.9622836068 ~34.8707695654 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^-6.228240417 ^1.2179554932 ^2.8341354452 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_tail_3
execute positioned ^-6.531869014 ^3.8958337355 ^3.6796365013 rotated ~198.8770810061 ~43.7000916281 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^-6.7359184867 ^2.9173162267 ^4.4380113168 rotated ~180 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_hitbox_tail_4
$execute as $(shadow) positioned ^0 ^1.025 ^0.25 rotated ~0 ~0 run function animated_java_dino:dino/animations/pose/zzz/frames/2_locator_shadow