# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7972f,0.1004f,2.7797f,0f,0.1004f,-1.7972f,2.7755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.796f,0.1199f,2.819f,0f,0.1199f,-1.796f,2.4026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2726f,-1.273f,2.5509f,0f,-1.273f,-1.2726f,2.1971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9669f,-1.5182f,2.1492f,0f,-1.5182f,-0.9669f,2.3106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.518f,-0.9674f,2.0245f,0f,-0.9674f,-1.518f,2.0232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5484f,0.9179f,1.359f,0f,0.9179f,-1.5484f,2.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.6276f,-0.7688f,1.3941f,0f,-0.7688f,-1.6276f,1.4705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.751f,-0.4171f,1.9158f,0f,-0.4171f,-1.751f,1.553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.5484f,0.9179f,1.359f,0f,0.9179f,-1.5484f,2.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6276f,-0.7688f,1.3941f,0f,-0.7688f,-1.6276f,1.4705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.751f,-0.4171f,1.9158f,0f,-0.4171f,-1.751f,1.553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7993f,0.0503f,1.993f,0f,0.0503f,-1.7993f,1.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7989f,0.0639f,0.8736f,0f,0.0639f,-1.7989f,-0.1075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6964f,0.6019f,1.1086f,0f,0.6019f,-1.6964f,0.4646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3172f,-1.2268f,1.693f,0f,-1.2268f,-1.3172f,0.1217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7989f,0.0639f,0.8736f,0f,0.0639f,-1.7989f,-0.1075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6964f,0.6019f,1.1086f,0f,0.6019f,-1.6964f,0.4646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3172f,-1.2268f,1.693f,0f,-1.2268f,-1.3172f,0.1217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7961f,-0.0469f,0.1088f,0.1147f,-0.0508f,1.7982f,-0.0635f,0.7839f,-0.107f,-0.0664f,-1.7956f,-2.4023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7961f,-0.0069f,0.1183f,0.0482f,-0.0508f,1.668f,-0.6747f,1.1634f,-0.107f,-0.6765f,-1.6646f,-1.466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7983f,0f,0.0791f,0f,-0.036f,1.6027f,-0.8185f,1.6372f,-0.0704f,-0.8193f,-1.6012f,-0.4775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7604f,-0.3753f,1.7473f,0f,-0.3753f,-1.7604f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.792114934,"pz":-0.3766196497,"ry":0,"rx":-12.034912},"hitbox_body_1":{"px":0,"py":0.9805432784,"pz":1.5128348623,"ry":0,"rx":1.60218175},"pos_head":{"px":0,"py":2.795387564,"pz":2.7987620851,"ry":0,"rx":3.81780675},"hitbox_head_0":{"px":0,"py":2.1825006935,"pz":2.7578628629,"ry":0,"rx":3.81780675},"hitbox_tail_0":{"px":0.0867022521,"py":0.4696184922,"pz":-1.7829487111,"ry":4.0640648189,"rx":-22.0124572888},"hitbox_tail_1":{"px":0.1687543402,"py":0.2369481327,"pz":-3.0495474292,"ry":3.4670119745,"rx":-2.0208860272}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args