# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7964f,0.1139f,2.7526f,0f,0.1139f,-1.7964f,2.773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7927f,0.1618f,2.8007f,0f,0.1618f,-1.7927f,2.4011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2664f,-1.2792f,2.5315f,0f,-1.2792f,-1.2664f,2.1969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9595f,-1.5229f,2.1304f,0f,-1.5229f,-0.9595f,2.3123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5132f,-0.9748f,2.0043f,0f,-0.9748f,-1.5132f,2.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5008f,0.9938f,1.3f,0f,0.9938f,-1.5008f,1.9979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.6877f,-0.6259f,1.3814f,0f,-0.6259f,-1.6877f,1.4644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7565f,-0.3935f,1.9019f,0f,-0.3935f,-1.7565f,1.5539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.5008f,0.9938f,1.3f,0f,0.9938f,-1.5008f,1.9979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6877f,-0.6259f,1.3814f,0f,-0.6259f,-1.6877f,1.4644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7565f,-0.3935f,1.9019f,0f,-0.3935f,-1.7565f,1.5539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7985f,0.0745f,1.9864f,0f,0.0745f,-1.7985f,1.0115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7993f,0.0488f,0.8726f,0f,0.0488f,-1.7993f,-0.101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7014f,0.5876f,1.1124f,0f,0.5876f,-1.7014f,0.4691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3068f,-1.2379f,1.6939f,0f,-1.2379f,-1.3068f,0.1212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7993f,0.0488f,0.8726f,0f,0.0488f,-1.7993f,-0.101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7014f,0.5876f,1.1124f,0f,0.5876f,-1.7014f,0.4691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3068f,-1.2379f,1.6939f,0f,-1.2379f,-1.3068f,0.1212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7992f,0.0208f,-0.0483f,-0.0509f,0.0222f,1.7992f,-0.0499f,0.8046f,0.0477f,-0.0505f,-1.7987f,-2.4126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7992f,0.003f,-0.0525f,-0.0214f,0.0222f,1.6736f,-0.6623f,1.1772f,0.0477f,-0.6626f,-1.6729f,-1.4715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7997f,0f,-0.0351f,0f,0.0157f,1.6094f,-0.8059f,1.6431f,0.0314f,-0.8061f,-1.6091f,-0.4784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7635f,-0.3605f,1.7473f,0f,-0.3605f,-1.7635f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7972433318,"pz":-0.3846483665,"ry":0,"rx":-11.552032},"hitbox_body_1":{"px":0,"py":0.9672826613,"pz":1.5012437755,"ry":0,"rx":2.37118675},"pos_head":{"px":0,"py":2.7677607436,"pz":2.7965926076,"ry":0,"rx":5.1585305},"hitbox_head_0":{"px":0,"py":2.1559986185,"pz":2.7413643115,"ry":0,"rx":5.1585305},"hitbox_tail_0":{"px":-0.0384647504,"py":0.4855390808,"pz":-1.7950939007,"ry":358.203201623,"rx":-21.5880117955},"hitbox_tail_1":{"px":-0.0748740985,"py":0.2623683923,"pz":-3.0655306591,"ry":358.4626728881,"rx":-1.5896085476}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args