# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7982f,0.0802f,2.8233f,0f,0.0802f,-1.7982f,2.7717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7981f,0.0824f,2.8548f,0f,0.0824f,-1.7981f,2.398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2705f,-1.2751f,2.5864f,0f,-1.2751f,-1.2705f,2.1929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9644f,-1.5199f,2.1849f,0f,-1.5199f,-0.9644f,2.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5163f,-0.9699f,2.0596f,0f,-0.9699f,-1.5163f,2.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.596f,0.8324f,1.4216f,0f,0.8324f,-1.596f,2.0251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.561f,-0.8963f,1.4137f,0f,-0.8963f,-1.561f,1.4856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7383f,-0.4673f,1.9375f,0f,-0.4673f,-1.7383f,1.553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.596f,0.8324f,1.4216f,0f,0.8324f,-1.596f,2.0251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.561f,-0.8963f,1.4137f,0f,-0.8963f,-1.561f,1.4856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7383f,-0.4673f,1.9375f,0f,-0.4673f,-1.7383f,1.553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,-0.0014f,1.9991f,0f,-0.0014f,-1.8f,1.0075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0778f,0.8746f,0f,0.0778f,-1.7983f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6917f,0.615f,1.1051f,0f,0.615f,-1.6917f,0.4605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3266f,-1.2166f,1.6922f,0f,-1.2166f,-1.3266f,0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7983f,0.0778f,0.8746f,0f,0.0778f,-1.7983f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6917f,0.615f,1.1051f,0f,0.615f,-1.6917f,0.4605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.3266f,-1.2166f,1.6922f,0f,-1.2166f,-1.3266f,0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7863f,-0.0878f,0.2035f,0.2147f,-0.0965f,1.796f,-0.0723f,0.7684f,-0.1996f,-0.0826f,-1.787f,-2.388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7863f,-0.0129f,0.2213f,0.0903f,-0.0965f,1.6629f,-0.6822f,1.1522f,-0.1996f,-0.6888f,-1.651f,-1.4594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7939f,0f,0.1481f,0f,-0.0684f,1.5968f,-0.8279f,1.6317f,-0.1314f,-0.8307f,-1.5914f,-0.4766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7575f,-0.3889f,1.7473f,0f,-0.3889f,-1.7575f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7874623649,"pz":-0.3692043688,"ry":0,"rx":-12.4786200194},"hitbox_body_1":{"px":0,"py":1.0014872381,"pz":1.5398236155,"ry":0,"rx":-0.0461200194},"pos_head":{"px":0,"py":2.8394685219,"pz":2.7945825924,"ry":0,"rx":2.6251299806},"hitbox_head_0":{"px":0,"py":2.2258631296,"pz":2.7664492464,"ry":0,"rx":2.6251299806},"hitbox_tail_0":{"px":0.1623333751,"py":0.4575065106,"pz":-1.7685187478,"ry":7.634600866,"rx":-22.27059527},"hitbox_tail_1":{"px":0.3158596948,"py":0.2188273115,"pz":-3.0273286076,"ry":6.4980572891,"rx":-2.3010919463}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args