# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @s run function animated_java_ranposu:ranposu/zzz/set_default_pose/as_locator_hitbox_body_0 with storage animated_java:temp entry.data.locators.hitbox_body_0
execute at @s run function animated_java_ranposu:ranposu/zzz/set_default_pose/as_locator_hitbox_body_1 with storage animated_java:temp entry.data.locators.hitbox_body_1
data modify storage animated_java:temp entry.data.locators.pos_head merge value { px: 0, py: 1.3125, pz: 1.875, ry: 0, rx: 0 }
execute at @s run function animated_java_ranposu:ranposu/zzz/set_default_pose/as_locator_hitbox_head_0 with storage animated_java:temp entry.data.locators.hitbox_head_0
execute at @s run function animated_java_ranposu:ranposu/zzz/set_default_pose/as_locator_hitbox_tail_0 with storage animated_java:temp entry.data.locators.hitbox_tail_0
execute at @s run function animated_java_ranposu:ranposu/zzz/set_default_pose/as_locator_hitbox_tail_1 with storage animated_java:temp entry.data.locators.hitbox_tail_1
execute at @s run function animated_java_ranposu:ranposu/zzz/set_default_pose/as_locator_shadow with storage animated_java:temp entry.data.locators.shadow