# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,0.2349f,1.7846f,6.2992f,0f,1.7846f,-0.2349f,3.1326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.6914f,0.6156f,6.4409f,0f,0.6156f,-1.6914f,2.7854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,6.4555f,0f,0.3126f,-1.7727f,2.4479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,6.144f,0f,0f,-1.8f,2.1701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7167f,-0.5413f,6.0979f,0f,-0.5413f,-1.7167f,1.8602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7167f,-0.5086f,0.1851f,0.6148f,0.0472f,-0.7539f,-1.6338f,5.7494f,0.5392f,-1.5534f,0.7323f,2.0571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7167f,-0.5228f,-0.1401f,0.5047f,0.0472f,0.3196f,-1.7708f,5.3316f,0.5392f,-1.6925f,-0.2911f,1.7338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7167f,-0.3991f,-0.3657f,0.4078f,0.0472f,1.1011f,-1.4231f,5.7901f,0.5392f,-1.3668f,-1.0397f,1.4884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7387f,0.3929f,-0.2503f,-0.5914f,-0.0406f,-1.0913f,-1.4309f,5.8819f,-0.4641f,-1.3765f,1.0629f,2.0592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7387f,0.4654f,0.0203f,-0.5211f,-0.0406f,-0.0732f,-1.7981f,5.3998f,-0.4641f,-1.7372f,0.0812f,1.8271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.4035f,0.2329f,-0.4078f,-0.0406f,0.7653f,-1.6287f,5.7901f,-0.4641f,-1.5784f,-0.7302f,1.4884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6314f,-0.7607f,5.6158f,0f,-0.7607f,-1.6314f,0.9679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.3789f,-1.157f,4.5502f,0f,-1.157f,-1.3789f,0.3818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7846f,-0.2349f,5.0196f,0f,-0.2349f,-1.7846f,0.7846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.0785f,-1.7983f,5.1957f,0f,-1.7983f,-0.0785f,0.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.4745f,-1.0324f,4.0118f,0f,-1.0324f,-1.4745f,0.1213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.663f,-0.6888f,4.5694f,0f,-0.6888f,-1.663f,0.3889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.4745f,-1.0324f,5.1957f,0f,-1.0324f,-1.4745f,0.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.2161f,-1.3271f,4.113f,0f,-1.3271f,-1.2161f,-2.3383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5588f,-0.9f,4.6193f,0f,-0.9f,-1.5588f,-1.4614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6314f,-0.7607f,5.0574f,0f,-0.7607f,-1.6314f,-0.4554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,-0.6156f,5.2642f,0f,-0.6156f,-1.6914f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":4.2344377291,"pz":-0.2384261802,"ry":0,"rx":-20},"hitbox_body_1":{"px":0,"py":4.9359471828,"pz":1.8713373243,"ry":0,"rx":-25},"pos_head":{"px":0,"py":6.3077851192,"pz":3.1593392892,"ry":0,"rx":20},"hitbox_head_0":{"px":0,"py":5.7305789269,"pz":2.9492534162,"ry":0,"rx":20},"hitbox_tail_0":{"px":0,"py":3.8876911405,"pz":-1.6806582303,"ry":0,"rx":-30},"hitbox_tail_1":{"px":0,"py":3.2664302697,"pz":-2.40336672,"ry":0,"rx":-47.5},"shadow":{"px":0,"py":3.9106214416,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args