# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.4367f,1.0844f,1.2975f,0f,1.0844f,-1.4367f,3.295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.388f,1.146f,1.5472f,0f,1.146f,-1.388f,3.0152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.5659f,0.8876f,1.6738f,0f,0.8876f,-1.5659f,2.702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6963f,0.6022f,1.4732f,0f,0.6022f,-1.6963f,2.336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7714f,0.3196f,1.5766f,0f,0.3196f,-1.7714f,2.0402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7448f,0.1527f,0.4151f,0.3945f,-0.1447f,1.3994f,-1.1228f,0.7044f,-0.418f,-1.1217f,-1.3443f,2.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7448f,-0.113f,0.4276f,0.4929f,-0.1447f,1.7904f,-0.117f,0.9343f,-0.418f,-0.1478f,-1.7445f,1.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7448f,-0.021f,0.4418f,0.4078f,-0.1447f,1.7262f,-0.4892f,1.4548f,-0.418f,-0.5097f,-1.6749f,1.5732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7927f,0.0591f,-0.1508f,-0.4464f,0.1239f,1.5799f,-0.8536f,0.6806f,0.1044f,-0.8605f,-1.5775f,1.9339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7927f,0.1233f,-0.1051f,-0.4588f,0.1239f,1.7957f,-0.0063f,0.9403f,0.1044f,-0.0135f,-1.7969f,1.4611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.2417f,0.3983f,-0.4078f,0.1593f,1.7545f,-0.3691f,1.4548f,-0.4378f,-0.3213f,-1.7161f,1.5732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.5168f,0f,0f,-1.8f,1.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7979f,0.0868f,0.821f,0f,0.0868f,-1.7979f,0.0726f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.5175f,0.9681f,0.9212f,0f,0.9681f,-1.5175f,0.6829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.6413f,-1.6819f,1.2946f,0f,-1.6819f,-0.6413f,0.1174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7086f,0.5662f,0.9623f,0f,0.5662f,-1.7086f,-0.4995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,0.4659f,1.7387f,0.6242f,0f,1.7387f,-0.4659f,0.0185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7952f,-0.1308f,1.2946f,0f,-0.1308f,-1.7952f,0.1174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.3446f,1.1966f,1.8369f,0f,1.1966f,-1.3446f,-2.4825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6085f,0.8078f,1.3825f,0f,0.8078f,-1.6085f,-1.5777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.797f,0.1047f,1.2907f,0f,0.1047f,-1.797f,-0.4844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7863f,-0.222f,1.3395f,0f,-0.222f,-1.7863f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.4400429428,"pz":-0.4568106716,"ry":0,"rx":-7.0833333333},"hitbox_body_1":{"px":0,"py":0.5188240846,"pz":1.5592376996,"ry":0,"rx":0},"pos_head":{"px":0,"py":1.2966355362,"pz":3.3229999578,"ry":0,"rx":39.5454545455},"hitbox_head_0":{"px":0,"py":0.8229752484,"pz":2.9319130183,"ry":0,"rx":39.5454545455},"hitbox_tail_0":{"px":0,"py":1.1636625736,"pz":-2.3094723933,"ry":0,"rx":26.6666666667},"hitbox_tail_1":{"px":0,"py":1.8897031833,"pz":-3.3300250045,"ry":0,"rx":41.6666666667},"shadow":{"px":0,"py":-0.0140625,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args