# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^-0.3932 ^1.8158 ^-1.9963 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^1.0616 ^1.1057 ^0.6403 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^1.7151 ^1.0014 ^1.0855 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_neck_1
execute positioned ^2.1823 ^1.4975 ^2.6076 rotated ~348.1493 ~45.128 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_pos_head
$execute as $(hitbox_head_0) positioned ^1.7529 ^0.7064 ^2.4715 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^1.7917 ^0.6228 ^-1.2598 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^2.2088 ^-0.7956 ^-2.8348 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^-0.4022 ^1.1269 ^0.1031 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^-1.4859 ^-0.5266 ^0.0941 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_leg_right_2
execute positioned ^-0.6585 ^4.3331 ^-3.7394 rotated ~335.064 ~40.0998 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_pos_tail_0
execute positioned ^-1.1244 ^5.4772 ^-4.7545 rotated ~335.7771 ~56.7463 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^-1.2604 ^3.9798 ^-4.1783 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_tail_1
execute positioned ^-1.4924 ^7.2407 ^-5.6209 rotated ~337.6163 ~62.3032 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_pos_tail_2
execute positioned ^-1.9657 ^9.0706 ^-6.1215 rotated ~311.2964 ~67.4939 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^-2.2757 ^8.3358 ^-5.7218 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_tail_3
execute positioned ^-2.3192 ^11.4417 ^-6.0276 rotated ~286.8126 ~77.9524 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^-2.7114 ^10.6826 ^-5.7825 rotated ~180 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_hitbox_tail_4
$execute as $(shadow) positioned ^0.346 ^0.8219 ^-1.5976 rotated ~335 ~0 run function animated_java_dino:dino/animations/step_l_to_jumptail_r/zzz/frames/38_locator_shadow