# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7018f,0.5864f,0.6969f,0f,0.5864f,-1.7018f,3.2477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.6719f,0.6668f,0.8491f,0f,0.6668f,-1.6719f,2.9049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.3145f,1.2297f,1.0456f,0f,1.2297f,-1.3145f,2.6302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.305f,1.2397f,1.0112f,0f,1.2397f,-1.305f,2.2142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.3778f,1.1583f,1.2479f,0f,1.1583f,-1.3778f,2.009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7356f,0.4691f,0.0866f,0.3812f,0.0013f,0.3315f,-1.7692f,0.4443f,-0.4771f,-1.7059f,-0.32f,1.7281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7356f,-0.0962f,0.4673f,0.4925f,0.0013f,1.7621f,0.3676f,0.7969f,-0.4771f,0.3548f,-1.699f,1.3351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7356f,-0.0056f,0.477f,0.4078f,0.0013f,1.7998f,0.0258f,1.2824f,-0.4771f,0.0252f,-1.7354f,1.5276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7977f,-0.0891f,-0.0155f,-0.3968f,-0.0356f,0.9806f,-1.509f,0.5158f,0.0831f,-1.5068f,-0.9812f,1.5289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7977f,-0.0093f,-0.0899f,-0.4246f,-0.0356f,1.7188f,0.5333f,0.9055f,0.0831f,0.5344f,-1.7168f,1.1567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7314f,0.1456f,0.47f,-0.4078f,0.3074f,1.6627f,0.6172f,1.2824f,-0.3843f,0.674f,-1.6242f,1.5276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7049f,0.5774f,1.5161f,0f,0.5774f,-1.7049f,1.0309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.8f,0.0031f,0.9109f,0f,0.0031f,-1.8f,0.0557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.3684f,1.1693f,0.9255f,0f,1.1693f,-1.3684f,0.674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.6767f,-1.668f,1.3107f,0f,-1.668f,-0.6767f,0.1166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7985f,0.0745f,0.8131f,0f,0.0745f,-1.7985f,-0.3877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,0.9479f,1.5302f,0.639f,0f,1.5302f,-0.9479f,0.2058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6901f,-0.6194f,1.3107f,0f,-0.6194f,-1.6901f,0.1166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5392f,0.9332f,1.5291f,0f,0.9332f,-1.5392f,-2.5623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7434f,0.4478f,1.2772f,0f,0.4478f,-1.7434f,-1.5816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7965f,-0.1128f,1.3179f,0f,-0.1128f,-1.7965f,-0.4851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7901f,-0.1889f,1.3536f,0f,-0.1889f,-1.7901f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.4669136507,"pz":-0.4733179536,"ry":0,"rx":-6.0243055556},"hitbox_body_1":{"px":0,"py":0.4003188837,"pz":1.214161359,"ry":0,"rx":18.7094907407},"pos_head":{"px":0,"py":0.7047272316,"pz":3.2746429066,"ry":0,"rx":21.7429242494},"hitbox_head_0":{"px":0,"py":0.1341778588,"pz":3.0470984589,"ry":0,"rx":21.7429242494},"hitbox_tail_0":{"px":0,"py":0.907936231,"pz":-2.2501731263,"ry":0,"rx":14.4039351852},"hitbox_tail_1":{"px":0,"py":1.4274165613,"pz":-3.4053083676,"ry":0,"rx":31.2268518519},"shadow":{"px":0,"py":0,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args