# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.reus_aj.root] run return 0
execute on passengers if entity @s[tag=aj.reus_aj.data] unless data entity @s {data:{rigHash: '6660fde796c8f1bc79837202473a8101da9b684487a58ad927e215fdce563606'}} on vehicle run function animated_java:reus_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1