# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "animated_java_nikuyaki:nikuyaki"
data modify storage animated_java:temp entry.data.rig_hash set value "0c417a376eecdd1482741563eeab9d92205f6d2ff24f12569e477147d48616e1"
tp @s ~ ~ ~ ~ ~
summon minecraft:area_effect_cloud ^0 ^0.265625 ^-1.4375 {Tags:["","aj.global.bone.chair1.child","aj.global.bone.chair1.child.locator","aj.global.bone.chair1.decendant","aj.global.bone.chair1.decendant.locator","aj.global.bone.chair1.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.chair","aj.new","animated_java_nikuyaki.nikuyaki.bone.chair1.child","animated_java_nikuyaki.nikuyaki.bone.chair1.child.locator","animated_java_nikuyaki.nikuyaki.bone.chair1.decendant","animated_java_nikuyaki.nikuyaki.bone.chair1.decendant.locator","animated_java_nikuyaki.nikuyaki.bone.chair1.tree","animated_java_nikuyaki.nikuyaki.bone.root.decendant","animated_java_nikuyaki.nikuyaki.bone.root.decendant.locator","animated_java_nikuyaki.nikuyaki.bone.root.tree","animated_java_nikuyaki.nikuyaki.entity","animated_java_nikuyaki.nikuyaki.locator","animated_java_nikuyaki.nikuyaki.locator.chair","animated_java_nikuyaki.nikuyaki.node","animated_java_nikuyaki.nikuyaki.node.chair"]}
execute as @n[ type=minecraft:area_effect_cloud, tag=animated_java_nikuyaki.nikuyaki.locator.chair, tag=aj.new, distance=..3 ] run function animated_java_nikuyaki:nikuyaki/zzz/summon/as_locator/chair
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.chair set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.chair.uuid set from storage animated_java:gu out
summon minecraft:interaction ^0 ^0.40625 ^0 {Tags:["","aj.global.bone.root.child","aj.global.bone.root.child.locator","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.interaction","aj.new","animated_java_nikuyaki.nikuyaki.bone.root.child","animated_java_nikuyaki.nikuyaki.bone.root.child.locator","animated_java_nikuyaki.nikuyaki.bone.root.decendant","animated_java_nikuyaki.nikuyaki.bone.root.decendant.locator","animated_java_nikuyaki.nikuyaki.bone.root.tree","animated_java_nikuyaki.nikuyaki.entity","animated_java_nikuyaki.nikuyaki.locator","animated_java_nikuyaki.nikuyaki.locator.interaction","animated_java_nikuyaki.nikuyaki.node","animated_java_nikuyaki.nikuyaki.node.interaction"]}
execute as @n[ type=minecraft:interaction, tag=animated_java_nikuyaki.nikuyaki.locator.interaction, tag=aj.new, distance=..2 ] run function animated_java_nikuyaki:nikuyaki/zzz/summon/as_locator/interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.interaction.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java_nikuyaki.nikuyaki.node.meat] run function animated_java_nikuyaki:nikuyaki/zzz/summon/as_node/meat
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.meat set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java_nikuyaki.nikuyaki.node.chair1] run function animated_java_nikuyaki:nikuyaki/zzz/summon/as_node/chair1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.chair1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java_nikuyaki.nikuyaki.node.base] run function animated_java_nikuyaki:nikuyaki/zzz/summon/as_node/base
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.base set from storage animated_java:gu out
function animated_java_nikuyaki:nikuyaki/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.chair
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function animated_java_nikuyaki:nikuyaki/zzz/summon/zzz/1 with storage animated_java:temp entry.data.locators.interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function animated_java_nikuyaki:nikuyaki/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function animated_java_nikuyaki:nikuyaki/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function animated_java_nikuyaki:nikuyaki/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function animated_java_nikuyaki:nikuyaki/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function animated_java_nikuyaki:nikuyaki/zzz/summon/zzz/2 with storage animated_java:temp entry.data.locators.chair
function animated_java_nikuyaki:nikuyaki/zzz/summon/zzz/3 with storage animated_java:temp entry.data.locators.interaction
execute at @s run function animated_java_nikuyaki:nikuyaki/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new