# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.6144f,0.7961f,4.496f,0f,0.7961f,-1.6144f,3.3184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.6144f,0.7961f,4.6746f,0f,0.7961f,-1.6144f,2.9887f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7045f,0.5786f,4.7404f,0f,0.5786f,-1.7045f,2.6574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7045f,0.5786f,4.5347f,0f,0.5786f,-1.7045f,2.2942f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7996f,0.0393f,4.5907f,0f,0.0393f,-1.7996f,1.9859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.3126f,-1.7727f,3.6688f,0f,-1.7727f,-0.3126f,1.7154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7932f,0.1569f,3.9707f,0f,0.1569f,-1.7932f,1.2681f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7846f,0.2349f,4.4287f,0f,0.2349f,-1.7846f,1.5313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.6156f,-1.6914f,3.5874f,0f,-1.6914f,-0.6156f,1.6479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7281f,0.5037f,3.9707f,0f,0.5037f,-1.7281f,1.2681f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7846f,0.2349f,4.4287f,0f,0.2349f,-1.7846f,1.5313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,-0.1569f,4.4429f,0f,-0.1569f,-1.7932f,0.9825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.6144f,-0.7961f,2.8914f,0f,-0.7961f,-1.6144f,0.2221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6144f,-0.7961f,3.4653f,0f,-0.7961f,-1.6144f,0.4526f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3533f,-1.1868f,4.0597f,0f,-1.1868f,-1.3533f,0.1273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.5388f,-0.9338f,2.896f,0f,-0.9338f,-1.5388f,0.3112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5388f,-0.9338f,3.4878f,0f,-0.9338f,-1.5388f,0.4908f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.2728f,-1.2728f,4.0597f,0f,-1.2728f,-1.2728f,0.1273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.157f,-1.3789f,2.6176f,0f,-1.3789f,-1.157f,-2.0976f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.3271f,-1.2161f,3.3016f,0f,-1.2161f,-1.3271f,-1.3511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.428f,-1.0958f,3.9471f,0f,-1.0958f,-1.428f,-0.4638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7167f,-0.5413f,4.1239f,0f,-0.5413f,-1.7167f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":3.1154483794,"pz":-0.2828993842,"ry":0,"rx":-17.5},"hitbox_body_1":{"px":0,"py":3.4950173177,"pz":1.5989526248,"ry":0,"rx":-5},"pos_head":{"px":0,"py":4.5016076246,"pz":3.3459248734,"ry":0,"rx":26.25},"hitbox_head_0":{"px":0,"py":3.9507035431,"pz":3.0742490454,"ry":0,"rx":26.25},"hitbox_tail_0":{"px":0,"py":2.539919828,"pz":-1.4068215635,"ry":0,"rx":-42.5},"hitbox_tail_1":{"px":0,"py":1.768951182,"pz":-2.1257276304,"ry":0,"rx":-50},"shadow":{"px":0,"py":2.7703125,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args