# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.3437 ^0.5759 ~0 ~12.5
data modify storage animated_java:temp entry.data.locators.hitbox_neck_1 merge value { px: 0, py: 0.3437, pz: 0.5759, ry: 0, rx: 12.5 }