# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.2584 ^-0.1417 ^0.0341 ~9.8454 ~-18.5868
data modify storage animated_java:temp entry.data.locators.hitbox_leg_right_2 merge value { px: -0.2584, py: -0.1417, pz: 0.0341, ry: 9.8454, rx: -18.5868 }