# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0.1724 ^0.3931 ^-0.2181 ~38.3752 ~58.0361
data modify storage animated_java:temp entry.data.locators.hitbox_leg_left_1 merge value { px: 0.1724, py: 0.3931, pz: -0.2181, ry: 38.3752, rx: 58.0361 }