# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.3815949716 ^0.2386494203 ~0 ~5
data modify storage animated_java:temp entry.data.locators.hitbox_body_0 merge value { px: 0, py: 0.3815949716, pz: 0.2386494203, ry: 0, rx: 5 }