# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.1724131458 ^0.3930821412 ^-0.2181240362 ~321.6248255436 ~58.0360879442
data modify storage animated_java:temp entry.data.locators.hitbox_leg_right_1 merge value { px: -0.1724131458, py: 0.3930821412, pz: -0.2181240362, ry: 321.6248255436, rx: 58.0360879442 }