# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.head_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.head_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.neck_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.neck_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.neck_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.arm_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.arm_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.arm_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.arm_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_1_fire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_1_fire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_1_fire_s] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_1_fire_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_2_fire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_2_fire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_2_fire_s] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_2_fire_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_film_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_film_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_0_fire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_0_fire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_0_fire_s] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_0_fire_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.fire_large_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_fire_large_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.wing_right_1_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_1_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.wing_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_1_fire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_1_fire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_1_fire_s] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_1_fire_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_2_fire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_2_fire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_2_fire_s] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_2_fire_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_film_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_film_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_0_fire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_0_fire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_0_fire_s] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_0_fire_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.fire_large_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_fire_large_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.finger_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.wing_left_1_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_1_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.wing_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_right_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_left_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.tail_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.tail_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.tail_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.tail_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.valk_aj.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out