# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.damage_counter_start.frame matches 36.. run scoreboard players set @s aj.damage_counter_start.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.damage_counter_start.frame
execute at @s run function animated_java:ranposu/animations/damage_counter_start/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.damage_counter_start.frame 1