# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.4925f,-1.0062f,0.0008f,-0.0072f,-1.0061f,1.4925f,0.0065f,1.2615f,-0.0043f,0.0049f,-1.8f,4.6319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.4925f,-1.0052f,-0.0431f,-0.0241f,-1.0061f,1.4908f,0.0716f,1.2884f,-0.0043f,0.0835f,-1.7981f,4.2582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.7204f,-0.5293f,-0.0073f,-0.0126f,-0.5205f,1.6871f,0.3505f,1.3121f,-0.0962f,0.3371f,-1.7655f,3.9214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.7933f,-0.1454f,-0.0535f,0.0043f,-0.1497f,1.465f,1.0351f,1.2183f,-0.0401f,1.0357f,-1.4717f,3.515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.7933f,-0.155f,-0.0005f,0f,-0.1497f,1.7307f,0.4716f,1.3467f,-0.0401f,0.4699f,-1.7371f,3.2293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9671f,-1.5181f,0.8099f,0f,-1.5181f,-0.9671f,2.522f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.5588f,0.9f,1.2726f,0f,0.9f,-1.5588f,2.2443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,0.4659f,1.7387f,1.2047f,0f,1.7387f,-0.4659f,2.768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,-0.0012f,-1.8f,0.8874f,0f,-1.8f,0.0012f,3.0474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.2586f,-1.2868f,0.733f,0f,-1.2868f,-1.2586f,2.5303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7948f,0.137f,1.2047f,0f,0.137f,-1.7948f,2.768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,-0.0785f,1.2428f,0f,-0.0785f,-1.7983f,2.2204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.7983f,0.0778f,-0.0102f,0.4168f,0.0749f,1.771f,0.3128f,0.892f,0.0236f,0.3121f,-1.7726f,0.4135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.3271f,1.2161f,0.8852f,0f,1.2161f,-1.3271f,1.032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.7573f,0.3896f,1.499f,0f,0.3896f,-1.7573f,1.319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.833f,0f,0f,-1.8f,1.3802f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7727f,0.3126f,1.1595f,0f,0.3126f,-1.7727f,1.9054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.5413f,-1.7167f,1.499f,0f,-1.7167f,-0.5413f,1.319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.7188f,-0.0568f,0.5314f,-0.0052f,-0.0784f,1.7972f,-0.0614f,2.2728f,-0.5286f,-0.0818f,-1.7187f,-1.2467f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.7928f,-0.0124f,0.1608f,-0.0956f,0.0127f,1.7781f,0.2795f,2.1155f,-0.1607f,0.2795f,-1.7709f,-0.2505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.7932f,-0.0049f,-0.1568f,0f,-0.0472f,1.7327f,0.4855f,1.7926f,0.1496f,0.4877f,-1.7262f,0.7937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.663f,0.6888f,1.4835f,0f,0.6888f,-1.663f,1.4372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0393,"pz":0.3978,"ry":0,"rx":22.5},"hitbox_body_1":{"px":0,"py":0.269,"pz":2.7949,"ry":0,"rx":-2.5},"pos_head":{"px":-0.0163,"py":1.2748,"pz":4.6548,"ry":358.6283,"rx":2.2804},"hitbox_head_0":{"px":0.3267,"py":0.7661,"pz":4.6263,"ry":358.6283,"rx":2.2804},"hitbox_tail_0":{"px":-0.0424,"py":1.6842,"pz":-0.8786,"ry":5.1871,"rx":8.9338},"hitbox_tail_1":{"px":0.2086,"py":1.7268,"pz":-1.8608,"ry":17.1812,"rx":-1.9557},"shadow":{"px":0,"py":0.1299,"pz":0.9844,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args