# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.nikuyaki.root] run return 0
execute if entity @s[tag=aj.nikuyaki.animation.baking.playing] run function animated_java:nikuyaki/animations/baking/zzz/on_tick
execute on passengers if entity @s[tag=aj.nikuyaki.data] run function animated_java:nikuyaki/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~