# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_0) positioned ^0 ^1.4244 ^-0.7447 rotated ~0 ~15 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_hitbox_body_0
$execute as $(hitbox_body_1) positioned ^0 ^0.8052 ^1.4324 rotated ~0 ~7.5 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_hitbox_body_1
execute positioned ^0 ^1.8805 ^3.4107 rotated ~0 ~2.5 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_pos_head
$execute as $(hitbox_head_0) positioned ^0 ^1.2669 ^3.3839 rotated ~0 ~2.5 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_hitbox_head_0
$execute as $(hitbox_tail_0) positioned ^0 ^1.9401 ^-2.0476 rotated ~0 ~-2.5 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_hitbox_tail_0
$execute as $(hitbox_tail_1) positioned ^0 ^1.8116 ^-3.0938 rotated ~0 ~-10 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_hitbox_tail_1
$execute as $(shadow) positioned ^0 ^0.6469 ^-0.225 rotated ~0 ~0 run function animated_java_ranposu:ranposu/animations/move/zzz/frames/13_locator_shadow