# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java_nikuyaki:nikuyaki rig_hash set value '0db68cfc7e6c5f4542ebfc87a78ab4909d4278c78ad2ca84c84b306941cf1e69'
scoreboard objectives add aj.baking.frame dummy