# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ranposu_aj.root] run return 0
execute on passengers if entity @s[tag=aj.ranposu_aj.data] unless data entity @s {data:{rigHash: '831a4766874cfd020b781765f2dc5139bb37fa2c38d7806c003cb71e0c7b351b'}} on vehicle run function animated_java:ranposu_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1