# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7945f,0.1412f,1.3804f,0f,0.1412f,-1.7945f,3.0596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7945f,0.1412f,1.4241f,0f,0.1412f,-1.7945f,2.6872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7997f,0.0314f,1.3857f,0f,0.0314f,-1.7997f,2.3515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7607f,0.3742f,1.1388f,0f,0.3742f,-1.7607f,2.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5893f,0.845f,1.3275f,0f,0.845f,-1.5893f,1.765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9271f,-1.5429f,0.7803f,0f,-1.5429f,-0.9271f,1.4966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.6444f,-0.7321f,0.8275f,0f,-0.7321f,-1.6444f,0.959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7259f,0.5112f,1.2386f,0f,0.5112f,-1.7259f,1.2906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.8727f,-1.5743f,0.7991f,0f,-1.5743f,-0.8727f,1.4979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6178f,-0.7891f,0.8275f,0f,-0.7891f,-1.6178f,0.959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7259f,0.5112f,1.2386f,0f,0.5112f,-1.7259f,1.2906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7956f,0.1256f,1.3385f,0f,0.1256f,-1.7956f,0.7508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.8809f,0f,0.0785f,-1.7983f,-0.5077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4375f,1.0833f,0.9334f,0f,1.0833f,-1.4375f,0.1086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.4562f,-1.058f,1.5551f,0f,-1.058f,-1.4562f,-0.1609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7945f,0.1412f,0.8993f,0f,0.1412f,-1.7945f,-0.5763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.3585f,1.1809f,0.9086f,0f,1.1809f,-1.3585f,0.0421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.5588f,-0.9f,1.5551f,0f,-0.9f,-1.5588f,-0.1609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.3057f,1.239f,2.4703f,0f,1.239f,-1.3057f,-2.6896f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6247f,0.7749f,2.0344f,0f,0.7749f,-1.6247f,-1.7757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7753f,0.2971f,1.8256f,0f,0.2971f,-1.7753f,-0.6985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,0.6156f,1.5448f,0f,0.6156f,-1.6914f,-0.0421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.0557103538,"pz":-1.061243684,"ry":0,"rx":20},"hitbox_body_1":{"px":0,"py":0.3058808908,"pz":1.2113523707,"ry":0,"rx":4},"pos_head":{"px":0,"py":1.3957967944,"pz":3.0830551892,"ry":0,"rx":4.5},"hitbox_head_0":{"px":0,"py":0.7834403222,"pz":3.0348616896,"ry":0,"rx":4.5},"hitbox_tail_0":{"px":0,"py":1.8006675192,"pz":-2.5028105034,"ry":0,"rx":25.5},"hitbox_tail_1":{"px":0,"py":2.5501302437,"pz":-3.5349128387,"ry":0,"rx":43.5},"shadow":{"px":0,"py":0.19125,"pz":-0.495,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args