# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.5588f,0.9f,4.5277f,0f,0.9f,-1.5588f,3.293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.5588f,0.9f,4.7275f,0f,0.9f,-1.5588f,2.9757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,0.6156f,4.8005f,0f,0.6156f,-1.6914f,2.6458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,0.6156f,4.6028f,0f,0.6156f,-1.6914f,2.2782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0785f,4.6655f,0f,0.0785f,-1.7983f,1.9713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.4659f,-1.7387f,3.7838f,0f,-1.7387f,-0.4659f,1.7254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.8f,0f,4.0455f,0f,0f,-1.8f,1.2535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7846f,0.2349f,4.5035f,0f,0.2349f,-1.7846f,1.5166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.5413f,-1.7167f,3.7244f,0f,-1.7167f,-0.5413f,1.6872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7846f,0.2349f,4.0455f,0f,0.2349f,-1.7846f,1.2535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7846f,0.2349f,4.5035f,0f,0.2349f,-1.7846f,1.5166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,-0.1569f,4.5177f,0f,-0.1569f,-1.7932f,0.9679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.6314f,-0.7607f,2.8671f,0f,-0.7607f,-1.6314f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6314f,-0.7607f,3.4359f,0f,-0.7607f,-1.6314f,0.2762f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6314f,-0.7607f,4.0976f,0f,-0.7607f,-1.6314f,0.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.4745f,-1.0324f,2.9757f,0f,-1.0324f,-1.4745f,0.4247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4745f,-1.0324f,3.578f,0f,-1.0324f,-1.4745f,0.5652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.0958f,-1.428f,4.0976f,0f,-1.428f,-1.0958f,0.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,0f,-1.8f,2.3989f,0f,-1.8f,0f,-1.82f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,0.9f,-1.5588f,3.2757f,0f,-1.5588f,-0.9f,-1.3138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.3789f,-1.157f,3.9592f,0f,-1.157f,-1.3789f,-0.4554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6914f,-0.6156f,4.1661f,0f,-0.6156f,-1.6914f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":3.1363162875,"pz":-0.2384261802,"ry":0,"rx":-20},"hitbox_body_1":{"px":0,"py":3.5698171045,"pz":1.5843186867,"ry":0,"rx":-5},"pos_head":{"px":0,"py":4.5315195738,"pz":3.3208022692,"ry":0,"rx":30},"hitbox_head_0":{"px":0,"py":3.9995634695,"pz":3.0136772692,"ry":0,"rx":30},"hitbox_tail_0":{"px":0,"py":2.5325209713,"pz":-1.1378218238,"ry":0,"rx":-60},"hitbox_tail_1":{"px":0,"py":1.7307081907,"pz":-1.2960354471,"ry":0,"rx":-90},"shadow":{"px":0,"py":2.8125,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args