# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.283f,1.2625f,0.924f,0f,1.2625f,-1.283f,3.2294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.2267f,1.3173f,1.2081f,0f,1.3173f,-1.2267f,2.9846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.5096f,0.9804f,1.3534f,0f,0.9804f,-1.5096f,2.6796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5778f,0.8663f,1.214f,0f,0.8663f,-1.5778f,2.2862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5977f,0.829f,1.4002f,0f,0.829f,-1.5977f,2.0342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7448f,0.328f,0.2968f,0.3628f,-0.0454f,1.0684f,-1.4479f,0.7931f,-0.44f,-1.411f,-1.0274f,1.9069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7448f,0.0985f,0.4313f,0.4929f,-0.0454f,1.7057f,-0.5732f,0.891f,-0.44f,-0.5666f,-1.6509f,1.3924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7448f,-0.021f,0.4419f,0.4078f,-0.0454f,1.797f,-0.0942f,1.3882f,-0.44f,-0.1024f,-1.7424f,1.5517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7962f,-0.0494f,-0.1062f,-0.4097f,0.0418f,1.2542f,-1.2905f,0.8847f,0.1094f,-1.2902f,-1.2504f,1.8115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7962f,-0.005f,-0.117f,-0.4439f,0.0418f,1.6525f,-0.7123f,0.9384f,0.1094f,-0.7135f,-1.6489f,1.2757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7387f,0.1969f,0.4222f,-0.4078f,0.255f,1.7674f,0.2261f,1.3882f,-0.3899f,0.2782f,-1.7351f,1.5517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7525f,0.4108f,1.5731f,0f,0.4108f,-1.7525f,1.0348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7827f,0.2493f,0.8926f,0f,0.2493f,-1.7827f,0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.4661f,1.0443f,0.9616f,0f,1.0443f,-1.4661f,0.6393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.8118f,-1.6065f,1.3915f,0f,-1.6065f,-0.8118f,0.1155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7791f,0.2732f,0.9191f,0f,0.2732f,-1.7791f,-0.4537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,0.8663f,1.5778f,0.714f,0f,1.5778f,-0.8663f,0.1298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7483f,-0.4284f,1.3915f,0f,-0.4284f,-1.7483f,0.1155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.6885f,0.6236f,1.4679f,0f,0.6236f,-1.6885f,-2.5858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7866f,0.2194f,1.3445f,0f,0.2194f,-1.7866f,-1.5808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7928f,-0.1605f,1.4143f,0f,-0.1605f,-1.7928f,-0.4858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7944f,-0.1424f,1.4314f,0f,-0.1424f,-1.7944f,0.2279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.5632781378,"pz":-0.4960730285,"ry":0,"rx":-4.5384615385},"hitbox_body_1":{"px":0,"py":0.4801181992,"pz":1.3245303682,"ry":0,"rx":13.1923076923},"pos_head":{"px":0,"py":0.9195250067,"pz":3.2571450059,"ry":0,"rx":47.0384615385},"hitbox_head_0":{"px":0,"py":0.5009091705,"pz":2.8076298848,"ry":0,"rx":47.0384615385},"hitbox_tail_0":{"px":0,"py":0.8921462693,"pz":-2.1962317036,"ry":0,"rx":7},"hitbox_tail_1":{"px":0,"py":1.2078376794,"pz":-3.3941136757,"ry":0,"rx":20.2692307692},"shadow":{"px":0,"py":0.0778846154,"pz":-0.225,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args