# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-4.4995f,0.059f,-0.0353f,-0.0113f,0.0538f,4.4599f,0.5971f,2.0549f,0.0428f,0.5966f,-4.4601f,4.8543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-4.4995f,0.0523f,-0.0446f,-0.0078f,0.0538f,4.497f,-0.1538f,2.7637f,0.0428f,-0.1544f,-4.4971f,4.3305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-4.4996f,-0.0048f,0.0582f,0f,-0.0056f,4.4996f,-0.0619f,2.8361f,-0.0581f,-0.0619f,-4.4992f,3.7213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-4.5f,0f,0f,0f,0f,4.4957f,0.1962f,2.8602f,0f,0.1962f,-4.4957f,2.962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-4.5f,0f,0f,0f,0f,4.4996f,0.0568f,2.8513f,0f,0.0568f,-4.4996f,2.2336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_right_1) {transformation: [-4.462f,-0.2703f,-0.5175f,-2.4839f,-0.4247f,-1.2352f,4.3063f,3.3887f,-0.4007f,4.3187f,1.1992f,0.7971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_right_0) {transformation: [-4.2336f,-1.4142f,0.5717f,-0.5522f,0.9228f,-1.0315f,4.2819f,2.9471f,-1.2146f,4.1456f,1.2604f,1.4468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_left_1) {transformation: [-4.4423f,0.2703f,0.6656f,2.4839f,0.5676f,-1.2352f,4.2898f,3.3887f,0.4404f,4.3187f,1.1852f,0.7971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wing_close_left_0) {transformation: [-4.2336f,1.4142f,-0.5717f,0.5522f,-0.9228f,-1.0315f,4.2819f,2.9471f,1.2146f,4.1456f,1.2604f,1.4468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-4.5f,0f,0f,0f,0f,4.4742f,0.4813f,3.1276f,0f,0.4813f,-4.4742f,0.7193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0682465098,"pz":1.2152714365,"ry":0,"rx":6.14},"hitbox_neck_0":{"px":0,"py":1.3055000664,"pz":3.0754004932,"ry":0,"rx":2.4983333333},"pos_head":{"px":-0.0033889375,"py":2.2797697399,"pz":5.4009331626,"ry":359.4319928716,"rx":-1.9592427078},"hitbox_head_0":{"px":-0.0177336167,"py":1.2455209169,"pz":5.1917834848,"ry":359.4319928716,"rx":-1.9592427078}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args