# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^-0.2738 ^1.7568 ^-0.4388 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^-0.2738 ^2.1481 ^2.8887 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^-0.2738 ^1.9811 ^3.6285 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_neck_1
execute positioned ^0 ^2.1522 ^5.0527 rotated ~0 ~59.9953 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_pos_head
$execute as $(hitbox_head_0) positioned ^-0.2738 ^1.4462 ^5.0783 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^0.7157 ^1.1942 ^0.0171 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^0.9785 ^-0.7156 ^-0.2535 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^-0.7157 ^1.1942 ^0.0171 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^-0.9785 ^-0.7156 ^-0.2535 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_leg_right_2
execute positioned ^0 ^3.0133 ^-2.6478 rotated ~0 ~-12.5047 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_pos_tail_0
execute positioned ^0 ^2.6488 ^-4.2114 rotated ~0 ~-7.5047 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^-0.2738 ^1.5164 ^-3.6828 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_tail_1
execute positioned ^0 ^2.445 ^-6.1867 rotated ~0 ~-7.5047 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_pos_tail_2
execute positioned ^0 ^2.4776 ^-8.1477 rotated ~0 ~-0.0047 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^-0.2738 ^1.4214 ^-8.462 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_tail_3
execute positioned ^0 ^3.434 ^-10.3517 rotated ~0 ~17.4953 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^-0.2738 ^2.257 ^-10.696 rotated ~180 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_hitbox_tail_4
$execute as $(shadow) positioned ^0 ^1.2125 ^0.25 rotated ~0 ~0 run function animated_java_dino:dino/animations/ecology_relax_long/zzz/frames/181_locator_shadow