# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.baking.frame matches 48.. run scoreboard players set @s aj.baking.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.baking.frame
execute at @s run function animated_java:nikuyaki/animations/baking/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.baking.frame 1