# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:nikuyaki/animations/pause_all
tag @s add aj.nikuyaki.animation.baking.playing
scoreboard players set @s aj.baking.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:nikuyaki/animations/baking/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only