# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.dino_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dino_aj', 'function_path': 'animated_java:dino_aj/animations/death_flying/stop'}
tag @s remove aj.dino_aj.animation.death_flying.playing
scoreboard players set @s aj.death_flying.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:dino_aj/animations/death_flying/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only