# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute if score @s aj.idle_relax.frame matches 76.. run scoreboard players set @s aj.idle_relax.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.idle_relax.frame
execute at @s run function animated_java_dino:dino/animations/idle_relax/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.idle_relax.frame 1