# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.7849f,0.1289f,0.194f,-0.0196f,0.2321f,0.8583f,1.565f,3.2168f,0.0196f,1.5769f,-0.8677f,2.5642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.7849f,0.2247f,0.0616f,-0.0048f,0.2321f,1.6753f,0.6159f,3.3584f,0.0196f,0.6187f,-1.6902f,2.2172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.799f,-0.0574f,0.019f,0f,-0.0589f,1.7918f,-0.1612f,3.2844f,-0.0138f,-0.1617f,-1.7927f,1.8877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7875f,-0.2115f,2.9424f,0f,-0.2115f,-1.7875f,1.6483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.6366f,-0.7495f,2.8583f,0f,-0.7495f,-1.6366f,1.3466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.4554f,-0.9253f,-0.5154f,0.9531f,0.1757f,0.6527f,-1.6682f,2.2874f,1.0445f,-1.3992f,-0.4374f,1.8593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.4554f,-0.7092f,-0.7866f,0.646f,0.1757f,1.1566f,-1.368f,2.0967f,1.0445f,-1.1829f,-0.866f,1.4586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.4554f,-0.9653f,-0.436f,0.4078f,0.1757f,0.5106f,-1.7171f,2.4301f,1.0445f,-1.4309f,-0.3186f,1.1239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.6568f,0.6507f,0.2679f,-0.7604f,-0.1189f,0.4167f,-1.7471f,2.4082f,-0.6936f,-1.6257f,-0.3405f,1.8968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.6568f,0.5802f,0.3982f,-0.5742f,-0.1189f,0.7732f,-1.6211f,2.0955f,-0.6936f,-1.5184f,-0.6733f,1.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.6568f,0.634f,0.3053f,-0.4078f,-0.1189f,0.5175f,-1.7199f,2.4301f,-0.6936f,-1.6032f,-0.4345f,1.1239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.2064f,-1.3359f,2.0668f,0f,-1.3359f,-1.2064f,0.7123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.8f,0f,0.8398f,0f,0f,-1.8f,-0.3317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7573f,0.3896f,1.1431f,0f,0.3896f,-1.7573f,0.2073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2728f,-1.2728f,1.715f,0f,-1.2728f,-1.2728f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,0f,0.8579f,0f,0f,-1.8f,-0.7488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6314f,0.7607f,1.0374f,0f,0.7607f,-1.6314f,-0.1569f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7573f,-0.3896f,1.715f,0f,-0.3896f,-1.7573f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,-0.0131f,0.385f,0f,-0.0131f,-1.8f,-2.4466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5523f,-0.9113f,0.8976f,0f,-0.9113f,-1.5523f,-1.5735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.3182f,-1.2257f,1.6239f,0f,-1.2257f,-1.3182f,-0.751f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7352f,-0.4785f,1.7754f,0f,-0.4785f,-1.7352f,-0.0534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":0.7862454016,"pz":-0.6004712147,"ry":0,"rx":-15.4166666667},"hitbox_body_1":{"px":0,"py":1.7924161917,"pz":1.8092486449,"ry":0,"rx":-47.9166666667},"pos_head":{"px":-0.018180472,"py":3.2252107171,"pz":2.5908740693,"ry":2.086910785,"rx":20.0105890361},"hitbox_head_0":{"px":-0.094853123,"py":2.6535060136,"pz":2.3797388066,"ry":2.086910785,"rx":20.0105890361},"hitbox_tail_0":{"px":0,"py":0.1643992929,"pz":-1.787373162,"ry":0,"rx":-30.4166666667},"hitbox_tail_1":{"px":0,"py":-0.1438447083,"pz":-3.1109480972,"ry":0,"rx":-0.4166666667}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args