# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.7736f,0.3069f,-0.0088f,-0.0064f,0.2407f,1.4216f,1.0775f,1.3154f,0.1907f,1.0605f,-1.4418f,3.9468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.7931f,0.1549f,0.0249f,0.0001f,0.1392f,1.4378f,1.0739f,1.5505f,0.0725f,1.0718f,-1.4443f,3.6547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,1.5503f,0f,0.2349f,-1.7846f,3.3169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7998f,0.0262f,1.2429f,0f,0.0262f,-1.7998f,3.0346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7992f,-0.0524f,1.2831f,0f,-0.0524f,-1.7992f,2.7239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.6878f,-0.0541f,-0.6232f,0.3148f,0.6056f,0.3084f,-1.6668f,0.4533f,0.1569f,-1.7725f,-0.271f,2.7429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.6878f,0.5967f,-0.1878f,0.355f,0.6056f,1.694f,-0.0596f,0.6831f,0.1569f,-0.1191f,-1.7892f,2.2563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7051f,0.0668f,-0.5728f,0.4078f,0.2858f,1.6507f,-0.6584f,1.2094f,0.5008f,-0.7147f,-1.5743f,2.2469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7073f,-0.4024f,0.4039f,-0.2462f,-0.548f,0.8058f,-1.5134f,0.5719f,0.1575f,-1.5584f,-0.8868f,3.0199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7073f,-0.5617f,-0.0979f,-0.3562f,-0.548f,1.7019f,-0.208f,0.7641f,0.1575f,-0.1674f,-1.7853f,2.5278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7236f,-0.0889f,0.5111f,-0.4078f,-0.4671f,1.0374f,-1.3949f,1.2094f,-0.2257f,-1.4683f,-1.0164f,2.2469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7907f,0.1829f,1.3265f,0f,0.1829f,-1.7907f,1.7105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7998f,0.0262f,0.8348f,0f,0.0262f,-1.7998f,0.762f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7515f,0.4151f,1.1302f,0f,0.4151f,-1.7515f,1.3053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9226f,-1.5456f,1.5958f,0f,-1.5456f,-0.9226f,0.813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7387f,0.4659f,1.0206f,0f,0.4659f,-1.7387f,-0.0821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.2541f,1.2912f,0.9778f,0f,1.2912f,-1.2541f,0.5349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7628f,0.364f,1.5958f,0f,0.364f,-1.7628f,0.813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.1368f,1.3956f,2.8701f,0f,1.3956f,-1.1368f,-1.5489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.428f,1.0958f,2.2537f,0f,1.0958f,-1.428f,-0.7456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7167f,0.5413f,1.897f,0f,0.5413f,-1.7167f,0.2921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6528f,0.7129f,1.5786f,0f,0.7129f,-1.6528f,0.931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.1495439598,"pz":-0.1148334203,"ry":0,"rx":23.3333333333},"hitbox_body_1":{"px":0,"py":0.2796706472,"pz":2.1378690783,"ry":0,"rx":5.8333333333},"pos_head":{"px":-0.0052584501,"py":1.3159064545,"pz":3.9748461876,"ry":0.9894588109,"rx":36.6285210005},"hitbox_head_0":{"px":-0.05812092,"py":0.825250638,"pz":3.6091065377,"ry":0.9894588109,"rx":36.6285210005},"hitbox_tail_0":{"px":0,"py":2.1762746127,"pz":-1.5054101514,"ry":0,"rx":37.5},"hitbox_tail_1":{"px":0,"py":3.05718135,"pz":-2.3771058592,"ry":0,"rx":50.8333333333}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args