# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.7959f,0.1199f,-0.0227f,0.0015f,0.1132f,1.7618f,0.3511f,2.0581f,0.0456f,0.3489f,-1.7653f,3.3328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.799f,0.0604f,-0.0095f,0.0001f,0.0574f,1.7646f,0.3508f,2.1453f,0.021f,0.3503f,-1.7655f,2.968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0.0044f,2.1018f,0f,0.0044f,-1.8f,2.633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7999f,-0.0218f,1.787f,0f,-0.0218f,-1.7999f,2.359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7992f,-0.0524f,1.8272f,0f,-0.0524f,-1.7992f,2.0483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.7721f,0.0883f,-0.3029f,0.3794f,0.3061f,0.9003f,-1.5283f,1.0135f,0.0765f,-1.5562f,-0.9014f,1.9904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.7721f,0.2785f,-0.1483f,0.3838f,0.3061f,1.7226f,-0.4232f,1.1526f,0.0765f,-0.4419f,-1.7432f,1.469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.7854f,0.122f,-0.1931f,0.4078f,0.1502f,1.7736f,-0.2677f,1.6663f,0.1722f,-0.2816f,-1.7695f,1.5933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.7727f,-0.2371f,0.2031f,-0.3402f,-0.3078f,1.1308f,-1.3662f,1.0133f,0.0524f,-1.3802f,-1.1542f,2.1022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.7727f,-0.3107f,0.0304f,-0.3802f,-0.3078f,1.7099f,-0.4705f,1.1382f,0.0524f,-0.4686f,-1.7372f,1.5788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.7883f,-0.1661f,0.1192f,-0.4078f,-0.1976f,1.6734f,-0.633f,1.6663f,-0.0524f,-0.642f,-1.6808f,1.5933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7935f,-0.1525f,1.6819f,0f,-0.1525f,-1.7935f,1.0445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_1":{"px":0,"py":0.7324734614,"pz":1.6586992575,"ry":0,"rx":-4.8611111111},"pos_head":{"px":0.0021787032,"py":2.0706768014,"pz":3.3578752166,"ry":359.6931900378,"rx":11.2382753788},"hitbox_head_0":{"px":-0.0184173973,"py":1.468522961,"pz":3.2383360361,"ry":359.6931900378,"rx":11.2382753788}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args