# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1f,0f,0f,0f,0f,0.9392f,0.3433f,1.5765f,0f,0.3433f,-0.9392f,1.6716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1f,0f,0f,0.0001f,0f,0.9392f,0.3433f,1.6555f,0f,0.3433f,-0.9392f,1.4788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1f,0f,0f,0f,0f,0.8546f,0.5192f,1.7311f,0f,0.5192f,-0.8546f,1.307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1f,0f,0f,0f,0f,0.8546f,0.5192f,1.6634f,0f,0.5192f,-0.8546f,1.0852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1f,0f,0f,0f,0f,0.9931f,-0.117f,1.6704f,0f,-0.117f,-0.9931f,0.9114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1f,0f,0f,0.2422f,0f,0.9245f,-0.3811f,1.181f,0f,-0.3811f,-0.9245f,0.9951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1f,0f,0f,0.2437f,0f,0.9245f,-0.3811f,1.2156f,0f,-0.3811f,-0.9245f,0.6973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1f,0f,0f,0.2266f,0f,0.9245f,-0.3811f,1.509f,0f,-0.3811f,-0.9245f,0.6972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1f,0f,0f,-0.2422f,0f,0.9245f,-0.3811f,1.181f,0f,-0.3811f,-0.9245f,0.9951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1f,0f,0f,-0.2438f,0f,0.9245f,-0.3811f,1.2156f,0f,-0.3811f,-0.9245f,0.6973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1f,0f,0f,-0.2266f,0f,0.9245f,-0.3811f,1.509f,0f,-0.3811f,-0.9245f,0.6972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1f,0f,0f,0f,0f,0.9245f,-0.3811f,1.4254f,0f,-0.3811f,-0.9245f,0.4039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1f,0f,0f,0.2316f,0f,0.9961f,-0.0879f,0.3818f,0f,-0.0879f,-0.9961f,-0.1884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1f,0f,0f,0.2344f,0f,0.9961f,-0.0879f,0.6327f,0f,-0.0879f,-0.9961f,0.0463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1f,0f,0f,0.2422f,0f,0.9961f,-0.0879f,1.0059f,0f,-0.0879f,-0.9961f,0.0956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1f,0f,0f,-0.2316f,0f,0.9925f,-0.1226f,0.3723f,0f,-0.1226f,-0.9925f,-0.1665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1f,0f,0f,-0.2344f,0f,0.9925f,-0.1226f,0.6312f,0f,-0.1226f,-0.9925f,0.0593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1f,0f,0f,-0.2422f,0f,0.9925f,-0.1226f,1.0059f,0f,-0.1226f,-0.9925f,0.0956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1f,0f,0f,0f,0f,0.7552f,0.6555f,0.6746f,0f,0.6555f,-0.7552f,-1.3069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1f,0f,0f,0f,0f,0.9963f,0.0865f,0.6259f,0f,0.0865f,-0.9963f,-0.7465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1f,0f,0f,0f,0f,0.9561f,-0.293f,0.7896f,0f,-0.293f,-0.9561f,-0.1593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1f,0f,0f,0f,0f,0.6815f,-0.7318f,1.0645f,0f,-0.7318f,-0.6815f,0.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":0.4371640662,"pz":0.1559341313,"ry":0,"rx":-47.04},"hitbox_body_1":{"px":0,"py":1.0252825044,"pz":0.8882327309,"ry":0,"rx":-22.4},"pos_head":{"px":0,"py":1.5812974196,"pz":1.6864176697,"ry":0,"rx":20.08},"hitbox_head_0":{"px":0,"py":1.2607905893,"pz":1.5692556698,"ry":0,"rx":20.08},"hitbox_tail_0":{"px":0,"py":0.3626238277,"pz":-1.0792054339,"ry":0,"rx":4.96},"hitbox_tail_1":{"px":0,"py":0.6980850674,"pz":-1.7780242889,"ry":0,"rx":40.96}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args