# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1f,0f,0f,0f,0f,0.9469f,0.3214f,1.5681f,0f,0.3214f,-0.9469f,1.6957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1f,0f,0f,0.0001f,0f,0.9469f,0.3214f,1.6427f,0f,0.3214f,-0.9469f,1.5012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1f,0f,0f,0f,0f,0.8721f,0.4893f,1.7123f,0f,0.4893f,-0.8721f,1.3269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1f,0f,0f,0f,0f,0.8721f,0.4893f,1.6369f,0f,0.4893f,-0.8721f,1.1076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1f,0f,0f,0f,0f,0.9939f,-0.1102f,1.6451f,0f,-0.1102f,-0.9939f,0.9338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1f,0f,0f,0.2422f,0f,0.933f,-0.3599f,1.1539f,0f,-0.3599f,-0.933f,1.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1f,0f,0f,0.2437f,0f,0.933f,-0.3599f,1.1953f,0f,-0.3599f,-0.933f,0.7094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1f,0f,0f,0.2266f,0f,0.933f,-0.3599f,1.4886f,0f,-0.3599f,-0.933f,0.716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1f,0f,0f,-0.2422f,0f,0.933f,-0.3599f,1.1539f,0f,-0.3599f,-0.933f,1.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1f,0f,0f,-0.2438f,0f,0.933f,-0.3599f,1.1953f,0f,-0.3599f,-0.933f,0.7094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1f,0f,0f,-0.2266f,0f,0.933f,-0.3599f,1.4886f,0f,-0.3599f,-0.933f,0.716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1f,0f,0f,0f,0f,0.933f,-0.3599f,1.4117f,0f,-0.3599f,-0.933f,0.4209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1f,0f,0f,0.2316f,0f,0.9963f,-0.0858f,0.384f,0f,-0.0858f,-0.9963f,-0.1925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1f,0f,0f,0.2344f,0f,0.9963f,-0.0858f,0.6344f,0f,-0.0858f,-0.9963f,0.0428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1f,0f,0f,0.2422f,0f,0.9963f,-0.0858f,1.0075f,0f,-0.0858f,-0.9963f,0.0928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1f,0f,0f,-0.2316f,0f,0.993f,-0.1183f,0.375f,0f,-0.1183f,-0.993f,-0.1719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1f,0f,0f,-0.2344f,0f,0.993f,-0.1183f,0.6329f,0f,-0.1183f,-0.993f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1f,0f,0f,-0.2422f,0f,0.993f,-0.1183f,1.0075f,0f,-0.1183f,-0.993f,0.0928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1f,0f,0f,0f,0f,0.7858f,0.6185f,0.6925f,0f,0.6185f,-0.7858f,-1.3225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1f,0f,0f,0f,0f,0.997f,0.0776f,0.6488f,0f,0.0776f,-0.997f,-0.7617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1f,0f,0f,0f,0f,0.9604f,-0.2785f,0.8036f,0f,-0.2785f,-0.9604f,-0.1721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1f,0f,0f,0f,0f,0.7157f,-0.6984f,1.0645f,0f,-0.6984f,-0.7157f,0.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":0.4364787055,"pz":0.1258782229,"ry":0,"rx":-44.296875},"hitbox_body_1":{"px":0,"py":1.0006593282,"pz":0.895940131,"ry":0,"rx":-21.09375},"pos_head":{"px":0,"py":1.5732529136,"pz":1.7104765815,"ry":0,"rx":18.75},"hitbox_head_0":{"px":0,"py":1.2501130069,"pz":1.6007853639,"ry":0,"rx":18.75},"hitbox_tail_0":{"px":0,"py":0.3826027751,"pz":-1.0921040644,"ry":0,"rx":4.453125},"hitbox_tail_1":{"px":0,"py":0.6933493075,"pz":-1.7942593677,"ry":0,"rx":38.203125}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args