# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1f,0f,0f,0f,0f,0.9749f,0.2227f,1.4224f,0f,0.2227f,-0.9749f,1.8355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1f,0f,0f,0.0001f,0f,0.9749f,0.2227f,1.4765f,0f,0.2227f,-0.9749f,1.6344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1f,0f,0f,0f,0f,0.9501f,0.3121f,1.5113f,0f,0.3121f,-0.9501f,1.4499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1f,0f,0f,0f,0f,0.9501f,0.3121f,1.395f,0f,0.3121f,-0.9501f,1.2493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1f,0f,0f,0f,0f,0.9985f,-0.0556f,1.4128f,0f,-0.0556f,-0.9985f,1.0761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1f,0f,0f,0.2422f,0f,0.9828f,-0.1845f,0.9166f,0f,-0.1845f,-0.9828f,1.0583f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1f,0f,0f,0.2437f,0f,0.9828f,-0.1845f,1.0111f,0f,-0.1845f,-0.9828f,0.7738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1f,0f,0f,0.2266f,0f,0.9828f,-0.1845f,1.2984f,0f,-0.1845f,-0.9828f,0.8336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1f,0f,0f,-0.2422f,0f,0.9828f,-0.1845f,0.9166f,0f,-0.1845f,-0.9828f,1.0583f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1f,0f,0f,-0.2438f,0f,0.9828f,-0.1845f,1.0111f,0f,-0.1845f,-0.9828f,0.7738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1f,0f,0f,-0.2266f,0f,0.9828f,-0.1845f,1.2984f,0f,-0.1845f,-0.9828f,0.8336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1f,0f,0f,0f,0f,0.9828f,-0.1845f,1.2764f,0f,-0.1845f,-0.9828f,0.5294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1f,0f,0f,0.2316f,0f,0.9997f,0.0227f,0.4353f,0f,0.0227f,-0.9997f,-0.2773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1f,0f,0f,0.2344f,0f,0.9997f,0.0227f,0.6588f,0f,0.0227f,-0.9997f,-0.0162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1f,0f,0f,0.2422f,0f,0.9997f,0.0227f,1.0243f,0f,0.0227f,-0.9997f,0.0739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1f,0f,0f,-0.2316f,0f,1f,0.003f,0.4285f,0f,0.003f,-1f,-0.2656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1f,0f,0f,-0.2344f,0f,1f,0.003f,0.6571f,0f,0.003f,-1f,-0.0091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1f,0f,0f,-0.2422f,0f,1f,0.003f,1.0243f,0f,0.003f,-1f,0.0739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1f,0f,0f,0f,0f,0.8896f,0.4567f,0.9598f,0f,0.4567f,-0.8896f,-1.4145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1f,0f,0f,0f,0f,0.9927f,0.1206f,0.8919f,0f,0.1206f,-0.9927f,-0.8561f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1f,0f,0f,0f,0f,0.9955f,-0.095f,0.9343f,0f,-0.095f,-0.9955f,-0.248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1f,0f,0f,0f,0f,0.925f,-0.3799f,1.0645f,0f,-0.3799f,-0.925f,0.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":0.48235712,"pz":-0.1090312654,"ry":0,"rx":-22.325625},"hitbox_body_1":{"px":0,"py":0.7859004005,"pz":0.9219317364,"ry":0,"rx":-10.63125},"pos_head":{"px":0,"py":1.4289518463,"pz":1.8496707381,"ry":0,"rx":12.87},"hitbox_head_0":{"px":0,"py":1.0962747445,"pz":1.7736608149,"ry":0,"rx":12.87},"hitbox_tail_0":{"px":0,"py":0.6401908029,"pz":-1.1976913961,"ry":0,"rx":6.924375},"hitbox_tail_1":{"px":0,"py":0.8703262614,"pz":-1.8777150465,"ry":0,"rx":27.174375}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args