# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,0.4659f,1.7387f,1.6559f,0f,1.7387f,-0.4659f,4.1231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.8f,0f,1.6703f,0f,0f,-1.8f,3.7484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,0.1569f,1.6554f,0f,0.1569f,-1.7932f,3.4109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.3969f,0f,0.3126f,-1.7727f,3.0832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.4991f,0f,0.3126f,-1.7727f,2.787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.2349f,-1.7846f,0.4491f,0f,-1.7846f,-0.2349f,2.233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.428f,1.0958f,0.9441f,0f,1.0958f,-1.428f,2.0179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7573f,0.3896f,1.3773f,0f,0.3896f,-1.7573f,2.32f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,-0.0785f,-1.7983f,0.5216f,0f,-1.7983f,0.0785f,2.3537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.663f,0.6888f,0.9441f,0f,0.6888f,-1.663f,2.0179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7573f,0.3896f,1.3773f,0f,0.3896f,-1.7573f,2.32f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.4393f,0f,0f,-1.8f,1.7745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7932f,-0.1569f,0.7907f,0f,-0.1569f,-1.7932f,1.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7573f,-0.3896f,1.2934f,0f,-0.3896f,-1.7573f,1.3775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9671f,-1.5181f,1.773f,0f,-1.5181f,-0.9671f,0.8989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7167f,0.5413f,0.9716f,0f,0.5413f,-1.7167f,-0.0398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6914f,0.6156f,1.2019f,0f,0.6156f,-1.6914f,0.5342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6914f,0.6156f,1.773f,0f,0.6156f,-1.6914f,0.8989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,3.4372f,0f,0.2349f,-1.7846f,-1.1803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5966f,0.8311f,2.9697f,0f,0.8311f,-1.5966f,-0.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.157f,1.3789f,2.1114f,0f,1.3789f,-1.157f,0.4013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5966f,0.8311f,1.7473f,0f,0.8311f,-1.5966f,1.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.3954155784,"pz":-0.0588660192,"ry":0,"rx":27.5},"hitbox_body_1":{"px":0,"py":0.441297928,"pz":2.3060561878,"ry":0,"rx":0},"pos_head":{"px":0,"py":1.6730882827,"pz":4.1452598395,"ry":0,"rx":0},"hitbox_head_0":{"px":0,"py":1.0588382827,"pz":4.1452598395,"ry":0,"rx":0},"hitbox_tail_0":{"px":0,"py":2.7615148892,"pz":-1.0170819694,"ry":0,"rx":27.5},"hitbox_tail_1":{"px":0,"py":3.0049471223,"pz":-1.9111992439,"ry":0,"rx":7.5},"shadow":{"px":0,"py":0.39375,"pz":0.5625,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args