# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7173f,0.5393f,1.5904f,0f,0.5393f,-1.7173f,4.1699f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7719f,0.3169f,1.6706f,0f,0.3169f,-1.7719f,3.8035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.777f,0.2868f,1.6802f,0f,0.2868f,-1.777f,3.4658f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,0.4405f,1.4462f,0f,0.4405f,-1.7453f,3.1202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,0.4405f,1.5697f,0f,0.4405f,-1.7453f,2.8323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.9946f,-1.5003f,0.6832f,0f,-1.5003f,-0.9946f,2.3991f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7206f,0.5288f,1.072f,0f,0.5288f,-1.7206f,2.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7244f,0.5162f,1.4822f,0f,0.5162f,-1.7244f,2.3576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.9394f,-1.5354f,0.7187f,0f,-1.5354f,-0.9394f,2.4328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7615f,0.3704f,1.072f,0f,0.3704f,-1.7615f,2.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7244f,0.5162f,1.4822f,0f,0.5162f,-1.7244f,2.3576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7952f,0.1308f,1.5836f,0f,0.1308f,-1.7952f,1.8181f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7999f,-0.0143f,0.7916f,0f,-0.0143f,-1.7999f,0.6257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7751f,0.2984f,1.1223f,0f,0.2984f,-1.7751f,1.1484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.4849f,-1.0173f,1.7513f,0f,-1.0173f,-1.4849f,0.8962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7946f,-0.1397f,1.0403f,0f,-0.1397f,-1.7946f,0.3954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4215f,1.1043f,1.0837f,0f,1.1043f,-1.4215f,1.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6638f,-0.6869f,1.7513f,0f,-0.6869f,-1.6638f,0.8962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.6613f,0.6929f,2.3145f,0f,0.6929f,-1.6613f,-1.7382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7893f,0.196f,2.2043f,0f,0.196f,-1.7893f,-0.7317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7745f,0.3017f,1.9927f,0f,0.3017f,-1.7745f,0.345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7219f,0.5245f,1.7473f,0f,0.5245f,-1.7219f,1.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.2045346281,"pz":0.0238028357,"ry":0,"rx":16.9416666667},"hitbox_body_1":{"px":0,"py":0.5496419396,"pz":2.2757229399,"ry":0,"rx":4.1666666667},"pos_head":{"px":0,"py":1.603458327,"pz":4.1947026554,"ry":0,"rx":10.1416666667},"hitbox_head_0":{"px":0,"py":0.9988057441,"pz":4.0865438996,"ry":0,"rx":10.1416666667},"hitbox_tail_0":{"px":0,"py":1.7439100278,"pz":-1.3411023892,"ry":0,"rx":6.25},"hitbox_tail_1":{"px":0,"py":2.0881361155,"pz":-2.5565588401,"ry":0,"rx":22.6416666667}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args