# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7641f,0.3576f,1.7068f,0f,0.3576f,-1.7641f,4.1772f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7863f,0.222f,1.7674f,0f,0.222f,-1.7863f,3.8071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,1.7672f,0f,0.2349f,-1.7846f,3.4693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,0.3896f,1.5232f,0f,0.3896f,-1.7573f,3.1307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,0.3896f,1.6383f,0f,0.3896f,-1.7573f,2.8393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.1113f,-1.416f,0.8057f,0f,-1.416f,-1.1113f,2.4873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7893f,0.196f,1.1173f,0f,0.196f,-1.7893f,2.0467f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7387f,0.4659f,1.537f,0f,0.4659f,-1.7387f,2.3674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.0801f,-1.4399f,0.8302f,0f,-1.4399f,-1.0801f,2.5036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7973f,0.0981f,1.1173f,0f,0.0981f,-1.7973f,2.0467f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7387f,0.4659f,1.537f,0f,0.4659f,-1.7387f,2.3674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0785f,1.6227f,0f,0.0785f,-1.7983f,1.8251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7999f,0.0228f,0.8219f,0f,0.0228f,-1.7999f,0.5287f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7326f,0.4879f,1.0944f,0f,0.4879f,-1.7326f,1.0839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.5796f,-0.863f,1.7455f,0f,-0.863f,-1.5796f,0.8961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7992f,-0.0525f,0.9775f,0f,-0.0525f,-1.7992f,0.3903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5146f,0.9726f,1.076f,0f,0.9726f,-1.5146f,1.0009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6752f,-0.6585f,1.7455f,0f,-0.6585f,-1.6752f,0.8961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7942f,0.1439f,2.0574f,0f,0.1439f,-1.7942f,-1.7691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7996f,-0.0393f,2.0795f,0f,-0.0393f,-1.7996f,-0.7568f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7937f,0.1503f,1.9599f,0f,0.1503f,-1.7937f,0.3339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,0.4405f,1.7473f,0f,0.4405f,-1.7453f,1.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.1571374445,"pz":0.0512609056,"ry":0,"rx":14.165},"hitbox_body_1":{"px":0,"py":0.6024687446,"pz":2.3125895188,"ry":0,"rx":2.5},"pos_head":{"px":0,"py":1.7212014189,"pz":4.2013434293,"ry":0,"rx":7.085},"hitbox_head_0":{"px":0,"py":1.1116416706,"pz":4.125580802,"ry":0,"rx":7.085},"hitbox_tail_0":{"px":0,"py":1.5435636336,"pz":-1.3009543603,"ry":0,"rx":-1.25},"hitbox_tail_1":{"px":0,"py":1.5885627684,"pz":-2.4770226933,"ry":0,"rx":4.585}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args