# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,0.4659f,1.7387f,1.6639f,0f,1.7387f,-0.4659f,4.1164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7961f,-0.1177f,1.6538f,0f,-0.1177f,-1.7961f,3.7415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,0.1569f,1.6389f,0f,0.1569f,-1.7932f,3.404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.3804f,0f,0.3126f,-1.7727f,3.0763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.4826f,0f,0.3126f,-1.7727f,2.7801f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.2349f,-1.7846f,0.4196f,0f,-1.7846f,-0.2349f,2.1932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.3533f,1.1868f,0.9276f,0f,1.1868f,-1.3533f,2.011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7573f,0.3896f,1.3608f,0f,0.3896f,-1.7573f,2.3131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0f,-1.8f,0.4775f,0f,-1.8f,0f,2.3087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.5966f,0.8311f,0.9276f,0f,0.8311f,-1.5966f,2.011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7573f,0.3896f,1.3608f,0f,0.3896f,-1.7573f,2.3131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.4228f,0f,0f,-1.8f,1.7676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7932f,-0.1569f,0.7829f,0f,-0.1569f,-1.7932f,1.0072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7573f,-0.3896f,1.2856f,0f,-0.3896f,-1.7573f,1.3675f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1f,-1.4966f,1.7756f,0f,-1.4966f,-1f,0.8995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7167f,0.5413f,0.9697f,0f,0.5413f,-1.7167f,-0.0464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7045f,0.5786f,1.2126f,0f,0.5786f,-1.7045f,0.5224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6776f,0.6524f,1.7756f,0f,0.6524f,-1.6776f,0.8995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,3.4795f,0f,0.2349f,-1.7846f,-1.1342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5966f,0.8311f,3.012f,0f,0.8311f,-1.5966f,-0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.0958f,1.428f,2.1247f,0f,1.428f,-1.0958f,0.4094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5781f,0.8658f,1.7473f,0f,0.8658f,-1.5781f,1.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.4189336289,"pz":-0.0662870286,"ry":0,"rx":28.75},"hitbox_body_1":{"px":0,"py":0.4248098002,"pz":2.2991563328,"ry":0,"rx":0},"pos_head":{"px":0,"py":1.6825525023,"pz":4.1373266911,"ry":0,"rx":-3.75},"hitbox_head_0":{"px":0,"py":1.0696176587,"pz":4.1775005632,"ry":0,"rx":-3.75},"hitbox_tail_0":{"px":0,"py":2.8038223631,"pz":-0.9709035943,"ry":0,"rx":27.5},"hitbox_tail_1":{"px":0,"py":3.0472545962,"pz":-1.8650208689,"ry":0,"rx":7.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args