# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,0.4659f,1.7387f,1.6698f,0f,1.7387f,-0.4659f,4.1102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7885f,-0.2031f,1.6419f,0f,-0.2031f,-1.7885f,3.7362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,0.1569f,1.627f,0f,0.1569f,-1.7932f,3.3987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.3685f,0f,0.3126f,-1.7727f,3.071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.4707f,0f,0.3126f,-1.7727f,2.7749f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.2349f,-1.7846f,0.3996f,0f,-1.7846f,-0.2349f,2.1636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.2953f,1.2499f,0.9157f,0f,1.2499f,-1.2953f,2.0058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7573f,0.3896f,1.3489f,0f,0.3896f,-1.7573f,2.3079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.0571f,-1.7991f,0.4476f,0f,-1.7991f,-0.0571f,2.2744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.5407f,0.9307f,0.9157f,0f,0.9307f,-1.5407f,2.0058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7573f,0.3896f,1.3489f,0f,0.3896f,-1.7573f,2.3079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.4109f,0f,0f,-1.8f,1.7624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7932f,-0.1569f,0.7774f,0f,-0.1569f,-1.7932f,0.9999f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7573f,-0.3896f,1.28f,0f,-0.3896f,-1.7573f,1.3602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.0236f,-1.4806f,1.7774f,0f,-1.4806f,-1.0236f,0.9f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7167f,0.5413f,0.9686f,0f,0.5413f,-1.7167f,-0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.7134f,0.5515f,1.2205f,0f,0.5515f,-1.7134f,0.514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6671f,0.6789f,1.7774f,0f,0.6789f,-1.6671f,0.9f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7846f,0.2349f,3.5091f,0f,0.2349f,-1.7846f,-1.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5966f,0.8311f,3.0416f,0f,0.8311f,-1.5966f,-0.2015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.0499f,1.4621f,2.1342f,0f,1.4621f,-1.0499f,0.4154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.5642f,0.8907f,1.7473f,0f,0.8907f,-1.5642f,1.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.4361364745,"pz":-0.071360967,"ry":0,"rx":29.6590909091},"hitbox_body_1":{"px":0,"py":0.4129149949,"pz":2.2939131747,"ry":0,"rx":0},"pos_head":{"px":0,"py":1.6894611131,"pz":4.1302667875,"ry":0,"rx":-6.4772727273},"hitbox_head_0":{"px":0,"py":1.0791320666,"pz":4.1995597704,"ry":0,"rx":-6.4772727273},"hitbox_tail_0":{"px":0,"py":2.8334210999,"pz":-0.9363620188,"ry":0,"rx":27.5},"hitbox_tail_1":{"px":0,"py":3.076853333,"pz":-1.8304792934,"ry":0,"rx":7.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args