# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.4065f,1.1233f,1.5774f,0f,1.1233f,-1.4065f,4.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7924f,0.1656f,1.6263f,0f,0.1656f,-1.7924f,3.6359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.781f,0.2609f,1.631f,0f,0.2609f,-1.781f,3.2981f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7515f,0.4151f,1.392f,0f,0.4151f,-1.7515f,2.956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7515f,0.4151f,1.5113f,0f,0.4151f,-1.7515f,2.6663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.7129f,-1.6528f,0.5393f,0f,-1.6528f,-0.7129f,2.144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.5588f,0.9f,1.0019f,0f,0.9f,-1.5588f,1.8662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7317f,0.4911f,1.4169f,0f,0.4911f,-1.7317f,2.1929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.6156f,-1.6914f,0.5844f,0f,-1.6914f,-0.6156f,2.2081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.6728f,0.6646f,1.0019f,0f,0.6646f,-1.6728f,1.8662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7317f,0.4911f,1.4169f,0f,0.4911f,-1.7317f,2.1929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.797f,0.1047f,1.5105f,0f,0.1047f,-1.797f,1.652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7997f,-0.0351f,0.7702f,0f,-0.0351f,-1.7997f,0.6115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7995f,0.0435f,1.1718f,0f,0.0435f,-1.7995f,1.0819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3387f,-1.2033f,1.7622f,0f,-1.2033f,-1.3387f,0.7494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.799f,0.0609f,0.9892f,0f,0.0609f,-1.799f,0.0822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5135f,0.9744f,1.087f,0f,0.9744f,-1.5135f,0.6929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7834f,-0.2437f,1.7622f,0f,-0.2437f,-1.7834f,0.7494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.6493f,0.721f,2.8422f,0f,0.721f,-1.6493f,-1.7215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7317f,0.4911f,2.566f,0f,0.4911f,-1.7317f,-0.7474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6125f,0.8f,2.0533f,0f,0.8f,-1.6125f,0.2227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6663f,0.6807f,1.7473f,0f,0.6807f,-1.6663f,0.8677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.2980544149,"pz":-0.1695813083,"ry":0,"rx":22.22},"hitbox_body_1":{"px":0,"py":0.4832509478,"pz":2.124594386,"ry":0,"rx":3.3333333333},"pos_head":{"px":0,"py":1.5925637951,"pz":4.0313910931,"ry":0,"rx":5.28},"hitbox_head_0":{"px":0,"py":0.980920131,"pz":3.9748659603,"ry":0,"rx":5.28},"hitbox_tail_0":{"px":0,"py":2.2135052323,"pz":-1.4249390695,"ry":0,"rx":15.8333333333},"hitbox_tail_1":{"px":0,"py":2.6297836225,"pz":-2.5435827105,"ry":0,"rx":23.6133333333},"shadow":{"px":0,"py":0.39375,"pz":0.41484375,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args