# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.5664f,0.8868f,1.5547f,0f,0.8868f,-1.5664f,3.9643f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7803f,0.2653f,1.6242f,0f,0.2653f,-1.7803f,3.5958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.777f,0.2868f,1.6338f,0f,0.2868f,-1.777f,3.2581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,0.4405f,1.3998f,0f,0.4405f,-1.7453f,2.9125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7453f,0.4405f,1.5233f,0f,0.4405f,-1.7453f,2.6245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,0.8253f,-1.5996f,0.5821f,0f,-1.5996f,-0.8253f,2.1246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.6144f,0.7961f,1.0256f,0f,0.7961f,-1.6144f,1.8172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7244f,0.5162f,1.4358f,0f,0.5162f,-1.7244f,2.1499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,0.7429f,-1.6396f,0.6247f,0f,-1.6396f,-0.7429f,2.1784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7024f,0.5848f,1.0256f,0f,0.5848f,-1.7024f,1.8172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7244f,0.5162f,1.4358f,0f,0.5162f,-1.7244f,2.1499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7952f,0.1308f,1.5372f,0f,0.1308f,-1.7952f,1.6104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7997f,-0.034f,0.7744f,0f,-0.034f,-1.7997f,0.5203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7958f,0.123f,1.1548f,0f,0.123f,-1.7958f,1.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.3864f,-1.1479f,1.7582f,0f,-1.1479f,-1.3864f,0.6997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.799f,-0.0612f,1.0245f,0f,-0.0612f,-1.799f,0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.4452f,1.073f,1.0814f,0f,1.073f,-1.4452f,0.7327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.7358f,-0.4765f,1.7582f,0f,-0.4765f,-1.7358f,0.6997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.5946f,0.8351f,2.6455f,0f,0.8351f,-1.5946f,-1.8498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7545f,0.4024f,2.4191f,0f,0.4024f,-1.7545f,-0.8629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.6995f,0.5929f,2.0312f,0f,0.5929f,-1.6995f,0.1635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.6885f,0.6237f,1.7473f,0f,0.6237f,-1.6885f,0.8185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.2631073572,"pz":-0.2029544709,"ry":0,"rx":20.275},"hitbox_body_1":{"px":0,"py":0.5032422438,"pz":2.0679723521,"ry":0,"rx":4.1666666667},"pos_head":{"px":0,"py":1.5684646918,"pz":3.9887388831,"ry":0,"rx":8.475},"hitbox_head_0":{"px":0,"py":0.9609221401,"pz":3.8982120341,"ry":0,"rx":8.475},"hitbox_tail_0":{"px":0,"py":2.0326259115,"pz":-1.5216488038,"ry":0,"rx":12.9166666667},"hitbox_tail_1":{"px":0,"py":2.4912792467,"pz":-2.6847937449,"ry":0,"rx":27.6416666667},"shadow":{"px":0,"py":0.39375,"pz":0.365625,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args