# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7804f,0.2652f,1.7652f,0f,0.2652f,-1.7804f,3.7362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7915f,0.1743f,1.8158f,0f,0.1743f,-1.7915f,3.3646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7878f,0.209f,1.8108f,0f,0.209f,-1.7878f,3.0269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7628f,0.364f,1.5619f,0f,0.364f,-1.7628f,2.6918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7628f,0.364f,1.6727f,0f,0.364f,-1.7628f,2.3987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.167f,-1.3704f,0.8716f,0f,-1.3704f,-1.167f,2.0818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7998f,0.0262f,1.1402f,0f,0.0262f,-1.7998f,1.6138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7453f,0.4405f,1.5645f,0f,0.4405f,-1.7453f,1.9284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.147f,-1.3873f,0.8888f,0f,-1.3873f,-1.147f,2.0913f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7996f,-0.0393f,1.1402f,0f,-0.0393f,-1.7996f,1.6138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7453f,0.4405f,1.5645f,0f,0.4405f,-1.7453f,1.9284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7992f,0.0524f,1.6424f,0f,0.0524f,-1.7992f,1.3849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7995f,0.0414f,0.8407f,0f,0.0414f,-1.7995f,0.0389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.7038f,0.5806f,1.0829f,0f,0.5806f,-1.7038f,0.608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.621f,-0.7824f,1.7426f,0f,-0.7824f,-1.621f,0.4532f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.8f,-0.0088f,0.9465f,0f,-0.0088f,-1.8f,-0.0532f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.5567f,0.9037f,1.0723f,0f,0.9037f,-1.5567f,0.5523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6807f,-0.6443f,1.7426f,0f,-0.6443f,-1.6807f,0.4532f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7946f,-0.1395f,1.9284f,0f,-0.1395f,-1.7946f,-2.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,-0.1569f,2.0166f,0f,-0.1569f,-1.7932f,-1.2089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7985f,0.0741f,1.9433f,0f,0.0741f,-1.7985f,-0.1141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7554f,0.3981f,1.7473f,0f,0.3981f,-1.7554f,0.5724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"hitbox_body_0":{"px":0,"py":1.1339516953,"pz":-0.377125636,"ry":0,"rx":12.7766666667},"hitbox_body_1":{"px":0,"py":0.6293220964,"pz":1.8871887906,"ry":0,"rx":1.6666666667},"pos_head":{"px":0,"py":1.7801986058,"pz":3.7599335728,"ry":0,"rx":5.5566666667},"hitbox_head_0":{"px":0,"py":1.1688350168,"pz":3.7004556395,"ry":0,"rx":5.5566666667},"hitbox_tail_0":{"px":0,"py":1.4461981784,"pz":-1.7167460304,"ry":0,"rx":-5},"hitbox_tail_1":{"px":0,"py":1.3541986422,"pz":-2.8430728457,"ry":0,"rx":-4.4433333333},"shadow":{"px":0,"py":0.39375,"pz":0.11953125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args