# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head_lower) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,0.0785f,1.8821f,0f,0.0785f,-1.7983f,3.6382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_upper) {transformation: [-1.8f,0f,0f,0.0001f,0f,1.7983f,0.0785f,1.9128f,0f,0.0785f,-1.7983f,3.2644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7932f,0.1569f,1.8979f,0f,0.1569f,-1.7932f,2.927f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.6394f,0f,0.3126f,-1.7727f,2.5993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck_2) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.7416f,0f,0.3126f,-1.7727f,2.3031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_2) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.2728f,-1.2728f,1.0107f,0f,-1.2728f,-1.2728f,2.0442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_1) {transformation: [-1.8f,0f,0f,0.4387f,0f,1.7727f,-0.3126f,1.1866f,0f,-0.3126f,-1.7727f,1.534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left_0) {transformation: [-1.8f,0f,0f,0.4078f,0f,1.7573f,0.3896f,1.6198f,0f,0.3896f,-1.7573f,1.8361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_2) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.2728f,-1.2728f,1.0107f,0f,-1.2728f,-1.2728f,2.0442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_1) {transformation: [-1.8f,0f,0f,-0.4388f,0f,1.7727f,-0.3126f,1.1866f,0f,-0.3126f,-1.7727f,1.534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right_0) {transformation: [-1.8f,0f,0f,-0.4078f,0f,1.7573f,0.3896f,1.6198f,0f,0.3896f,-1.7573f,1.8361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_0) {transformation: [-1.8f,0f,0f,0f,0f,1.8f,0f,1.6819f,0f,0f,-1.8f,1.2906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_2) {transformation: [-1.8f,0f,0f,0.4168f,0f,1.7983f,0.0785f,0.8855f,0f,0.0785f,-1.7983f,-0.149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_1) {transformation: [-1.8f,0f,0f,0.4219f,0f,1.6314f,0.7607f,1.0649f,0f,0.7607f,-1.6314f,0.4429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_left_0) {transformation: [-1.8f,0f,0f,0.4359f,0f,1.6914f,-0.6156f,1.7368f,0f,-0.6156f,-1.6914f,0.3552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_2) {transformation: [-1.8f,0f,0f,-0.4168f,0f,1.7983f,0.0785f,0.8855f,0f,0.0785f,-1.7983f,-0.149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_1) {transformation: [-1.8f,0f,0f,-0.4219f,0f,1.6314f,0.7607f,1.0649f,0f,0.7607f,-1.6314f,0.4429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leg_right_0) {transformation: [-1.8f,0f,0f,-0.4359f,0f,1.6914f,-0.6156f,1.7368f,0f,-0.6156f,-1.6914f,0.3552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_2) {transformation: [-1.8f,0f,0f,0f,0f,1.663f,-0.6888f,1.671f,0f,-0.6888f,-1.663f,-2.3068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7573f,-0.3896f,1.8901f,0f,-0.3896f,-1.7573f,-1.3183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail_0) {transformation: [-1.8f,0f,0f,0f,0f,1.7983f,-0.0785f,1.9099f,0f,-0.0785f,-1.7983f,-0.2212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body_1) {transformation: [-1.8f,0f,0f,0f,0f,1.7727f,0.3126f,1.7473f,0f,0.3126f,-1.7727f,0.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"hitbox_body_0":{"px":0,"py":1.0886739373,"pz":-0.4447351739,"ry":0,"rx":10},"hitbox_body_1":{"px":0,"py":0.6838433922,"pz":1.8221329965,"ry":0,"rx":0},"pos_head":{"px":0,"py":1.8983186397,"pz":3.6610812746,"ry":0,"rx":2.5},"hitbox_head_0":{"px":0,"py":1.2846532696,"pz":3.6342880659,"ry":0,"rx":2.5},"hitbox_tail_0":{"px":0,"py":1.2582847991,"pz":-1.747346743,"ry":0,"rx":-12.5},"hitbox_tail_1":{"px":0,"py":0.9311747401,"pz":-2.723549768,"ry":0,"rx":-22.5},"shadow":{"px":0,"py":0.39375,"pz":0.02109375,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args