# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:karakuri_aj/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '189e1252ff6961a677e94a7d136cf03a08dd02de4ab1448674758dab3dd0c054'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack