# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.chair
function animated_java_nikuyaki:nikuyaki/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.interaction
function animated_java_nikuyaki:nikuyaki/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args