# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_body_1.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_body_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_neck_1.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_neck_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.head_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_arm_right_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_arm_left_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_right_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_right_1.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_right_2.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_right_3.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_left_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_left_1.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_left_2.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_finger_left_3.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_leg_right_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_leg_left_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_tail_0.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_tail_1.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_tail_2.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_tail_3.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.hitbox_tail_4.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.locators.shadow.uuid
function animated_java_valk:valk/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args