# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:karakuri_aj/remove/as_data
function animated_java:karakuri_aj/remove/this/without_on_remove_function