# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 run function animated_java:ranposu/animations/pose/zzz/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
execute if score @s aj.pose.frame matches -1 run function animated_java:ranposu/animations/pose/zzz/function_keyframe_loop_patch
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.pose.frame
function animated_java:ranposu/animations/pose/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.pose.frame matches 0.. run return run scoreboard players set @s aj.pose.frame -1
scoreboard players add @s aj.pose.frame 1