# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hitbox_body_1) positioned ^1.1156 ^1.6309 ^-1.4288 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_body_1
$execute as $(hitbox_body_0) positioned ^-2.0176 ^0.9799 ^-0.4928 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_body_0
$execute as $(hitbox_neck_1) positioned ^-3.1558 ^0.5184 ^-0.6029 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_neck_1
execute positioned ^-2.9304 ^0.5661 ^0.6214 rotated ~340.7584 ~49.9899 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_pos_head
$execute as $(hitbox_head_0) positioned ^-3.2657 ^-0.1607 ^0.5916 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_head_0
$execute as $(hitbox_leg_left_1) positioned ^-0.4021 ^1.2876 ^0.1991 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_leg_left_1
$execute as $(hitbox_leg_left_2) positioned ^-0.0558 ^-0.7968 ^0.3248 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_leg_left_2
$execute as $(hitbox_leg_right_1) positioned ^-1.2123 ^1.0616 ^-2.4938 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_leg_right_1
$execute as $(hitbox_leg_right_2) positioned ^-0.9031 ^-0.696 ^-3.6306 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_leg_right_2
execute positioned ^2.7944 ^3.4273 ^-2.1586 rotated ~80.4328 ~4.4968 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_pos_tail_0
execute positioned ^4.3706 ^3.3183 ^-2.267 rotated ~92.6125 ~-5.3305 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_pos_tail_1
$execute as $(hitbox_tail_1) positioned ^3.9508 ^2.2035 ^-2.1284 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_1
execute positioned ^6.2273 ^2.9326 ^-2.5205 rotated ~73.0929 ~-17.2727 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_pos_tail_2
execute positioned ^7.9741 ^2.7525 ^-3.387 rotated ~60.5418 ~-5.1316 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_pos_tail_3
$execute as $(hitbox_tail_3) positioned ^8.2187 ^1.5595 ^-3.634 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_3
execute positioned ^9.1281 ^2.2873 ^-5.3785 rotated ~29.8323 ~-19.9838 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_pos_tail_4
$execute as $(hitbox_tail_4) positioned ^9.1586 ^0.6829 ^-5.6679 rotated ~180 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_hitbox_tail_4
$execute as $(shadow) positioned ^0.5625 ^0.8375 ^-1.25 rotated ~0 ~0 run function animated_java_dino:dino/animations/damage_counter_mirror/zzz/frames/61_locator_shadow