# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_body_1
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_body_0
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_neck_0
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_head_0
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_leg_right_0
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_leg_right_1
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_leg_left_0
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_leg_left_1
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_tail_0
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_tail_1
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_hitbox_tail_2
function animated_java:karakuri_aj/remove/zzz/this/kill_locator with entity @s data.locators.locator_shadow